README.md, hello_world.py, metricflow/cli/__init__.py, metricflow/cli/main.py, pyproject.toml
First
This PR 
- Adds a few more examples to the MetricFlow tutorial i.e. `mf tutorial`
- Organizes the resources section of the Readme
- Bumps the pypi version to 0.91.9
=> Add a few more examples to the tutorial

.github/workflows/ci-metricflow-unit-tests.yaml
For this action to be required for merge it must execute on every
PR, so we remove restrictions on execution. To cut down on pointless
retries we no longer trigger on PR edit, as that includes all manner
of metadata updates like PR descriptions.
=> Make MetricFlow Unit Tests run on every PR

.github/workflows/cd-push-to-pypi.yaml
* Gives access to the Pypi secrets environment to the Pypi workflow.
* Access to that env requires approval from a list of internal approvers before the secrets can be accessed
=> fix pypi workflow by giving it access to the Pypi Publish environment secrets

metricflow/cli/main.py, metricflow/cli/utils.py
- `order` arg should be able to accept an input with multiple values separated by comma `ds,revenue`
- consolidate `metrics` and `dimensions` args intto `query_options`
=> Fix parsing order input for multiple values

metricflow/cli/cli_context.py, metricflow/sql_clients/snowflake.py
Having `client_session_keep_alive=True` the connection thread for the snowflake client was kept alive even after the program was running which caused the CLI to hang during any queries.
- removed the previous solution of using `__del__` destructor to close the connection as the issue still lingered with it
- made `client_session_keep_alive` an arg to pass to instantiate the snowflake client so that the CLI can pass `False` to it.
Similar issue: https://github.com/snowflakedb/snowflake-connector-python/issues/836
=> Fix snowflake hanging issue on CLI

metricflow/time/time_granularity_solver.py
The wrong argument was sent to the `element_name` of `MeasureReference` in two instances within the TimeGranularitySolver object. The Reference was sent and not the string name.
Solution: send the string name of the Reference, instead of the Reference.
=> Fix the format of arguments sent to two instantiations of MeasureReference

metricflow/cli/cli_context.py
When I run `mq health-checks` after specifying bigquery in `mf setup`, 
"json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)" Error occurred
I checked the code and found that cred_file.readline() in cli_context.py returns "{". 
This issue seems to be due to the assumption of a specific form of Google Cloud Platform Service Account Key.
Usually, Service Account Key is configured as follows:
```
{
"type": "service_account",
"project_id": "project_id",
"private_key_id": "private_key",
"private_key": "-----BEGIN PRIVATE KEY-----~~~",
"client_email": "mail",
"client_id": "123123",
"auth_uri": "~~~~~~~",
"token_uri": "~~~~~~~",
"auth_provider_x509_cert_url": "~~~~~~~~",
"client_x509_cert_url": "~~~~~~~~~"
}
```
To fix this issue, we need to …
=> fix: bigquery read credential issue in __initialize_sql_client

README.md
Some users accidentally include the `>` when copy/paste-ing from the README. The `>` is used to indicate the terminal commands in the README. I removed the `>` and rendered the code as code blocks to clearly indicate the code.
**BEFORE** with the `>`
<kbd>
</kbd>
**AFTER** without the `>`
<kbd>
</kbd>
=> [README] Removing > from commands

metricflow/cli/__init__.py, metricflow/cli/main.py, metricflow/test/cli/test_cli.py
We are using `pyproject.toml` to package the library to publish to pypi. Since the `.toml` wasn't able to read from another file and the cli code couldn't reach outside the top-level directory, we needed a way to sync the current version of the library without having to hardcode the version on both `pyproject.toml` and `metricflow/cli/__init__.py`. Instead, we can aggregate the current package version using `importlib.metadata.version` in the CLI. This allows us to keep the hardcoded version in 1 file which is inside `pyproject.toml`
- Removed version in `metricflow/cli/__init__.py`
- Use `importlib.metadata` to get current package version in CLI
- Added test for version CLI command
=> Sync package version handling

metricflow/time/time_granularity_solver.py
There was a duplicate `MeasureReference` definition hiding in time granularity solver. It is deleted in this PR, and the usages of `MeasureReference` now point to our singular definition of `MeasureReference`.
=> Removing duplicate MeasureReference definition

metricflow/test/fixtures/model_yamls/composite_identifier_model/messages_source.yaml, metricflow/test/fixtures/model_yamls/composite_identifier_model/users_source.yaml, metricflow/test/fixtures/model_yamls/extended_date_model/data_sources/bookings_from_sql_query_source.yaml, metricflow/test/fixtures/model_yamls/extended_date_model/data_sources/bookings_monthly_source.yaml, metricflow/test/fixtures/model_yamls/extended_date_model/data_sources/extended_bookings_source.yaml, metricflow/test/fixtures/model_yamls/extended_date_model/data_sources/listings_extended_source.yaml, metricflow/test/fixtures/model_yamls/join_types_model/bookings_source.yaml, metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/account_month_txns.yaml, metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/bridge_table.yaml, metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/customer_other_data.yaml, metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/customer_table.yaml, metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/third_hop_table.yaml, metricflow/test/fixtures/model_yamls/multi_hop_join_model/unpartitioned_data_sources/account_month_txns.yaml, metricflow/test/fixtures/model_yamls/non_ds_model/bookings_source.yaml, metricflow/test/fixtures/model_yamls/non_ds_model/listings_latest.yaml, metricflow/test/fixtures/model_yamls/simple_model/data_sources/id_verifications.yaml, metricflow/test/fixtures/model_yamls/simple_model/data_sources/listings_latest.yaml, metricflow/test/fixtures/model_yamls/simple_model/data_sources/revenue.yaml, metricflow/test/fixtures/model_yamls/simple_model/data_sources/user_ds_source.yaml, metricflow/test/fixtures/model_yamls/simple_model/data_sources/users_latest.yaml, metricflow/test/fixtures/model_yamls/simple_model/data_sources/views_source.yaml, metricflow/test/model/validations/test_data_sources.py, metricflow/test/model/validations/test_dimension_const.py, metricflow/test/model/validations/test_element_const.py, metricflow/test/model/validations/test_identifiers.py, metricflow/test/model/validations/test_metrics.py
MetricFlow no longer requires `time_format` for time dimensions. 
This PR removes `time_format` from all sample models and tests.
=> Removing time_format (legacy)

metricflow/cli/main.py, metricflow/dag/dag_visualization.py, metricflow/test/dataflow_plan_to_svg.py, pyproject.toml
Moving these methods out will fix dependencies on the test environment.
=> Move DAG Visualization Methods out of test/

metricflow/model/model_validator.py, metricflow/model/validations/dim_names.py, metricflow/model/validations/materializations.py, metricflow/test/model/validations/test_materializations.py, metricflow/test/test_utils.py
Problem: Materializations did not have validation coverage
Solution: Added coverage within the `ModelValidator` for Materializations. In addition, we altered some of the attributes of Materialization to default to empty list instead of None to avoid returning null when returning a collection. In addition, some supplemental methods were added to other objects for easier usage of them.
=> Adding Materialization checks to Validations

metricflow/model/model_validator.py, metricflow/test/model/validations/test_common_identifiers.py
This validation added a nonblocking warning to the resulting validation issues.
Removing this warning is generally what customers want as the lone identifier doesn't cause any problems.
=> Removing Unnecessary Lone Identifiers Validation

CHANGELOG.md, attribution.md, pyproject.toml
We would like to make the initial developer API available as part of the
standard libary installation, so we are deploying a new release today.
This includes the relevant updates to the changelog, attribution, and
project version files.
=> Release PR for MetricFlow 0.93

metricflow/model/model_validator.py, metricflow/model/parsing/dir_to_model.py, metricflow/model/validations/identifiers.py, metricflow/test/model/validations/test_identifiers.py
Adding Validation and Test for Composite Identifiers
MetricFlow enforces that each identifier is defined uniquely, one aspect of this is that the sub identifiers are the same.
This is not a problem when an identifier is only requested once in a model. But this can become a problem when a model requests the same identifier across multiple data sources of a model. Each time that identifier is requested, it must share the same sub-identifier structure.
Defaulting the issues attribute of ModelBuildResult to an empty tuple for more intuitive handling.
=> Composite identifiers validation

metricflow/engine/metricflow_engine.py, metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/semantic_containers.py, metricflow/query/query_parser.py, metricflow/test/model/test_data_source_container.py
This PR adds the `LOCAL_LINKED` property to indicate if an available dimension for a metric is the same as a local one, but linked with a local primary identifier. For example, if a data source has the primary identifier `listing` and dimension `capacity_latest`, then the dimension `listing__capacity_latest` for a measure in that data source would have the property `LOCAL_LINKED`.
This also updates the function for getting available dimensions for a metric to use properties, instead of a set of flags.
=> Add LOCAL_LINKED Property for Available Dimensions

metricflow/model/semantics/linkable_spec_resolver.py, metricflow/test/model/semantics/test_linkable_spec_resolver.py
When retrieving valid linkable elements for a metric, a set of properties can be specified to filter the list returned. This PR adds the IDENTIFIER property to local identifiers, and also improves test coverage by adding tests for all properties.
=> Add IDENTIFIER Property to Local Identifiers

metricflow/model/validations/materializations.py
Since the materialization validation was recently introduced, this changes the issue type to warning to that migrations are easier.
=> Use Warnings for Materialization Validations

metricflow/model/objects/common.py, metricflow/model/objects/data_source.py, metricflow/model/objects/elements/measure.py, metricflow/model/objects/materialization.py, metricflow/model/objects/metric.py, metricflow/model/parsing/dir_to_model.py
Metadata field was missing from the Model objects and it should be surfaced as it contains useful data about the model objects. For example, for a metric, it would show which file config it was parsed from and the sliced raw yaml block.
- Added `Metadata` to
- `DataSource`
- `Metric`
- `Materialization`
- `Measure`
- Fixed the parser to properly parse the metadata context for each object
=> Add Metadata to Model objects

metricflow/api/metricflow_client.py, metricflow/cli/main.py, metricflow/model/model_validator.py, metricflow/test/model/validations/test_common_identifiers.py, metricflow/test/model/validations/test_configurable_rules.py, metricflow/test/model/validations/test_dimension_const.py, metricflow/test/model/validations/test_element_const.py, metricflow/test/model/validations/test_identifiers.py, metricflow/test/model/validations/test_measures.py, metricflow/test/model/validations/test_metrics.py, metricflow/test/model/validations/test_unique_valid_name.py
This PR makes the ModelValidator configurable. Specifically it makes it so that the lists of rules that are run is configurable. This is important because it powers two important use cases. There are times when people only want to run a subset of rules (for instance when the only thing that was changed were the dimensions in a metric) or where custom validations are needed (for instance if someone extends the parsing schema so that all data sources have owners and they want to validate all data sources have owners).
```
from metricflow.model.model_validator import ModelValidator
ModelValidator().validate_model(your_model)
```
```
from metricflow.model.model_validator import ModelValidator
from metricflow.model.validations.metrics import MetricMeasuresRule …
```
=> Update ModelValidator to allow for a configureable list of rules

metricflow/cli/main.py
Previously the validate-configs command only printed the success message if the 'build_result.issues' was 'None'. However, the current implementation of the ModelValidator returns an empty tuple for the issues when there are no issues. Thus the validate-configs command never printed the success message. This change checks the boolean value of 'build_result.issues' which evaluates to 'False' for 'None' and empty sequences.
Previously this was the appearance of running `validate-configs` when there are no issues:
```
$ mf validate-configs
```
This is now the appearance of running `validate-configs` when there are no issues:
```
$ mf validate-configs
✅ Validation completed! No issues were found.
```
=> Make validate-configs print success message when there are no issues

metricflow/model/objects/data_source.py, metricflow/model/objects/elements/dimension.py, metricflow/model/objects/elements/identifier.py, metricflow/model/objects/elements/measure.py, metricflow/model/objects/materialization.py, metricflow/model/objects/metric.py
Similar to https://github.com/transform-data/metricflow/pull/75 we will add addition metadata onto the model objects for extra details, specifically 
- description
- owners
=> added description/owners to model objects

metricflow/model/parsing/dir_to_model.py
`ParsingContext` is loaded via the yaml loader, but I can't think of a good way to pass the filepath to the custom Loader. In the custom Loader we just put the filename as a literal string `'<unicode string>'` [here](https://github.com/transform-data/metricflow/blob/main/metricflow/model/parsing/yaml_loader.py#L33) listed as `node.start_mark.name`. This causes the parser to use `'<unicode string>'` as the filename/filepath.
Originally, it was done this way where we pass the filepath through the `parse` method, but it was a bit janky so I removed it. Now I realized we actually needed it in order to retrieve the filepath for each object we parse or else we'll just have the filepath correct on the first node and the rest of the child nodes will have `'<unicode string>'`
=> add `filepath` to method signature instead of getting from ParsingContext

metricflow/test/integration/test_configured_cases.py
This PR calls `pytest.skip` for tests that can't be run on a given SQL engine instead of logging to provide better visibility to the user.
=> Use pytest.skip for configured tests that can't be run

metricflow/model/parsing/dir_to_model.py
The model directory contains the YAML files that define the semantic model. Currently, it parses all YAML files in the directory, but hidden files and directories should be skipped (e.g. `.git`).
=> Skip Hidden Directories and Files in the YAML Model Directory

metricflow/cli/main.py, metricflow/object_utils.py, metricflow/protocols/sql_client.py, metricflow/sql_clients/big_query.py, metricflow/sql_clients/redshift.py, metricflow/sql_clients/snowflake.py, metricflow/sql_clients/sqlite.py, metricflow/test/sql_clients/test_sql_client.py
This PR add a method to `SqlClient` to enable cancelling of running queries. This could be useful if a large query is submitted by mistake and the user wants to cancel running it.
=> Add Method to Cancel Running Queries

metricflow/cli/main.py, metricflow/model/data_warehouse_model_validator.py, metricflow/test/fixtures/cli_fixtures.py, metricflow/test/fixtures/model_fixtures.py, metricflow/test/fixtures/model_yamls/data_warehouse_validation_model/data_sources/data_source1.yml, metricflow/test/model/validations/test_data_warehouse_tasks.py, metricflow/test/snapshots/test_data_warehouse_tasks.py/data_warehouse_validation_model/test_build_metric_tasks__query0.sql
Perhaps the most important data warehouse validation is ensuring all metrics defined in the model will run in the data warehouse. This PR adds metric based data warehouse validations to the `DataWarhouseModelValidator`. Additionally, these validations are now run as part of `validate-configs`
=> Add Metric based Data Warehouse Validations

metricflow/test/integration/configured_test_case.py, metricflow/test/integration/test_configured_cases.py
This PR changes the integration test case repository defined in the test module  from an internal variable name to a public variable name so that it can be imported and used for other testing purposes.
=> Expose Integration Test Case Repository

metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/third_hop_table.yaml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_composite_identifier__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_composite_identifier_with_join__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_composite_identifier_with_order_by__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_multihop_node__plan0.xml
This PR fixes the data source definition for `third_hop_table` to remove a dimension that's not listed in the source table.
=> Fix 'third_hop_table' Data Source Definition

metricflow/cli/main.py, metricflow/model/data_warehouse_model_validator.py, metricflow/test/model/validations/test_data_warehouse_tasks.py
This PR adds dimension based data warehouse validations to the DataWarhouseModelValidator. Additionally, these validations are now run as part of validate-configs
=> Add Dimension Data Warehouse Validations

README.md
**Issue opened here**: https://github.com/transform-data/metricflow/issues/56 
**Why:** The tutorial section has a Step 7 with the original code `mf query --metrics transactions --dimensions ds --order ds --explain -- display-plans` (note the extra space prior to the `display-plans`). This was throwing an error. 
**What was changed:** Removing the space prior to `display-plans` to fix the command, now showing up as `mf query --metrics transactions --dimensions ds --order ds --explain --display-plans`
=> Removing extra space in the MetricFlow tutorial in Step 7 of the README.md file 

metricflow/model/data_warehouse_model_validator.py, metricflow/model/validations/element_const.py, metricflow/protocols/sql_client.py, metricflow/sql_clients/base_sql_client_implementation.py
We used to use a lot of reST style doc strings in our infrastructure. After cutting things over to metricflow we started using google style docstrings for documenting classes / methods / etc. However, not everything got converted over, there were still some stragglers. This PR simply makes sure any docstrings following the old reST style now follow the google style.
=> Clean up docstrings to ensure all follow google docstring formatting

CONTRIBUTING.md, Makefile, local-data-warehouses/Makefile, local-data-warehouses/README.md, local-data-warehouses/postgresql/docker-compose.yaml
As the title. 
In a separate window:
```
make postgresql
```
In the main window:
```
make test-postgresql
```
All tests fail until #99 lands.
=> docs(sql-client): add instructions to run tests against local postgres

metricflow/model/model_transformer.py, metricflow/test/fixtures/model_fixtures.py, metricflow/test/model/transformations/test_configurable_transform_rules.py
Currently, we have a set of rules that gets ran for transforming the model pre/post validation. However, this isn't extensible in a way that we can't customize it for certain scenarios. So similarly to the `ModelValidator` changes, we would want to make it so we can pass custom rules that can be ran during transformation without having to run the preset rules all the time.
- Enable the ability to pass custom build `ModelTransformRule` into the `rules` param to run those custom rules instead of the default rules
=> Add the ability to pass custom rules to ModelTransformer

metricflow/test/cli/test_cli.py, metricflow/test/fixtures/cli_fixtures.py
Currently, we test the CLI without any integration with the MF engine as we mock all the returned results and just check that the CLI returns properly and displays the proper results. This is an _okay_ approach, but we would like to test with the real thing rather than mocking an integral component to the CLI engine.
- removed the mocked `MetricFlowEngine`, `SemanticModel`, `UserConfiguredModel`
- Test the CLI with the `simple_user_configured_model` model
- Added a test for `health_checks` command
=> Test CLI without mock MF engine

.gitignore
Visual Studio Code stores a bunch of project-level IDE configuration stuff
in the .vscode directory in the local repo. We do not want these committed
to the metricflow project, so we ignore anything in that location by default.
=> Add .vscode/ entry to .gitignore

metricflow/sql_clients/duckdb.py, metricflow/test/cli/test_cli.py
This PR adds multi-threading support for the DuckDb client. While threading is not currently used in the repo, there are dependent use case that can benefit from this.
=> Add multi-threading support for DuckDB

metricflow/cli/main.py, metricflow/cli/utils.py, metricflow/sql_clients/duckdb.py, metricflow/sql_clients/sql_utils.py
This PR enables the use of DuckDB as a dialect, which is useful for testing the CLI in a standalone setup.
=> Add CLI Support for DuckDB

metricflow/cli/main.py, metricflow/model/data_warehouse_model_validator.py, metricflow/model/validations/common_identifiers.py, metricflow/model/validations/data_sources.py, metricflow/model/validations/dimension_const.py, metricflow/model/validations/element_const.py, metricflow/model/validations/identifiers.py, metricflow/model/validations/materializations.py, metricflow/model/validations/metrics.py, metricflow/model/validations/non_empty.py, metricflow/model/validations/unique_valid_name.py, metricflow/model/validations/validator_helpers.py, metricflow/test/cli/test_cli.py, metricflow/test/model/validations/helpers.py, metricflow/test/model/validations/test_configurable_rules.py, metricflow/test/model/validations/test_data_sources.py, metricflow/test/model/validations/test_data_warehouse_tasks.py, metricflow/test/model/validations/test_dimension_const.py, metricflow/test/model/validations/test_element_const.py, metricflow/test/model/validations/test_identifiers.py, metricflow/test/model/validations/test_materializations.py, metricflow/test/model/validations/test_metrics.py
Historically we have used model_object_reference (an OrderedDict) to give context to ValidationIssues. However, this has some drawbacks. First the OrderedDict could be over specified (i.e. what if both a dimension and a measure name are specified?). Second it's not easily JSON serializable. Thus we've moved to something more concrete, ValidationContext and sub-classes thereof. This new class, and sub-classes, provides a hierarchy of contexts which all provide the same interface for generating human readable context strings. Additionally, ValidationContexts are of our specifically JSON serializable 'BaseModel' class. The one hickup is that in most cases we want to generate the ValidaitonContext from an available 'Metadata' object for 'DataSources', 'Metrics', and 'Materializations'. It'd …
=> Improve Validation Issue Context

poetry.lock, pyproject.toml
It looks like there was an update in duckdb `0.4.0` to better support multithreading: 
https://github.com/duckdb/duckdb/pull/3886
However, internal concurrency testing with `0.4.0` is throwing seg faults when removing the `check_same_thread` flag, so downgrading to the previous tested version - `0.3.4`.
=> Use DuckDB 0.3.4

metricflow/cli/main.py, metricflow/engine/utils.py, metricflow/model/parsing/config_linter.py, metricflow/test/cli/test_cli.py, metricflow/test/fixtures/model_fixtures.py, metricflow/test/fixtures/model_yamls/config_linter_model/multiple_data_sources_without_divider.yml, metricflow/test/model/test_config_linter.py, poetry.lock, pyproject.toml
There have been issues with YAML config files such as missing "---" dividers between top level object. That specific issue meant that if there were multiple metrics defined in a file, but missing the "---" dividers between them, all the metrics would be silently swallowed except the last specified in the file. The new errors people will see when validating their configs will look like the following:
```
✖ Breaking issues found in config yaml files
• ERROR: in file `opportunities.yaml` on line #84 - duplication of key "metric" in mapping. Key "metric" is a top level object. If multiple top level objects are specified in the same file, they must be separated using "---"
```
=> Lint YAML Config Files before processing

poetry.lock
This PR simply bumps the numpy version to the latest (`1.22.4 -> 1.23.0`) with a `poetry update numpy`.
Numpy `1.22.4` was breaking metricflow on my computer, making it break with a failed import of `numpy.core.multiarray`. Updating it seems to have fixed the issue.
Screenshot of the issue:
=> bump numpy version

metricflow/model/model_validator.py
I noticed while working on a separate branch that the `validate_model` return logic had three statements which all did the same thing. This refactor just simplifies that logic so it only has one return and is less confusing.
=> Simplify 'validate_model' return flow logic

.github/workflows/cd-sql-engine-tests.yaml
Engine-specific tests currently only run for things under
metricflow/test/integration, but that does not cover all of the
engine-specific test cases. We need to run them on any test that
might generate engine-specific plan files, and also any test that
targets the SqlClient classes themselves.
=> Run the full test suite for engine-specific tests

.github/workflows/cd-sql-engine-tests.yaml
Previously, the SQL Engine tests were triggered under three conditions,
only one of which has proved useful:
1. PR label: this worked correctly and behaved exactly as we would hope
2. Schedule: this worked correctly in the main repo, but had other problems
3. PR submission/update: this never worked correctly
This commit replaces the schedule and PR submission triggers with a
dispatch on push to the main branch. We do this for the following reasons:
1. The schedule causes problems with forked repos since they would not
have the appropriate configuration for running these tests by default.
Furthermore, the scheduled runs were never approved internally, so they
were simply sitting there waiting for eternity and providing no value.
2. The PR submission runs were quite noisy - we generally …
=> Refine triggers for SQL Engine Test actions

metricflow/instances.py
It came up in another PR, #128 that we should be using *Reference classes for referencing things like data source, metrics,
materializations, and etc. Those all existed, except for materializations. This PR simply adds that class and nothing extra. I'm doing it as a separate PR simply because it's unrelated to #128 except for the fact that #128 requires its existence.
=> Add MaterializationModelReference

metricflow/model/objects/constraints/where.py, metricflow/test/constraints/test_where.py
The parser we use for the WHERE clause returns a JSON-like structure
with dict types representing key/value pairs for things like literals
and function definitions. For a function taking arguments, the key
would be the name of the function and the value would be a list of
arguments, which themselves could be strings, lists, or dicts.
For any function taking no arguments, such as CURRENT_DATE(), or one
taking keywords, such as CAST(x AS DOUBLE), the parsed output would
represent the keywords (or empty set of arguments) as an empty dict.
Since we recursively call a helper that asserts that the dict contains
exactly one key, our parsing logic throws an error on such input.
This commit simply moves that assertion where it belongs - into the
first call into the recursive processing function, …
=> Fix where clause parsing for empty functions

metricflow/model/model_validator.py, metricflow/model/objects/elements/measure.py, metricflow/model/semantics/semantic_containers.py, metricflow/model/validations/agg_time_dimension.py, metricflow/test/model/validations/test_agg_time_dimension.py, metricflow/test/plan_utils.py
This PR adds a validation rule that ensures that the aggregation time dimension set for a measure in a data source references a valid time dimension in the same data source.
=> Validate Aggregation Time Dimension for Measures

metricflow/api/metricflow_client.py, metricflow/cli/main.py, metricflow/model/data_warehouse_model_validator.py, metricflow/model/model_validator.py, metricflow/model/parsing/config_linter.py, metricflow/model/parsing/dir_to_model.py, metricflow/model/validations/agg_time_dimension.py, metricflow/model/validations/common_identifiers.py, metricflow/model/validations/data_sources.py, metricflow/model/validations/dimension_const.py, metricflow/model/validations/element_const.py, metricflow/model/validations/identifiers.py, metricflow/model/validations/materializations.py, metricflow/model/validations/metrics.py, metricflow/model/validations/unique_valid_name.py, metricflow/model/validations/validator_helpers.py, metricflow/test/api/test_metricflow_client.py, metricflow/test/cli/test_cli.py, metricflow/test/model/test_config_linter.py, metricflow/test/model/validations/test_configurable_rules.py, metricflow/test/model/validations/test_data_warehouse_tasks.py, metricflow/test/model/validations/test_identifiers.py, metricflow/test/model/validations/test_measures.py, metricflow/test/model/validations/test_unique_valid_name.py, metricflow/test/model/validations/test_validator_helpers.py
This PR started as the second half to #133, in that we wanted to be able to deserialize JSON-ified ValidationIssues into ValidationIssue objeccts. In doing this work we found blocking problems with the structure of `ValidationIssues` and `ValidationContext` which stopped the magical parsing of Pydantic `BaseModel` from working. This in turn lead to a refactor to the structure of`ValidationIssues` and `ValidationContexts` so that both serialization and de-serialization of `ValidationIssues` is simple.
• The different `ValidationContexts` now contain a `FileContext` instead of inheriting from `FileContext`.
• `ValidationIssue` is now an `ABC` which the different issue types implement, making them distinct.
• There is a new `ModelValidationResults` class which should be the primary source of …
=> Refactor Validation Issue Structuring

metricflow/model/objects/common.py, metricflow/model/parsing/dir_to_model.py, metricflow/model/parsing/validation.py, metricflow/model/parsing/yaml_loader.py, metricflow/test/integration/configured_test_case.py, metricflow/test/model/parsing/test_data_source_parsing.py, metricflow/test/model/parsing/test_materialization_parsing.py, metricflow/test/model/parsing/test_metadata_parsing.py, metricflow/test/model/parsing/test_metric_parsing.py
Metricflow's YAML file loading uses two different loader types,
depending on whether we want file parsing context metadata included
in the payload or not. These were invoked via the one-line
yaml.load_all calls with the relevant parser (although sometimes we'd
use the wrong one and load context data in only to remove it later).
This causes problems with our context-aware parsing, because PyYAML
will only correctly populate the `name` field on its output nodes if
the input stream is a file-like object with the `name` property set
correctly. See the [relevant PyYAML source](https://github.com/yaml/pyyaml/blob/8cdff2c80573b8be8e8ad28929264a913a63aa33/lib/yaml/reader.py#L72-L85
) for details.
This PR streamlines the parser by centralizing our logic for converting 
an input string into a …
=> Streamline YAML loading and parsing context construction

metricflow/model/objects/data_source.py, metricflow/model/parsing/schemas.py
We don't use mutability in the OSS, but we still require it in the model configs.
- Make mutability a default to fully mutable unless stated otherwise
=> Make mutability optional on configs

metricflow/cli/main.py, metricflow/engine/metricflow_engine.py
When using `--explain` to get the SQL, it can be cluttering with all the inline description in the SQL itself.
- added a new flag `--hide-sql-descriptions` to optionally remove the inline descriptions on the returned SQL
=> add option to remove SQL descriptions

metricflow/dataflow/sql_table.py, metricflow/model/model_validator.py, metricflow/model/validations/reserved_keywords.py, metricflow/test/model/validations/test_reserved_keywords.py
This PR adds a rule which ensures when element `names` are used for sql generation (i.e. the element `expr` or `ref` aren't used) that they aren't SQL reserved keywords.
It should be known that this rule should not be a catch all. Data warehouse validations should catch these issues, but we currently don't have identifier and measure data warehouse validations (coming soon), and data warehouse validations are slow in comparison to semantic validation rules. Thus this rule is intended to catch words that are likely reserved keywords in all engines and to fail fast.
=> Add SQL Reserved Keyword Semantic Rule

.github/workflows/cd-sql-engine-tests.yaml
Not testing PostgreSQL means we forget to do important things
like keep the PostgreSQL plans up to date or just generally run
the test suite against it.
This PR adds it to the action so any time we trigger a full
SQL engine test run PostgreSQL will be included.
=> Add PostgreSQL tests to SQL Engine test github action

metricflow/dataset/dataset.py, metricflow/model/validations/unique_valid_name.py, metricflow/test/model/validations/test_unique_valid_name.py
With the advent of the metric_time query construct it has effectively
become a reserved keyword for Metricflow, as we cannot resolve queries
that are requesting `metric_time` if there is some other time dimension
also named `metric_time` in the user model.
This commit adds a general MetricFlowReservedKeywords enumeration and
adds a validation check to assert that none of the checked names
match a value in the enum.
=> Disallow metric_time as an element name

README.md, pyproject.toml
Our pypi page is essentially blank, and it appears this is because
we have not filled out the pyproject.toml fields poetry requires
to push any of our useful information to pypi.
With other package managers it's possible to customize the pypi
description to render, e.g., a brief header followed by the
changelog. Poetry does not allow this, and instead requires a pointer
to a README.md or some other specific readme location/format combo,
so as a comprise the changelog is now linked from the top of the
README.md as well.
=> Add readme and other metadata info to pyproject.toml

metricflow/cli/main.py, metricflow/model/data_warehouse_model_validator.py, metricflow/test/model/validations/test_data_warehouse_tasks.py
This change is two fold. First generating queries for measures and identifiers is fair bit harder than the queries we'd been generating for data_sources and dimensions, which was going to increase the complexity of the task builder greatly. So we wanted to begin using the tools the rest of MetricFlow uses for generating queries, no need to reinvent the wheel. Additionally, by using the `sql_query_plan_renderer` we ensure validation queries are similar to what MetricFlow would render using the same elements.
**TLDR**: This makes future work on data warehouse validations easier and makes validations consistent with the rest of MetricFlow.
=> Refactor data warehouse validations to use 'sql_query_plan_renderer'

metricflow/cli/main.py, metricflow/model/model_validator.py, metricflow/test/cli/test_cli.py
This might be a premature improvement, but it is a matter of time before it becomes absolutely necessary. Semantic validations are CPU bound. They don't depend on any external information. As we add more semantic validation rules and as configs grow larger, semantic validations become slower. Additionally, semantic validations don't depend on one another and they don't alter the underlying model. Thus the straight forward solution is to allow more CPU threads to be thrown at them. On a small config, there is virtually no difference in runtime currently. On exceedingly  large configs, time gains are seen (and to different degrees based on how many threads there are).
=> Multi-Thread Semantic Validations

metricflow/dataflow/sql_table.py, metricflow/model/data_warehouse_model_validator.py, metricflow/model/objects/base.py, metricflow/model/objects/constraints/where.py, metricflow/model/objects/metric.py, metricflow/model/parsing/schema_validator.py, metricflow/test/model/validations/test_reserved_keywords.py, mypy.ini
Metricflow originally used the stock mypy options for typechecking,
but recent PRs involving more direct worth with Pydantic and
jsonschema objects and methods (which tend to be Any or incompletely
typed due to the nature of JSON values) has resulted in a
proliferation of incompletely typed methods.
This commit adds a mypy.ini with a few initial options in place to
rein in potential accidental spread of Any types and incompletely typed
methods, and fixes the relevant mypy errors. We do this in one
fell swoop just because the total number of errors was fairly small.
=> Increase strictness of mypy typechecking

metricflow/dataflow/sql_table.py, metricflow/model/objects/base.py, metricflow/model/objects/constraints/where.py, metricflow/model/objects/metric.py, metricflow/test/model/parsing/test_model_deserialization.py
The initial cutover to using Pydantic-native parsing via input
validator overrides only allowed for dict-type or class instance inputs
on a per-model object basis. For example, the SqlTable class would
only accept strings or SqlTable objects, and every individual
class implementing our PydanticCustomInputParser base was responsible
for handling dict or calling class type inputs.
The issue with this object-by-object approach is any time someone
either uses direct initialization or, more importantly, uses Pydantic
to serialize and deserialize a model, they will encounter failures
whenever a value needs to be parsed by pydantic through one of these
custom override classes unless every single one of them implements
the relevant instance conditions.
This change centralizes that logic by moving …
=> Enable custom Pydantic model deserialization

metricflow/cli/main.py, metricflow/model/validations/validator_helpers.py
The original implementation of ValidationIssue.as_readable_string
included a reference to click formatting that color-coded the
issue level. This looks great in the CLI, but in contexts where
that gets converted to plain text it inserts a bunch of unicode
sequences into the header of the error message, making the exception
traces harder to read.
This splits that behavior into a CLI-focused method and base method.
Local testing confirms the CLI output is unchanged, while error logs
no longer contain the unicode markers.
=> Make validation issue strings plain text by default

metricflow/test/model/validations/test_data_warehouse_tasks.py
Pytest fixtures only get invoked when they are included in the fixture,
call graph, so the session-scoped fixture was getting called once in
this test module. This worked out fine as long as the test case
referencing the fixture was invoked before the test cases that
needed it, but that isn't guaranteed to happen when parallel
execution gets involved.
This should resolve the issue by ensuring the fixture is invoked when
needed.
=> Ensure warehouse validation tables exist when needed

metricflow/dataflow/sql_column.py, metricflow/errors/errors.py, metricflow/inference/context/base.py, metricflow/inference/context/data_warehouse.py, metricflow/inference/context/snowflake.py, metricflow/test/dataflow/test_sql_column.py, metricflow/test/inference/context/test_data_warehouse.py, metricflow/test/inference/context/test_snowflake.py
This PR adds an inference context provider that fetches min, max, unique and null count statistics from a given set a tables.
This functionality will be useful for implementing inference rules about that set of tables, e.g, columns ending with "_id" are probably primary or foreign keys.
It is the first step towards data source configuration inference.
For this to be in a minimally usable state, we still need to do the following (which will come on subsequent PRs):
- Implement basic inference rules such as "`_id` columns are probably IDs". Those rules will produce "signals", contextual pieces of evidence about a table or a column.
- Implement an inference policy that coerces signals about a column into some useful piece of information, such as "this column is an ID"
- Implement an …
=> Add data warehouse context provider for inference

metricflow/dataflow/sql_column.py, metricflow/inference/context/base.py, metricflow/inference/rule/base.py, metricflow/inference/rule/defaults.py, metricflow/inference/rule/rules.py, metricflow/test/inference/rule/conftest.py, metricflow/test/inference/rule/test_base.py, metricflow/test/inference/rule/test_defaults.py, metricflow/test/inference/rule/test_rules.py
It adds the base classes required for implementing inference rules with minimal effort. Those classes make it easy for custom rules to return signals about columns, associated with confidence scores and reasons. For example, a custom rule could return a signal as follows:
```python
InferenceSignal(
column=SqlColumn.from_names(db="db", schema="schema", table="table", column="id")
type=InferenceSignalType.PRIMARY_IDENTIFIER,
confidence=InferenceSignalConfidence.FOR_SURE,
reason="The column is named `id`"
)
```
A heuristic that reasons about a collection of signals could then use confidence values to make conclusions about a column, giving well-described reasons to the end user. It could also prevent false positives by detecting conflicting signals (see `InferenceSignal.conflict`).
Apart …
=> Add basic inference rule functionality

metricflow/dataflow/dataflow_plan.py, metricflow/dataset/dataset.py, metricflow/model/objects/data_source.py, metricflow/model/objects/elements/dimension.py, metricflow/model/objects/elements/identifier.py, metricflow/model/objects/elements/measure.py, metricflow/model/objects/metric.py, metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/semantic_containers.py, metricflow/model/transformations/agg_time_dimension.py, metricflow/model/validations/agg_time_dimension.py, metricflow/model/validations/common_identifiers.py, metricflow/model/validations/data_sources.py, metricflow/model/validations/dimension_const.py, metricflow/model/validations/identifiers.py, metricflow/model/validations/unique_valid_name.py, metricflow/plan_conversion/node_processor.py, metricflow/query/query_parser.py, metricflow/references.py, metricflow/specs.py, metricflow/test/model/test_data_source_container.py, metricflow/test/model/validations/test_dimension_const.py, metricflow/test/model/validations/test_metrics.py, metricflow/test/plan_conversion/dataflow_to_sql/test_metric_time_dimension_to_sql.py, metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py, metricflow/time/time_granularity_solver.py
Currently, all the `*Reference` and `*Spec` all lives together in the `specs.py` file. We should split these out as they have different functionality. This helps with code organization by not cluttering a file with unrelated code.
- Removed all `*Reference` classes out of `specs.py` -> `references.py`
- Moved an import in the middle of the file in `specs.py` back to the top of the file. Wasn't possible due to circular import prior to the move.
=> Separate `*Reference` classes out of specs.py

metricflow/query/query_parser.py, metricflow/test/integration/test_cases/itest_constraints.yaml, metricflow/test/integration/test_configured_cases.py
Although not recommended due to poor query optimization, this PR allows using `metric_time` in the where clause constraint.
=> Support metric_time in Where Constraints

metricflow/model/parsing/schemas.py
It seems like 9 months ago we added a 'constraint' attribute to the
'data_source_schema' in anticipation of adding a 'constraint' property to the
'DataSource' object. However, we never added this 'constraint' functionally.
Additionally, we never defined the corresponding 'constraint_schema' that would
be needed to resolve/parse this 'constraint' property.
The good news is, removing this attribute won't break anyone's configs. This is
because if someone is currently including this attribute for a data source,
parsing of the configs failed. More good news is that if we ever do want to add
a constraint attribute to data sources, we can always re-implent it.
=> Remove unused 'constraint' attribute of 'data_source_schema'

metricflow/test/integration/test_cases/itest_semi_additive_measure.yaml
Bringing this in line with the new query standard
=> Use metric_time instead of ds in semi-additive test case

metricflow/model/data_warehouse_model_validator.py
The data warehouse model validator has a helper function '_data_source_node' to
generate the data source node for the validation query. To generate the source node
the function uses the 'create_from_data_sets' function and asserted that this only
returns one node. However the function actually generate multiple nodes per data
set supplied. This was breaking data warehouse validations for any data source
where more than one source node could be returned. This commit updates
'_data_source_node' to assume that more than one node can be returned from
'create_from_data_sets' and to return the first node.
=> Update source node generator for data warehouse validations to expect >= 1 nodes

config-templates/shopify/customer.yaml, config-templates/shopify/customer_address.yaml, config-templates/shopify/inventory_item.yaml, config-templates/shopify/inventory_level.yaml, config-templates/shopify/order.yaml, config-templates/shopify/order_line.yaml, config-templates/shopify/product_variant.yaml
Shopify customers often get a bunch of useful sales and inventory data in their warehouse. Some MetricFlow users might find it convenient to include that Shopify data in their overall metric model. This commit adds a baseline set of data source files to set up an initial MetricFlow-friendly model of the underlying Shopify data.
=> Add template for shopify metric model

metricflow/inference/context/snowflake.py, metricflow/inference/rule/defaults.py, metricflow/inference/solver/weighted_tree.py, metricflow/test/inference/context/test_snowflake.py, metricflow/test/inference/rule/test_defaults.py
#204 highlighted an issue where string type columns were not being classified as dimensions.
This PR is an attempt at improving our detection there. The core of it is a new rule, which classifies a column in the warehouse as a dimension if it is both a STRING type AND relatively low cardinality (below 40% unique).
It's not clear if this is a huge improvement. It should reduce the false negative rate, which appears to be burdensome on early users, but it could result in a higher than expected false positive rate where string foreign key fields, or string fields which should be omitted (like the "name" field for a customer_organization table, where you might have a lot of duplicate entries for franchise customers or whatever). However, this rule appears to be useful, even if we need to …
=> [Inference] Classify low cardinality strings as dimensions

Makefile, metricflow/model/parsing/explicit_schema.py, metricflow/model/parsing/schemas/metricflow.json
Changes
- Adds functionality to generate an explicit json schema from the one defined throughout the metricflow parsing code.
- Adds a Makefile command to generate this explicit schema in `models/parsing/schemas`
The generated schema is similar to the one used for parsing but flattened into a single json file. Each subschema in the schema store becomes a definition, while each top level schema is a property that references it's corresponding definition. Some subschemas have their own definition sections, so for simplicity they are lifted into the single top level definitions section. 
With this change, we can easily reference schemas across tagged versions. e.g. `https://github.com/transform-data/metricflow/blob/v0.X.Y/metricflow/model/parsing/schemas/metricflow.json`. 
The next step is a …
=> Generate an explicit json schema from the parsing logic

metricflow/model/parsing/config_linter.py, metricflow/model/parsing/dir_to_model.py, poetry.lock, pyproject.toml
Other projects use MetricFlow. Some of these have custom yaml config filtering logic. By abstracting out the logic for collecting model config files we:
- Make it reusable throughout the code base
- Allow people to use it and do additional filter on the results
Also, by having functions for linting model config files paths and functions for building a model from config file paths, we allow people more flexibility than by only building the model from a directory.
Additionally, in this PR we begin using GItPython to check if a config dir is a repository, and if so ignore YAML files which are ignored via the repository's `.gitignore` file. This was an issue which cropped up because sometimes dependencies of projects include YAML files in their package.
=> Abstract logic for collecting model config files + Begin ignoring yaml files that are .gitignore'd

.github/workflows/ci-schema-consistency.yaml
Adds a Github action that is triggered when models/parsing is edited. 
The action regenerates the JSON schema using the latest changes in `models/parsing`. If the generated schema doesn't match the existing json schema in `/models/parsing/schemas/metricflow.json`, the action fails. 
This is a follow up to the work in https://github.com/transform-data/metricflow/pull/211
I'm not sure a great way to test Github actions so I tested against a forked repo to avoid spamming metricflow's Github Action log; a failure looks like this: https://github.com/jack-transform/metricflow-jckelly-test/runs/7968193985?check_suite_focus=true
=> Github Action to check JSON schema consistency

metricflow/model/objects/elements/measure.py, metricflow/model/validations/agg_time_dimension.py, metricflow/test/model/validations/test_agg_time_dimension.py
If the user fails to include either a primary time dimension or a
measure-specific aggregation time dimension for a measure in their
model they will encounter an assertion check either during validation
or querying. The original error message was really intended for
developers, but it is incidentally raised in validation. This quick fix
makes it a bit more user-friendly.
=> Improve error message for missing aggregation time dimension

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/plan_conversion/instance_converters.py, metricflow/test/integration/test_cases/itest_semi_additive_measure.yaml
When using the transform function `ChangeMeasureAggregationState` if a measure instance has a spec with a non-null `NonAdditiveDimensionParameters` it ends up not copying it over along with it. This caused errors when filtering elements such as 
```python
MeasureSpec(element_name=x, non_additive_dimension=<not None>) not in
[...,MeasureSpec(element_name=x, non_additive_dimension=None),...]
```
Also removed the previous workaround which was removing the non_additive_dimension property from MeasureSpec during measure aggregation, but that was incorrect.
=> BUG: ChangeMeasureAggregationState wasn't copying the MeasureInstance fully

metricflow/model/parsing/explicit_schema.py, metricflow/model/parsing/schemas/metricflow.json
In https://github.com/transform-data/metricflow/pull/211 (generating an explicit JSON schema), I made the mistake of using the schema names as the names of the properties at the top level of the generated Metricflow schema. 
Materialization objects are defined by a schema named `materialization_schema`, so right now the schema matches `materialization_schema` for materialization definitions as opposed to the correct `materialization`. This fixes the schema to match materializations properly. (I also fixed `derived_identifier`, but it appears this may not no longer be in use)
=> Fix the names of the top level objects in the generated schema.json

metricflow/dataflow/builder/node_evaluator.py, metricflow/dataflow/builder/partitions.py, metricflow/model/semantic_model.py, metricflow/model/semantics/semantic_containers.py, metricflow/plan_conversion/instance_converters.py, metricflow/plan_conversion/node_processor.py, metricflow/protocols/semantics.py, metricflow/query/query_parser.py
Many of our internal operations for building and converting dataflow
plans rely on our semantic containers (DataSourceSemantics and
MetricSemantics). These containers pull in a lot of dependencies and
also allow callers to modify them on the fly by adding data sources
or metrics to them.
This PR adds more limited scope accessor-only Protocols for
DataSourceSemantics and MetricSemantics, and converts all
relevant references to use it instead of the concrete implementations
found in semantic_containers.py
This gives us more protection against inadvertent use of methods
like `DataSourceSemantics.add_data_source` and limits the scope of
transitive imports running through our semantic_containers module.
=> Add protocols for read-only semantic containers

metricflow/model/validations/materializations.py
Many things can cause building of the `SemanticModel` from the `UserConfiguredModel`
to blow up. Notably, if a dimension/measure referenced by a metric doesn't exist.
This has caused the Materializations Validation to fail, even if the issue is
unrelated to materializations. Additionally, a very arcane error message was being
output because part of the issue raised includes the arguments to the called
function, which in this case was the entire `UserConfiguredModel`.
This PR aims to fix the problem by handling the error and letting the user
know what went wrong in a friendly manner.
=> Handle exception during building SemanticModel in materializations validation

metricflow/dataclass_serialization.py, metricflow/test/test_dataclass_serialization.py, poetry.lock, pyproject.toml
Our dataclass deserializer was crashing whenever we encountered a serialized value
at rest that did not have a value for a newly added dataclass field with a fallback
default. This makes it impossible to safely add new fields, even if they are strictly
optional and can be defaulted to None or something similar.
This PR fixes the default value propagation and does bits and piece of cleanup
along the way in an effort to make this a little less cumbersome to work with.
=> fix dataclass deserializer errors

.github/workflows/cd-push-to-pypi.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, .github/workflows/ci-schema-consistency.yaml, CONTRIBUTING.md
We have recently seen persistent build failures in GitHub's CI
environments due to missing dependency files. Other repos have
triggered this following Poetry's release of 1.2.0, so this commit
pins our poetry install version back 1.1.15 inside of our CI/CD
configuration files.
The issue appears to arise from disabling the virtualenvs.create
configuration option in Poetry. We have opened an issue for this:
https://github.com/transform-data/metricflow/issues/245
=> Pin Poetry to 1.1.15 in CI/CD configs

metricflow/model/objects/elements/dimension.py, metricflow/model/objects/elements/identifier.py, metricflow/test/model/parsing/test_data_source_parsing.py
Previously we hadn't been tracking the metadata/config file context for dimensions and identifiers. Doing so allows us to provide better context during validations (giving line numbers). Additionally it's useful for model investigating/debugging for projects using MetricFlow.
Additionally we this PR refactors the initialization of identifier objects to use pydantic's initializer and validators instead of a custom `__init__` method which clobbers pydantic initialization. This was necessary as part of this PR because it was required for metadata parsing to work for identifiers.
=> Add metadata context info to dimensions and identifiers

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/plan_conversion/node_processor.py, metricflow/specs.py, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_multihop_join_plan__dfp_0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_multihop_node__plan0.xml
This PR optimizes multi-hop candidate generation to reduce the candidate nodes that are evaluated during the building of the dataflow plan. Previously, two source nodes were used to generate a candidate for a multi-hop join when they contained any element in the query and a common identifier. The updated logic is to evaluate the requested multi-hop dimensions individually, and for each dimension, construct candidate joins only when the identifiers are of the correct the type. Then the joined nodes are deduped to produce the candidate set. Depending on the model, this can reduce the number of nodes that are evaluated during plan generation by a large multiple (>10x seen in internal models).
=> Optimize Candidate Search in Multi-Hop Joins

metricflow/model/validations/data_sources.py, metricflow/model/validations/element_const.py, metricflow/test/model/validations/test_element_const.py, metricflow/test/model/validations/test_unique_valid_name.py
Our model-level element naming validation is enforced primarily through two
validators today - the ElementConsistencyRule and the
DataSourceMeasuresUnique rule.
This PR clarifies their relationship via updates to documentation and test layout,
and restructures the behavior of the ElementConsistencyRule to be more
clear as to its purpose.
=> Improve clarity of model-level element naming validation operations

metricflow/model/model_validator.py, metricflow/model/validations/data_sources.py, metricflow/model/validations/measures.py, metricflow/model/validations/metrics.py, metricflow/test/model/validations/test_configurable_rules.py, metricflow/test/model/validations/test_measures.py, metricflow/test/model/validations/test_metrics.py
The addition of measure constraints opens up the possibility of
two different variations on the same measure. When this happens users
must provide an alias for each distinctly constrained variation of
the input measure.
This adds a validator to enforce that model contract, and to provide
better user-facing error messages than whatever inscrutable SQL
errors might arise as a result of rendering two different measure
inputs with the same alias. We also enforce our standard naming
constraints, including that aliases must not collide with measure
names. This last is potentially unnecessary, but until we get more
experience with our query layouts and address possible downstream
optimizations it is prudent to apply a more restrictive policy.
=> Add validation for constrained measure aliases

metricflow/sql/sql_bind_parameters.py, metricflow/test/sql_clients/test_sql_client.py
During the construction of queries where a constrained measure is used multiple times, it's possible for the SQL tree to use the same bind parameters multiple times.
=> Allow updates to SqlBindParameters if item is same

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/measure_additiveness.py
An earlier commit added a property for getting measures by additiveness,
and returned a tuple of tuples, which made it a bit unclear at the
callsite that these inner tuples were grouped by a particular key.
We change it to a dict to make that relationship more obvious.
=> Clean up measures_by_additiveness behavior

metricflow/model/model_validator.py, metricflow/model/validations/measures.py, metricflow/test/model/validations/test_measures.py
_This should be merged after this https://github.com/transform-data/metricflow/pull/253 goes in._ **actually this can be merged prior to this**
With the addition to semi-additive measures. We introduced a new `non_additive_dimension` property on measures. There are a few cases in which we need to validate such that the config is correct and ensures that the resultant query that is built is well-formed. There are 3 cases in that needs to be validated for a valid `non_additive_dimension`
1. `non_additive_dimension.name` must be a valid time-dimension in the data source
2. `non_additive_dimension.window_choice` must be either `min` or `max`
3. `non_additive_dimension_window_groupings` must be valid identifiers in the data source
=> Added Validator for non_additive_dimension property

metricflow/test/integration/test_cases/itest_semi_additive_measure.yaml, metricflow/test/integration/test_configured_cases.py
We want to support the use of `metric_time` instead of `ds` in queries when we pass it as a dimension.
=> BUG: use metric_time instead of ds

metricflow/model/parsing/schemas/metricflow.json, metricflow/model/parsing/schemas_internal.py, metricflow/test/fixtures/model_yamls/simple_model/metrics.yaml
**NOTE**
Transform's internal schema, `schemas_internal.py`, is in MetricFlow. We might one day change that, but for the time being it is where it is. Which means to modify `schemas_internal.py` we have to do so in MetricFlow.
This PR adds a concept of tags to `locked_metadata` of `schemas_internal.py` for internal metric tagging functionality we're working on.
=> Add tags to locked_metadata

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/specs.py, metricflow/test/integration/test_cases/itest_semi_additive_measure.yaml
Currently for a semi-additive measure, we can optionally add a set of identifiers to designate the grain to apply the non-additive filter. From a recent merge #253, we modified the implementation of where we did this filter join, which caused an edge case bug in which we have a window_grouping that is not passed as a dimension in the query which causes an `Invalid identifier '<one of the window_groupings that was not in query>'` Error.
Similar to adding the non-additive dimension as an extraneous linkable spec, we add all the `window_groupings` identifiers to that extraneous_linkable_spec set so that we can reference the identifiers properly during the query.
=> BUG: window_groupings should not need to be in query dimensions

metricflow/sql_clients/databricks.py
Update Databricks client to reflect the fact that indexes are not supported.
=> Update Databricks client attribute: indexes aren't supported

metricflow/sql_clients/databricks.py, metricflow/sql_clients/sql_utils.py, metricflow/test/sql_clients/test_sql_client.py
In other client implementations of create_table_from_dataframe, we
rely on the pandas.io.sql.to_sql method to convert dataframe types
to SQLAlchemy types and then issue a query via SQLAlchemy. This
uses the infer_dtype method to change any object type columns
into something more refined, since object is assigned by default
to columns containing None type values. The Pandas library also
applies a mask to convert NA types to None, which SQLAlchemy can
then insert as the appropriate null value type.
Our logic only partially covered these cases, with the result that
any None-type input in a numeric or timestamp column would fail to
upload, since Databricks naturally can't understand the `numpy.nan`
or `pandas.NaT` values that result. Worse, without the inference
in place, any boolean type …
=> Improve support for None types in Databricks create_table_from_dataframe

metricflow/sql_clients/databricks.py
Databricks appears to add UTC timezone to all DateTime columns by default if there is no timezone on table creation. This gives us inconsistent results from other warehouses. Here, we remove the timezone in query results.
=> Remove tz added by default to Databricks tables

metricflow/api/metricflow_client.py, metricflow/cli/custom_click_types.py, metricflow/cli/main.py, metricflow/cli/utils.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/query/query_parser.py, metricflow/test/integration/test_cases/itest_simple.yaml
Currently, all the interfaces requires dimensions to be a non-empty list of inputs. This should not be the case as it is possible to not pass any dimension which outputs a metric without any group by dimension and returns an aggregate value of just the metric.
- In `MetricFlowClient`, remove the requirement of a non-empty dimension input
- In the CLI, remove the requirement of a non-empty dimension input
- Restrict the ability to query for multiple metrics with no group bys due to a bug (Will re-enable once we implement cross join)
=> Enable the ability to not pass dimensions in interfaces

metricflow/test/examples/__init__.py, metricflow/test/examples/test_node_sql.py
This PR adds a test case to demonstrate a way to view SQL generated at a specific dataflow plan node.
=> Example test case for SQL generation at a dataflow plan node

metricflow/cli/main.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/protocols/sql_client.py, metricflow/sql_clients/big_query.py, metricflow/sql_clients/databricks.py, metricflow/sql_clients/duckdb.py, metricflow/sql_clients/postgres.py, metricflow/sql_clients/redshift.py, metricflow/sql_clients/snowflake.py, metricflow/test/sql_clients/test_sql_client.py
This PR adds enumerations for SQL engines that are not yet supported. There are some intermediate development uses cases where this is helpful.
=> Enumerate Future SQL Engines

.github/workflows/ci-metricflow-unit-tests.yaml, poetry.lock, pyproject.toml
Making the dbt-* dependencies optional means they aren't installed when one does `poetry add metricflow` or `pip install metricflow`. Instead one would do `poetry add metricflow -E dbt-snowflake` or `pip install metricflow[dbt-snowflake]`. In this case we support the following extras `dbt-snowflake`, `dbt-redshift`, `dbt-postgres` and `dbt-bigquery`.
This is important because installing dbt-* deps adds to MetricFlow package size fairly dramatically, thus it should only be installed if people are going to be using the dbt-MetricFlow functionality.
=> Make dbt deps optional

metricflow/model/parsing/dbt_dir_to_model.py, metricflow/model/transformations/dbt_to_metricflow.py
This builds on #279. It takes a dbt `Manifest` and builds a `UserConfiguredModel` based on the manifest's `metrics`. I believe the only thing that is missing is that this skips dbt metrics which have a `calculation_method` of `derived` because we are currently building out MetricFlow's ability to support derived metrics, and thus we'll add in a later PR.
With this version of metricflow installed to your virtual env
```
$ python
>>> from metricflow.model.parsing import dbt_dir_to_model
>>> dbt_dir_to_model.parse_dbt_project_to_model("/path/to/dbt/project/root")
ModelBuildResult(...)
```
* feature-branch--issue-266-dbt-integration
* #279 
* #280 👈 You are here
* #288
=> Add building a UserConfiguredModel from a dbt Manifest

metricflow/engine/metricflow_engine.py
Currently the CLI doesn't use the `SemanticModel` or the `UserConfiguredModel` provided by the `CLIContext`, instead it rebuilds the `SemanticModel` each time. Specifically most CLI commands use `CLIContext.mf` which directly builds the `MetricFlowEngine` from the config. Thus to build the model from dbt configs using most CLI commands, we have to update the `MetricFlowEngine.from_config` method to check how the underlying `SemanticModel`/`UserConfiguredModel` should be built, and building it accordingly.
* feature-branch--issue-266-dbt-integration
* #279 
* #280
* #288 👈 You are here
=> When building the MetricFlowEngine from config, check if building with dbt

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/engine/metricflow_engine.py, metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/semantic_containers.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/protocols/semantics.py, metricflow/query/query_parser.py, metricflow/references.py, metricflow/specs.py, metricflow/test/model/semantics/test_linkable_spec_resolver.py, metricflow/test/model/test_data_source_container.py, metricflow/test/time/test_time_granularity_solver.py, metricflow/time/time_granularity_solver.py
We currently use `MetricSpec` as a key for everything in `MetricSemantics`. This restricts us from adding properties to `MetricSpec` as we are using `MetricSpec(element_name="..")` as the key and if we were to add any properties it would end up not matching. For example,
```
MetricSpec(element_name="metric", alias="test") 
would not match 
MetricSpec(element_name="metric")
```
So in order to resolve this, replace all the usage of `MetricSpec` where we treat it as a key and replace it with `MetricReference`.
=> use MetricReference as the key for MetricSemantics

.github/workflows/ci-metricflow-unit-tests.yaml, .github/workflows/ci-schema-consistency.yaml, metricflow/engine/metricflow_engine.py, metricflow/engine/utils.py
The `dbt-*` packages are optional. This means that typically they won't be installed, and they shouldn't be installed unless you are actively developing `MetricFlow`/`dbt` functionality or using `MetricFlow`/`dbt` functionality. If `dbt-*` deps aren't installed, imports which eventually lead to dbt imports cause fatal exceptions. To get around this, we've moved the import of methods/classes which lead to dbt imports into the places they get used. Thus the exceptions will now only occur if you try to use dbt functionality without having installed an appropriate `dbt-*` dependency.
Additionally we've reverted changes to some of the github workflows which began installing the `dbt-snowflake` optional dependency.
-----
An example of the errors that were happening which no longer happen:
```
$ …
```
=> Fix dbt imports

metricflow/model/validations/validator_helpers.py, metricflow/object_utils.py, metricflow/sql/sql_exprs.py, metricflow/test/sql_clients/test_sql_client.py, poetry.lock
A type change to our `assert_values_exhausted` helper resulted in
mypy accepting Enum-typed input for that method, which opened the
door to runtime failures that mypy would have caught had the
typing remained as NoReturn.
This restores the original behavior, adds some documentation, and
fixes the broken callsites.
This PR includes some minor poetry lock file updates in a separate commit.
=> Re-establish static checking for exhaustive switch statements 

metricflow/sql_clients/databricks.py
When using databricks-sql-connector, you can connect using a cluster or a SQL warehouse. Some users prefer SQL warehouse because it can be more affordable. If your Databricks connection uses S3, however, you will get an error when you try to rename tables. We fix this issue for cluster connections by setting this config: `spark.databricks.delta.alterTable.rename.enabledOnAWS=true`. That config is not supported for SQL warehouse connections, so users are unable to rename tables when using a SQL warehouse connection with S3.
To work around this this for users who want to use S3 with a SQL warehouse, we will require them to specify a cluster connection to use exclusively for table renames. We can specify which connection to use by changing the HTTP path used when connecting to Databricks.
=> Databricks: Enable secondary connection for table renames

metricflow/test/integration/test_cases/itest_metrics.yaml
Some of our engines require subquery aliases, but these were missing
in the "expected" SQL queries.
=> Fix derived metric integration tests

metricflow/model/model_validator.py, metricflow/model/validations/metrics.py, metricflow/test/model/validations/test_metrics.py
With the addition of derived metrics, we need to validate that they are correctly configured.
1. Derived metrics allows you to attach an alias to an input metric. The alias must be unique from the other aliases and other input metric names.
2. Validates that the input metric provided exists in the model
=> added validator for derived metrics

metricflow/model/model_validator.py, metricflow/model/parsing/dir_to_model.py, metricflow/model/validations/data_sources.py, metricflow/test/model/validations/helpers.py, metricflow/test/model/validations/test_validity_param_definitions.py
The validity params for defining an SCD window on a data source must
conform to certain specifications, otherwise we will not be able to
properly handle them and users could encounter strange runtime
failures.
This PR adds the relevant validation checks and assertions, along
with a test suite for the new validation. It also reshuffles some of our
parsing/validation functions to enable isolated testing on specific
custom model elements.
=> Add validation to ensure validity param specifications are correct

metricflow/model/validations/data_sources.py, metricflow/test/model/validations/test_validity_param_definitions.py
Defining measures in an SCD-style data source is a bit tricky,
because it's unclear when (or if) the user wants the measure to be
globally aggregable vs semi-additive to the validity windows.
While we sort out the right model syntax for this, we will prevent
measure definitions in data sources with validity windows to ensure
there is no mismatch between framework behavior and user expectations
with regard to how these things are aggregated.
This PR also includes some related error message cleanup.
=> Prevent measure definitions in data sources with validity windows

.github/workflows/cd-push-to-pypi.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-linting.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, .github/workflows/ci-schema-consistency.yaml
Our actions were pinned to Poetry 1.1.15 due to an outstanding issue 
with virtual env creation configuration. For historical reasons, we were
also testing exclusively in Python 3.8.
This PR moves us to a model where we're using the latest Poetry version
for build management, and running all actions against Python 3.9 (our latest
supported Python version) EXCEPT our core unit tests, which are run against
all supported Python versions.
This shift to matrixed Python versions presents a separate issue, resolved here
as well, where our merge-blocking unit test job is effectively forked into N
separate jobs, one for each version. Since branch protection is bound to job
name, and the job names are generated in the matrix configuration, we'd need
to keep updating the branch protection against …
=> Actions cleanup: use more recent Poetry and Python versions

.pre-commit-config.yaml, metricflow/model/transformations/dbt_to_metricflow.py
Metricflow has an override in its .pre-commit-config to ignore all
missing imports, which means third party packages simply don't get
typechecked in any case where the mypy invocation is mediated by
pre-commit (which is roughly all of them, for us).
This means the dbt integration was done with a relative minimum of
typechecker support.
Here we enable dbt typchecking in the .pre-commit-config (the remaining
changes were an unfortunate side effect of auto-formatting) by adding
dbt-core to the dependency list, and clean up the typing errors this
exposed as a result.
Note these fixes are just wallpapering over the underlying issues, so
more robust changes may be warranted.
=> Enable pre-commit typechecking for dbt packages

metricflow/protocols/async_sql_client.py, metricflow/protocols/sql_client.py, metricflow/protocols/sql_request.py, metricflow/sql_clients/async_request.py, metricflow/sql_clients/base_sql_client_implementation.py, metricflow/sql_clients/big_query.py, metricflow/sql_clients/databricks.py, metricflow/sql_clients/duckdb.py, metricflow/sql_clients/postgres.py, metricflow/sql_clients/redshift.py, metricflow/sql_clients/snowflake.py, metricflow/sql_clients/sql_utils.py, metricflow/sql_clients/sqlalchemy_dialect.py, metricflow/test/conftest.py, metricflow/test/fixtures/sql_client_fixtures.py, metricflow/test/sql_clients/test_async.py
This PR adds an async interface to the query execution methods in `SqlClient` along with the associated query cancellation methods. The cancellation of queries is handled by returning a request ID in the async method, which is later used to call the cancel method. The queries are tagged using serialized metadata that is added as a comment to the query text, which allows for easy inspection of running queries in the DW engine. It also enables cancelling queries from separate `SqlEngine` objects.
=> Add Async Query / Cancel Methods to SqlClient

metricflow/protocols/async_sql_client.py, metricflow/protocols/sql_client.py, metricflow/sql_clients/async_request.py, metricflow/sql_clients/base_sql_client_implementation.py, metricflow/sql_clients/big_query.py, metricflow/sql_clients/common_client.py, metricflow/sql_clients/databricks.py, metricflow/sql_clients/duckdb.py, metricflow/sql_clients/postgres.py, metricflow/sql_clients/redshift.py, metricflow/sql_clients/snowflake.py, metricflow/sql_clients/sqlalchemy_dialect.py, metricflow/test/sql_clients/test_async.py
This PR adds an isolation level option to the SQL client to handle concurrency applications.
=> Add Isolation Level Support to SqlClient

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/dataflow_plan.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/test/integration/test_cases/itest_metrics.yaml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_derived_metric__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_nested_derived_metric__plan0.xml
With the merge of Derived Metrics, we supported the ability to reference metrics and build an expr out of it. The way we aggregate all the metrics data is through the `CombineMetricsNode` which utilizes a `FULL OUTER JOIN` to combine the metric data. This would mean that there are cases where some metrics would return rows of `NaN` or `null` values because it doesn't have data associated to the metric time that other metrics have. This would result in the final result having `NaN` or `null` value. 
With further discussions on https://github.com/transform-data/metricflow/pull/281#discussion_r998590378, we decided to use an `INNER JOIN` when combining metrics for derived metrics so that we don't have null values in the results.
=> Use INNER JOIN for derived metrics when combining metrics

metricflow/sql_clients/databricks.py
Currently, if the user has not set up a secondary connection and tries to execute a table rename, this fails. This PR fixes that!
=> Databricks: only use secondary connection if it exists

metricflow/test/compare_df.py, metricflow/test/fixtures/model_yamls/simple_model/metrics.yaml, metricflow/test/integration/test_cases/itest_metrics.yaml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_nested_derived_metric__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_nested_derived_metric__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_derived_metric__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_nested_derived_metric__plan0.xml
The derived metrics tests were all implicitly checking BIGINT types,
since that's what SUM returns. This changes them to use DOUBLE
for proper ratio computation, which will bring the answers in line
with expectation based on manual calculation against the table fixtures.
Note we cannot do explicit casting in the metric definition expr because
DOUBLE types are not consistently named across engines, so we rely on
the implicit casting shorthand of multiplying by a double literal.
=> Make derived metrics tests use double types

.github/workflows/ci-schema-consistency.yaml, metricflow/model/parsing/schemas/metricflow.json, metricflow/model/parsing/schemas_internal.py, metricflow/test/fixtures/model_yamls/simple_model/metrics.yaml
Following the example PR https://github.com/transform-data/metricflow/pull/261, we are adding a new field called `private` in metric `locked_metadata` field in our internal schema. This field will be used to allow more granular access control for a metric.
Note that this change is taking place in MetricFlow because that is where schema's internal lives. However, it doesn't actually add or change any features of metricflow for the community.
=> Add private field support in metric locked_metadata

metricflow/model/data_warehouse_model_validator.py
We're having some spec building issues when building specs for the measure based data warehouse validations. It's extra hard to debug because currently we don't return the exception stacktrace information. Without this it's hard to see what is going on. This commit adds the exception stacktrace information to the `extra_details` section of the validation error. Note, from a CLI perspective `extra_details` aren't printed out by default. They are only printed when `--verbose-issues` is specified
=> Add `extra_detail` to data warehouse validation errors raised from exceptions

metricflow/model/data_warehouse_model_validator.py
In the SourceNodeBuilder, we split the measures into smaller source nodes by the `agg_time_dimension`  property. In the DW validator, we get all the source nodes for the data source and just use the first one via `source_nodes[0]`. This means if we have a data source with 2 measures with a different `agg_time_dimension`, we would correctly validate 1 measure while the other measure would throw an error that looks like (`MeasureSpec(measure1) not in specset ...`). Again, this is due to simply using 1 source node for validating all the measures when we should really be selecting the correct source node that contains the measure we are trying to query.
- Select the correct source node to pass to the `FilterElementNode` when validating a measure
=> FIX: DW measure validation was using wrong source node

metricflow/model/objects/data_source.py
This PR removes the `update_cron` default as it is not used in the open source project so it will be confusing.
=> Remove `update_cron` Default From Mutability

metricflow/sql_clients/duckdb.py, metricflow/test/sql_clients/test_sql_client.py
* Using a Lock instead of RLock as DuckDB can throw odd errors with concurrent queries, even in the same thread.
* Protecting `list_tables` with a lock as it also accesses the engine.
=> Fix DuckDB Concurrency Issues

metricflow/dataset/convert_data_source.py, metricflow/model/validations/data_sources.py, metricflow/test/model/validations/test_agg_time_dimension.py
We added the concept of measure `agg_time_dimension` in #158. Which means that it's no longer required for a data source with measures to have a primary time dimension, so long as every measure has an `agg_time_dimension` set. This PR catches validations up to that reality.
=> If a data source's measures all have an `agg_time_dimension`, a primary time dimension is not requried

.github/workflows/cd-push-to-pypi.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-linting.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, .github/workflows/ci-schema-consistency.yaml
All CI jobs using actions/cache@v2 and actions/checkout@v2 are throwing
warnings about save-state, node.js build version, or both. 
This is due to cache@v2 and checkout@v2 depending on an older version
of the actions core package. The latest releases of their v3 packages resolve
this issue, so we are updating these dependencies accordingly.
=> Update github action dependencies to use latest actions/core

metricflow/model/parsing/schemas/metricflow.json, metricflow/model/parsing/schemas_internal.py, metricflow/test/fixtures/model_yamls/simple_model/metrics.yaml
Following the example PR https://github.com/transform-data/metricflow/pull/261 and https://github.com/transform-data/metricflow/pull/320, we are adding a new field called unit in metric locked_metadata field in our internal schema. This field will be used to display and store the unit associated with a metric.
Note that this change is taking place in MetricFlow because that is where schema's internal lives. However, it doesn't actually add or change any features of metricflow for the community.
=> add unit field support in metric locked_metadata 

metricflow/api/metricflow_client.py, metricflow/cli/cli_context.py, metricflow/engine/metricflow_engine.py, metricflow/execution/execution_plan.py, metricflow/model/data_warehouse_model_validator.py, metricflow/plan_conversion/dataflow_to_execution.py, metricflow/sql_clients/sql_utils.py, metricflow/test/api/conftest.py, metricflow/test/execution/test_tasks.py, metricflow/test/fixtures/cli_fixtures.py, metricflow/test/integration/conftest.py, metricflow/test/integration/test_configured_cases.py, metricflow/test/model/validations/test_data_warehouse_tasks.py, metricflow/test/plan_conversion/test_dataflow_to_execution.py
This PR exposes AsyncSqlClient in the engine API and the execution plan so that MF can add custom tags to SQL queries that are sent to the DW.
=> Use AsyncSqlClient in API / Execution Plan

metricflow/api/metricflow_client.py, metricflow/cli/cli_context.py, metricflow/engine/metricflow_engine.py, metricflow/execution/execution_plan.py, metricflow/model/data_warehouse_model_validator.py, metricflow/plan_conversion/dataflow_to_execution.py, metricflow/sql_clients/base_sql_client_implementation.py, metricflow/sql_clients/big_query.py, metricflow/sql_clients/databricks.py, metricflow/sql_clients/duckdb.py, metricflow/sql_clients/snowflake.py, metricflow/sql_clients/sql_utils.py, metricflow/sql_clients/sqlalchemy_dialect.py, metricflow/test/api/conftest.py, metricflow/test/execution/test_tasks.py, metricflow/test/fixtures/cli_fixtures.py, metricflow/test/integration/conftest.py, metricflow/test/integration/test_configured_cases.py, metricflow/test/model/validations/test_data_warehouse_tasks.py, metricflow/test/plan_conversion/test_dataflow_to_execution.py, metricflow/test/sql_clients/test_async.py
This PR updates the Snowflake SQL client so that the request tags that are passed in get converted to a JSON string and used as the `QUERY_TAG` session parameter when executing a SQL query.
=> Add Tag Support for Snowflake Queries

metricflow/cli/main.py, metricflow/configuration/config_handler.py
I encountered the issue when importing metricflow in multi threading / multi processing env.
```
../metricflow/metricflow/__init__.py:1: in <module>
from metricflow.api.metricflow_client import MetricFlowClient  # noqa: D
../metricflow/metricflow/api/metricflow_client.py:10: in <module>
from metricflow.engine.metricflow_engine import (
../metricflow/metricflow/engine/metricflow_engine.py:47: in <module>
_telemetry_reporter = TelemetryReporter(report_levels_higher_or_equal_to=TelemetryLevel.USAGE)
../metricflow/metricflow/telemetry/reporter.py:39: in __init__
self._email = os.getenv(TelemetryReporter.ENV_EMAIL_OVERRIDE) or ConfigHandler().get_value(CONFIG_EMAIL)
../metricflow/metricflow/configuration/config_handler.py:15: in __init__
dir_path.mkdir(parents=True) …
```
=> Make creating folders thread/process safe

metricflow/dataflow/builder/node_evaluator.py, metricflow/engine/metricflow_engine.py, metricflow/instances.py, metricflow/model/semantic_model.py, metricflow/model/semantics/data_source_semantics.py, metricflow/model/semantics/linkable_element_properties.py, metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/metric_semantics.py, metricflow/model/semantics/valid_join.py, metricflow/plan_conversion/node_processor.py, metricflow/protocols/semantics.py, metricflow/test/model/semantics/test_linkable_spec_resolver.py, metricflow/test/model/test_data_source_container.py
This PR adds a class to centralize the logic that is used to figure out whether a join between data sources using a specific identifier. To resolve circular dependencies, some of the semantics classes were factored out.
=> Centralize Join Validity Logic

metricflow/model/parsing/schemas.py, metricflow/model/parsing/schemas/metricflow.json, metricflow/test/model/parsing/test_metric_parsing.py
The schema for metric inputs to derived metrics allows for a list
of either string or metric input struct, but the Pydantic object
only accepts this latter. This removes the option from the
schema for the sake of consistency, and also to ensure any editor
plugins based on the jsonschema provide the correct completion
hints.
=> Fix schema for metric inputs to derived metrics

metricflow/sql_clients/databricks.py
We're working to add more logging for Databricks in Transform. Here I did a minor refactor to move execution logic into a helper function that we can easily override in Transform (to add a Datadog trace) without having to duplicate any additional logic.
=> Databricks: Move execute logic into helper function

metricflow/execution/execution_plan.py, metricflow/plan_conversion/dataflow_to_execution.py, metricflow/protocols/async_sql_client.py, metricflow/protocols/sql_request.py, metricflow/sql_clients/base_sql_client_implementation.py, metricflow/sql_clients/databricks.py, metricflow/sql_clients/duckdb.py, metricflow/sql_clients/snowflake.py, metricflow/sql_clients/sql_utils.py, metricflow/sql_clients/sqlalchemy_dialect.py, metricflow/test/sql_clients/test_async.py
This PR updates the tag format used for SQL requests to be of the JSON format so that they are easier to consume.
=> Allow Tags for SQL Requests  in JSON Format

metricflow/protocols/async_sql_client.py, metricflow/protocols/sql_request.py, metricflow/sql_clients/async_request.py, metricflow/sql_clients/base_sql_client_implementation.py, metricflow/sql_clients/big_query.py, metricflow/sql_clients/databricks.py, metricflow/sql_clients/duckdb.py, metricflow/sql_clients/postgres.py, metricflow/sql_clients/redshift.py, metricflow/sql_clients/snowflake.py, metricflow/sql_clients/sqlalchemy_dialect.py, metricflow/test/sql_clients/test_async.py
This PR updates `AsyncSqlClient.cancel_request` so that a filtering / matching function can be used to select which queries to cancel.
=> Update cancel_request to filter by function

.github/workflows/cd-push-to-pypi.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-linting.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, .github/workflows/ci-schema-consistency.yaml
The recent update to ubunutu 22.04 seems to have broken a bunch of
stuff with python installs. In all likelihood the fix is going to
involve hacky environment variable overrides or continuous
reinstallation of python-distutils.
Rather than deal with testing all of those things at this time, we
simply pin the ubuntu version back to 20.04 in CI and hope for the
best.
=> Pin CI actions to ubuntu 20.04

.github/workflows/cd-push-to-pypi.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-linting.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, .github/workflows/ci-schema-consistency.yaml
This undoes the failed attempt to revert our CI ubuntu runtime to the
previous version, and provides what is hopefully a more robust fix
for the problem.
The CI runner was failing to find matching versioned dependencies in
the hosted tools cache. This was likely caused by one of two things:
1. An update to Ubuntu that updated some system packages
2. A mis-configured cache key (pointing at the wrong poetry.lock file location)
The former is fixed by appending the ubuntu version to the cache key
in our actions/cache configurations.
The latter is fixed by providing the hashFiles call in our actions/cache
configuration with the correct file path for the config file we wish to
hash.
This PR moves us back onto ubuntu-latest, and makes both updates
to our actions cache keys, which will hopefully …
=> Update CI actions cache keys so they are properly versioned

metricflow/query/query_parser.py, metricflow/test/fixtures/model_yamls/simple_model/metrics.yaml, metricflow/test/query/test_query_parser.py
Currently, we don't validate derived metrics correctly. So realistically, one could query for something incorrectly when using derived metric and pass the query parser as there are no query validations against the input metrics.
we could have a derived metric of a cumulative metric
```yaml
metric:
name: cumulative_metric
description: some cumulative metric
type: cumulative
type_params:
measures:
- some_measure
window: 7 days
---
metric:
name: derived_metric
description: cumulative_metric - 10
type: derived
type_params:
expr: cumulative_metric - 10
metrics:
- name: cumulative_metric
```
Now if we query, we would get thrown an error 
```
mf query --metrics cumulative_metric
Unable To Satisfy Query Error: Metric cumulative is a cumulative metric specified with a window/grain_to_date which …
```
=> Validate each derived metric inputs individually

metricflow/dataclass_serialization.py, metricflow/specs.py, metricflow/sql/render/expr_renderer.py, metricflow/sql/render/sql_plan_renderer.py, metricflow/sql/sql_bind_parameters.py, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_plan__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_with_reused_measure_plan__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan_time_dimension__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_with_common_linkable_plan__dfp_0.xml, metricflow/test/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfp_0.xml, metricflow/test/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfpo_0.xml, metricflow/test/sql/test_bind_parameter_serialization.py, metricflow/test/sql_clients/test_sql_client.py
This PR changes `SqlBindParameters` to be immutable and serializable. This is needed as `MetricFlowQuerySpec` (supposed to be immutable / serializable) can include `SqlBindParameters` via a `WhereClauseConstraint`.
=> Change SqlBindParameters To Be Immutable / Serializable

metricflow/cli/main.py, metricflow/cli/utils.py
NOTE: this changes depending on the warehouse selected and this also is displayed in `mf tutorial` as well
New option
```
--show-dataflow-plan (Default: False)  Display dataflow plan in explain output
```
Usage
```
mf query --metrics ... --explain --show-dataflow-plan
```
If that flag is not pass, we would only show the generated SQL
=> Polish CLI

metricflow/sql/optimizer/rewriting_sub_query_reducer.py, metricflow/sql/sql_exprs.py, metricflow/test/snapshots/test_rewriting_sub_query_reducer.py/SqlQueryPlan/test_reducing_join_left_node_statement__after_reducing.sql, metricflow/test/snapshots/test_rewriting_sub_query_reducer.py/SqlQueryPlan/test_reducing_join_left_node_statement__before_reducing.sql, metricflow/test/snapshots/test_rewriting_sub_query_reducer.py/SqlQueryPlan/test_reducing_join_statement__after_reducing.sql, metricflow/test/snapshots/test_rewriting_sub_query_reducer.py/SqlQueryPlan/test_reducing_join_statement__before_reducing.sql, metricflow/test/sql/optimizer/test_rewriting_sub_query_reducer.py
There are certain cases where the sub query reducer collapses cross joins, it potentially leads to a final select node containing a mix of aggregate functions and other exprs (ie., column references). This ends up throwing an invalid GROUP BY error.
```sql
-- query
SELECT
src2.bookings AS bookings
, src3.listings AS listings
FROM (
-- src2
SELECT
SUM(src1.bookings) AS bookings
FROM (
-- src1
SELECT
1 AS bookings
FROM demo.fct_bookings src0
) src1
) src2
CROSS JOIN (
-- src4
SELECT
SUM(src4.listings) AS listings
FROM demo.fct_listings src4
) src3
```
```sql
-- query
SELECT
src2.bookings AS bookings
, SUM(src4.listings) AS listings
FROM (
-- src2
SELECT
SUM(1) AS bookings
FROM demo.fct_bookings src1
) src2
CROSS JOIN
demo.fct_listings src4
```
This would throw an error similar to this
``` …
```
=> BUG: Aggregate functions gets mixed with other exprs when optimized

.github/workflows/cd-sql-engine-tests.yaml, metricflow/test/conftest.py, metricflow/test/model/dbt_cloud_parsing/conftest.py
After my merge of #324, the `MetricFlow Sql Engine Tests` began failing. This is because I missed the fact that `MetricFlow SQL Engine Tests` run the entire MetricFlow test suite. This raised two issues
1. `MetricFlow Sql Engine Tests` shouldn't run the dbt cloud support tests
2. dbt cloud support tests need to be easy to isolate
This PR isolates the dbt cloud support tests (and related materials like fixtures) into one dir making them easy to skip: `poetry run pytest metricflow/test --ignore=metricflow/test/model/dbt_cloud_parsing`. Additionally this PR begins skipping the dbt cloud support tests in the `MetricFlow Sql Engine Tests`.
=> Fix `MetricFlow SQL Engine Tests` that got broken due to #324

metricflow/plan_conversion/dataflow_to_sql.py, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_semi_additive_join_node_with_queried_group_by__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_semi_additive_join_node_with_queried_group_by__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDbSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_semi_additive_join_node_with_queried_group_by__plan0_optimized.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_semi_additive_join_node_with_queried_group_by__plan0.xml
Under certain conditions the semi-additive join node rendering
produces slightly strange SQL, where columns in the `GROUP BY`
statement are not included in the `SELECT`. For example, the inner
query for the filter join might look like this:
```
SELECT MIN(ds) AS ds__complete
FROM input_table
GROUP BY DATE_TRUNC(ds, isoweek)
```
This is confusing, as the DATE_TRUNC expression in the group by
allows for multiple rows of output. In this case, since the `ds`
columns are dates, there will always be exactly 1 row per `isoweek`,
however it's not obvious that this is the intent of the query.
This also causes problems with certain rendering approaches, as
we typically render either a raw expression OR an alias in `GROUP BY`
statements. In cases where we render the latter, this query will
break …
=> Add all group by columns to select in semi-additive join node

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/dataflow_plan.py, metricflow/model/objects/metric.py, metricflow/model/validations/metrics.py, metricflow/test/model/parsing/test_metric_parsing.py
This class will soon be used to specify offset windows for derived metrics. Renaming to something that makes sense for both use cases!
=> Rename `CumulativeMetricWindow` to `MetricTimeWindow`

CONTRIBUTING.md, Makefile
Our integration with dbt-cloud adds optional dependencies
which are currently required to run the complete test suite.
This doesn't resolve the broader issue raised in #387, but it
does bring our developer documentation up to date with the current
state of our main branch.
=> Update makefile and developer docs for dbt-cloud

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/query/query_parser.py, metricflow/test/dataflow/optimizer/source_scan/test_source_scan_optimizer.py, metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py, metricflow/test/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfp_0.xml, metricflow/test/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfpo_0.xml
https://github.com/transform-data/metricflow/pull/352#discussion_r1049226384
Essentially in the DataflowPlanBuilder, given a MetricSpec
1. we get the Metric object corresponding to that MetricSpec and combine the where constraint defined in the Metric
2. combine on the where constraint defined in the MetricSpec as well
Currently, it doesn't seem like there's a use case of doing both of these other than to cause slight confusion. At runtime when building the query, we just pass a list of MetricSpec to the builder that was initialized by the metric names only. So to remove the redundancy here, in the query parser we should attach the constraint to the MetricSpec that gets passed to the builder so that we don't have to retrieve the metric constraint from the Metric object directly …
=> Consolidate metric constraints in DataflowPlanBuilder

.github/workflows/cd-sql-engine-tests.yaml
The existing SQL engine tests only exercised our Databricks
engine implementations as SQL queries against a Databricks
cluster configuration. However, it's more common for analytics
query workloads to target a Databricks SQL warehouse configuration.
Since we support both, we should test both.
=> Add Databricks SQL Warehouse runtime to sql engine tests

metricflow/test/integration/test_cases/itest_metrics.yaml
Needed to update these tests to use the `mf_time_spine_source` Jinja variable in order for tests to have access to the time spine table in Transform.
=> Use `mf_time_spine_source` Jinja variable in test cases

metricflow/test/fixtures/model_yamls/extended_date_model/metrics/bookings_cumulative.yaml, metricflow/test/time/test_time_granularity_solver.py, metricflow/time/time_granularity_solver.py
Previously, a bug was allowing some queries to succeed for multiple metrics with no overlapping granularities. This fixes that.
Example:
`bookings_cumulative` only supports `day` granularity
`bookings_monthly` only supports `month` granularity or larger
Querying for `bookings_cumulative` and `bookings_monthly` together with a granularity of `month` would succeed, though we would expect it to fail since querying `bookings_cumulative` alone with `month` granularity would fail.
=> Bug fix: error for restricted granularity

.github/workflows/ci-validation-duration.yaml
Chatted with Marco offline and he suggested a workflow be added for test runs to avoid local caching/pytest artifacts interfering with getting a stable read on what the proper baseline is for tests (after I was playing around with a local branch that changed our SQL parser and then completely changed the test duration baseline).
=> Add workflow to measure validation test duration on PRs and main

metricflow/engine/metricflow_engine.py, metricflow/logging/formatting.py, metricflow/query/query_parser.py, metricflow/sql_clients/base_sql_client_implementation.py
This PR cleans up how logging indents are generated and also formats the bind parameters so they are more legible when there are many parameters.
=> Clean Up Logging indents and Bind Parameter Logging

metricflow/model/transformations/dbt_to_metricflow.py
The package `pre-commit` recently went from `2.2.1` to `3.0.0`. Running `mypy` on branch `main` with `pre-commit 2.2.1` succeeds, but if using `pre-commit 3.0.0` it fails with the following error
```
metricflow/model/transformations/dbt_to_metricflow.py:112: error: Argument "target_model_name" to "resolve_ref" of "Manifest" has incompatible type "Optional[Any]"; expected "str"  [arg-type]
```
This is a small update to make it clear to `mypy` the typing of `target_model` in `dbt_to_metricflow`
=> Fix `dbt_to_metricflow` new linting errors that come from `pre-commit 3.0.0`

metricflow/model/model_transformer.py, metricflow/model/parsing/dbt_cloud_to_model.py, metricflow/model/parsing/dbt_dir_to_model.py, metricflow/model/parsing/dir_to_model.py, metricflow/test/fixtures/model_fixtures.py, metricflow/test/model/transformations/test_configurable_transform_rules.py, metricflow/test/model/validations/test_common_identifiers.py, metricflow/test/model/validations/test_configurable_rules.py, metricflow/test/model/validations/test_data_warehouse_tasks.py, metricflow/test/model/validations/test_element_const.py, metricflow/test/model/validations/test_identifiers.py, metricflow/test/model/validations/test_materializations.py, metricflow/test/model/validations/test_measures.py, metricflow/test/model/validations/test_reserved_keywords.py, metricflow/test/model/validations/test_unique_valid_name.py
There are no longer any `pre` validation transformations or `post` validation transformations. There are however transformation rules which require other transformation rules to be run first. Additionally, we can imagine
there being more ordered levels or transformation rules than just two. This PR adds a new `transform` method to the `ModelTransformer` which takes ina tuple of rule sequences. These rule sequences are operated over in order, i.e.
the first sequence is run before the second sequence, and etc. This makes transformations more flexible going forward, resolves the naming with the actual state of things, and simlifies the majority of use cases involving `ModelTransformer`. Additionally, we have deprecated the `pre` and `post`functions, which will eventually be removed.
* Adds …
=> Improve Terminology and Implementation of `TransformModel`

.github/workflows/ci-linting.yaml, .pre-commit-config.yaml
Pre-commit recently released a 3.0, but our project configuration is
restricted to version 2.x (specifically, 2.18 or higher, but less than
3.0).
SQLAlchemy just released version 2.0, but our project configuration is
restricted to version 1.4.x.
Both of these are causing failures in CI, as our configurations allow for
latest version installations of pre-commit itself, and latest version of
SQLAlchemy within the pre-commit runtime environment.
Making MetricFlow compatible with these version updates is more involved
than a simple version change, so we limit the version ranges for the time being.
=> Fix pre-commit version discrepancies

metricflow/test/integration/test_cases/itest_composite_identifier.yaml, metricflow/test/integration/test_cases/itest_order_limit.yaml
Recent changes added some values to our dummy test data which
produced multiple correct sort orders for output rows in the
itest_order_limit test cases. Although this has not yet come up in
our CI we have seen intermittent output order failures on these tests
in other runtime contexts, so adding explicit ordering
directives are necessary to ensure test robustness.
This commit makes a similar update to the composite_key_order integration
test to prevent a future recurrence of this issue.
This does not affect other tests as they rely on
comparisons of unordered output.
=> Ensure consistent sort order for order-dependent integration test cases

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/model/semantic_model.py, metricflow/model/semantics/data_source_container.py, metricflow/model/semantics/data_source_semantics.py, metricflow/model/semantics/metric_semantics.py, metricflow/plan_conversion/instance_converters.py, metricflow/protocols/semantics.py, metricflow/test/model/semantics/test_data_source_join_evaluator.py, metricflow/test/model/test_data_source_container.py
This PR cleans up `DataSourceSemantics` and `MetricSemantics` to
* Remove functionality that is no longer used. 
* Move from using strings to look up data sources to using `DataSourceReference`.
* Change signatures to use `Sequence` instead of `List` or `Tuple` to follow principle of using the most general interfaces in the signatures. `Iterable` or something else may be more apt, however.
Cleanup of some of the internal data structures will be handled in another PR.
=> Clean up DataSourceSemantics and MetricSemantics.

.changes/unreleased/Fixes-20230426-104954.yaml, metricflow/protocols/sql_client.py, metricflow/sql_clients/common_client.py, metricflow/test/sql_clients/test_async.py, metricflow/test/sql_clients/test_sql_client.py
This was an artifact of Transform and is no longer needed.
=> Remove MYSQL from `SqlEngine` & `SqlDialect` enums

.changes/unreleased/Under the Hood-20230424-122900.yaml, metricflow/api/metricflow_client.py, metricflow/cli/main.py, metricflow/model/model_validator.py, metricflow/test/cli/test_cli.py, metricflow/test/model/validations/test_common_identifiers.py, metricflow/test/model/validations/test_configurable_rules.py, metricflow/test/model/validations/test_identifiers.py, metricflow/test/model/validations/test_measures.py, metricflow/test/model/validations/test_metrics.py, metricflow/test/model/validations/test_validity_param_definitions.py
Model validation rules do not alter the model. By extension the ModelValidator does not alter the model. The fact that the ModelValidator was returning the model was a carry over from a now long bygone era when model validators and model transformations were much more tightly coupled.  We've, for the better, gotten away from that. This now vestigial return value's existence can muddle the mental model of how the ModelValidator works for people learning about it. Thus this change cleans this no longer needed functionality. Indeed it's desirable to stop returning the model from the ModelValidator because we want to cement the idea that the ModelValidator does not and should not modify the model.
=> Stop returning the model from ModelValidator

.changes/unreleased/Under the Hood-20230424-122559.yaml, dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/dir_to_model.py, metricflow/model/validations/agg_time_dimension.py, metricflow/model/validations/common_identifiers.py, metricflow/model/validations/data_sources.py, metricflow/model/validations/dimension_const.py, metricflow/model/validations/element_const.py, metricflow/model/validations/identifiers.py, metricflow/model/validations/measures.py, metricflow/model/validations/metrics.py, metricflow/model/validations/non_empty.py, metricflow/model/validations/reserved_keywords.py, metricflow/model/validations/unique_valid_name.py, metricflow/model/validations/validator_helpers.py, metricflow/test/model/validations/test_validator_helpers.py
Our different validation issue classes (`ValidationWarning`, `ValidationFutureError`, `ValidationError`) used to be entirely separate classes (i.e. didn't inherit from a parent class). However, they now all inherit from `ValidationIssue`. Before this we needed the `ValidationIssueType` type for saying something could contain any of those separate classed. However, since we now have `ValidationIssue` as the parent class, we should be able to replace `ValidationIssueType` with it. This will make typing easier.
=> Replace uses of `ValidationIssueType` with `ValidationIssue`

.changes/unreleased/Under the Hood-20230425-112809.yaml, dbt_semantic_interfaces/dbt_semantic_interfaces/errors.py, dbt_semantic_interfaces/dbt_semantic_interfaces/objects/base.py, dbt_semantic_interfaces/dbt_semantic_interfaces/objects/common.py, dbt_semantic_interfaces/dbt_semantic_interfaces/objects/constraints/where.py, dbt_semantic_interfaces/dbt_semantic_interfaces/objects/metric.py, dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/dir_to_model.py, dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/add_input_metric_measures.py, dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/convert_count.py, dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/convert_median.py, dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/proxy_measure.py, metricflow/errors/errors.py, metricflow/model/validations/metrics.py
The parsing/transformation/validation related MetricFlow errors are only related to those processes. Those processes are moving to dbt_semantic_interfaces. Thus, it behooves us to move these to dbt_semantic_interfaces as well.
=> Cutover errors specific to parsing/transformation/validation to dbt_semantic_interfaces

.changes/unreleased/Fixes-20230428-123628.yaml, dbt_semantic_interfaces/dbt_semantic_interfaces/objects/metric.py, metricflow/model/semantics/metric_semantics.py, metricflow/test/fixtures/model_yamls/simple_model/metrics.yaml, metricflow/test/integration/test_cases/itest_metrics.yaml
In derived metric, there are multiple layers of constraints.
1. The constraint in the metric used as an input metric
2. The input_metric constraint defined in the derived metric definition
`(1)` is not being respected so if one were to define a derived metric as so,
```yaml
metric:
name: "instant_bookings"
description: "bookings metric"
type: measure_proxy
type_params:
measures:
- bookings
constraint: is_instant
---
metric:
name: "double_instant_bookings"
description: "2x bookings metric"
type: derived
type_params:
expr: instant_bookings * 2
metrics:
- name: instant_bookings
```
The `constraint: is_instant` clause would be missing in the metric `double_instant_bookings`. This PR fixes this bug.
=> BUG: Input Metric's original constraint is not being propogated

dbt_semantic_interfaces/dbt_semantic_interfaces/objects/common.py, dbt_semantic_interfaces/dbt_semantic_interfaces/objects/metric.py
This PR removes functions and classes that make references to `definition_hash`, which is not used in the open source project. This was originally a part of https://github.com/dbt-labs/metricflow/pull/444, but got left out by accident.
<!--- 
=> Remove References to Definition Haash

metricflow/model/validations/reserved_keywords.py
Validations are going to be moved over to dbt_semantic_interfaces. As such they can't be importing metricflow. The change here is small. We're unfortunately duplicating code that is in `SqlTable`, but this will likely be changing again in the near future as dbt_semantic_interfaces plans on using a more structured object directly on the data source in place of sql_table.
<!--- 
=> Remove use of `SqlTable` in `reserved_keywords.py` validation rule

.changes/unreleased/Under the Hood-20230503-174526.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, metricflow/test/fixtures/setup_fixtures.py, metricflow/test/fixtures/sql_client_fixtures.py, metricflow/test/sql_clients/test_sql_client.py
This PR implements the issue https://github.com/dbt-labs/metricflow/issues/482 and allows the user to run `pytest --use-persistent-source-schema ...`.
=> Reduce time to run tests by using a persistent source schema

dbt_semantic_interfaces/dbt_semantic_interfaces/dataclass_serialization.py, dbt_semantic_interfaces/dbt_semantic_interfaces/references.py, metricflow/column_assoc.py, metricflow/constraints/time_constraint.py, metricflow/instances.py, metricflow/specs.py, metricflow/sql/sql_bind_parameters.py, metricflow/test/sql/test_bind_parameter_serialization.py, metricflow/test/test_dataclass_serialization.py, metricflow/test/test_instance_serialization.py
We're not sure if this serialization is actually still necessary, it
may be vestigial. However, until we figure that out, dbt-semantic-interfaces
will need to know about SerializableDataclass. This is because one of the
main things that can be serialized are instances sets. Although instance
sets aren't in dbt-semantic-interfaces, references are, and instance have
a lot of references. Thus the references must be built with
SerializableDataclass, and thus it must be in dbt-semantic-interfaces.
If SerializableDataclass does turn out to be vestigial, then we'll remove
it from things at that point.
=> Move dataclass_serialization.py to dbt_semantic_interfaces

.github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-metricflow-unit-tests.yaml
There is a known race condition when creating the persistent source schema for the first time that was thought to be rare to hit. But with the current Databricks setup in CI, it is actually likely, so removing this speedup for now.
<!--- 
=> Disable using --use-persistent-schema in CI tests

dbt_semantic_interfaces/dbt_semantic_interfaces/objects/aggregation_type.py
When we moved `AggregationType` over, we changed it from an `ExtendedEnum` to an `Enum`. We thought this wouldn't be problematic. However, it turns out that the `_missing_` function of `ExtendedEnum` is actually very important. This is because the custom `_missing_` implementation ensures that using upper-cased or lower-cased values in a config file both work. That is to say that with `ExtendedEnum`, `sum` and `SUM` are both valid, but with `Enum` only `sum` is.
<!--- 
3. run `changie new` to [create a changelog …
=> Making AggregationType use ExtendedEnum again

dbt_semantic_interfaces/dbt_semantic_interfaces/objects/semantic_model.py
Set the `relation_name` pydantic validator to private as it shouldn't be accessed outside of pydantic and added additional errors to avoid `None` string formatting.
<!--- 
=> Update pydantic validator for SemanticModel.relation_name

metricflow/plan_conversion/dataflow_to_execution.py, metricflow/query/query_parser.py, metricflow/specs.py, metricflow/test/query/test_query_parser.py
This PR removes the output column override feature that renamed the output columns in specific cases. This feature is no longer needed as it was for migration.
<!--- 
=> Remove Output Column Overrides

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/node_evaluator.py, metricflow/dataflow/builder/partitions.py, metricflow/dataflow/builder/source_node.py, metricflow/engine/metricflow_engine.py, metricflow/model/data_warehouse_model_validator.py, metricflow/model/semantic_manifest_lookup.py, metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/metric_lookup.py, metricflow/model/semantics/metric_semantics.py, metricflow/model/semantics/semantic_model_join_evaluator.py, metricflow/model/semantics/semantic_model_lookup.py, metricflow/model/semantics/semantic_model_semantics.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/plan_conversion/instance_converters.py, metricflow/plan_conversion/node_processor.py, metricflow/protocols/semantics.py, metricflow/query/query_parser.py, metricflow/test/dataflow/builder/test_node_evaluator.py, metricflow/test/examples/test_node_sql.py, metricflow/test/model/semantics/test_linkable_spec_resolver.py, metricflow/test/model/semantics/test_semantic_model_join_evaluator.py, metricflow/test/model/test_semantic_model_container.py, metricflow/test/plan_conversion/instance_converters/test_create_select_columns_with_measures_aggregated.py, metricflow/test/plan_conversion/instance_converters/test_create_validity_window_join_description.py, metricflow/time/time_granularity_solver.py
As a followup of renaming `DataSource` -> `SemanticModel`, `SemanticModelSemantics` is not a desirable name. So will be renaming
- `SemanticModelSemantics` -> `SemanticModelAccessor`
- `MetricSemantics` -> `MetricAccessor`
<!--- 
=> Update the naming of SemanticManifestLookup objects

.github/ACTIONS_README.md, .github/workflows/bot-changelog.yml
resolves #[CT-2462](https://github.com/dbt-labs/actions/issues/39)
Update versions of used Github Actions ahead of:
[node12 deprecation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) (Summer 2023)
[set-output deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) (fully disabled on 18th May 2023)
<!--- 
3. run `changie new` to [create a changelog entry](https://github.com/dbt-labs/metricflow/blob/main/CONTRIBUTING.md#adding-a-ch …
=> update used gh actions ahead of set-output, node12 deprecation

metricflow/model/semantics/linkable_element_properties.py, metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/metric_lookup.py, metricflow/protocols/semantics.py, metricflow/test/model/test_semantic_model_container.py
This PR exposes a way to get the semantic model where a dimension was defined when listing the available dimensions for a metric. This feature is for internal developers.
<!--- 
=> Include the Source Semantic Model for Available Dimensions

metricflow/model/semantics/linkable_spec_resolver.py, metricflow/test/model/test_semantic_model_container.py
This PR updates `ValidLinkableSpecResolver.get_linkable_elements_for_metrics()` to dedupe results in cases where there is a common path to get the same dimension from multiple measures of a metric.
<!--- 
=> Dedupe Items Returned By ValidLinkableSpecResolver.get_linkable_elements_for_metrics()

.changes/unreleased/Fixes-20230517-163839.yaml, metricflow/sql/render/big_query.py
The BigQuerySqlExpressionRenderer is updating the `value` property of
an enum value. It's possible Python passes enumeration types by value,
or does some copy on write, but most likely they're passed by reference
like everything else. As such, modifying properties on an enum instance
is likely bad form.
The existing logic also blocks mypy updates to 0.940 or later. So we
fix it here.
=> Stop updating enum values by reference in BigQuerySqlExpressionRenderer

.changes/unreleased/Under the Hood-20230517-164028.yaml, .pre-commit-config.yaml, metricflow/plan_conversion/instance_converters.py, mypy.ini
This PR improves our typechecking coverage by:
1. updating MyPy to 0.942
2. removing the blanket `--ignore-missing-imports` directive
3. cataloguing the individual import overrides
4. fixing a random type issue all of the pre-commit config re-jiggering uncovered
=> Improve typechecking coverage

.changes/unreleased/Under the Hood-20230518-115000.yaml, .github/workflows/ci-linting.yaml, .pre-commit-config.yaml, metricflow/inference/renderer/config_file.py, mypy.ini, poetry.lock, pyproject.toml
Our initial approach to using mypy was to have a .pre-commit-config
with a list of additional dependencies needed by mypy to do typechecking
on third-party packages. These dependencies cannot be easily updated in
lock-step with the package configuration we use in poetry, an issue which
has caused our CI to break in the past due to version mismatches.
Since all of our CI should build the package from a fresh virtual environment,
we have decided to risk the discrepancies that might arise for local
developers in order to ensure mypy is running against the same build
state (modulo a handful of typing packages and optional "dev-only"
installations of optional packages).
This PR moves us to local environment for mypy runs, and updates the
CI jobs to allow them to work with this configuration.
=> Move mypy to use the local environment for package dependencies

metricflow/specs/column_assoc.py, metricflow/test/fixtures/setup_fixtures.py, metricflow/test/inference/rule/test_rules.py, pyproject.toml
This PR hides deprecation warnings that come from the 3rd party libraries that are used by MF and show up as noise in the output of `pytest`.
<!--- 
=> Hide 3rd party library deprecation warnings

.changes/unreleased/Fixes-20230523-164125.yaml, .pre-commit-config.yaml, metricflow/telemetry/reporter.py
The original implementation of the log_call decorator returned an
object of type Callable[..., Any] because the version of mypy we
were using at the time did not support parameter binding correctly.
This resulted in implicit Any typing for every method wrapped with
this decorator, which means mypy would not catch errors with input
parameters. For example, the MetricFlowEngine.query() method is
typed to accept a single parameter, but callers could pass in any
combination of parameters without a typechecking error because
the `query` method was wrapped in a decorator that converted it from
it's original signature to Callable[..., Any].
Now that we are up to date on mypy, we can follow the typing guide
for decorators (or, as in this case, decorator factories) to
ensure the wrapped function …
=> Fix type signatures for log_call decorator

.github/workflows/cd-push-to-pypi.yaml
Hatch publish doesn't have a "build and publish" mode so we have
to update the action to do both.
resolves #
<!--- 
=> Fix broken publish action

.changes/unreleased/Dependencies-20230525-102100.yaml, pyproject.toml
MetricFlow no longer needs all of the dependencies listed in its
pyproject.toml - some have been vestigial for a long time, and others
have been moved to the dbt-semantic-interfaces package.
This commit also updates our dependency listing, and loosens the version
requirements for tabulate, which were pinned only due to a transitive
dependency used in the old Transform paid product.
=> Clean up MetricFlow dependencies

pyproject.toml
Somehow or other we ended up in 0.200.1. This rolls us back to
0.200.0 as our base version, and pushes the dev build up to the next
version mark.
The downside of this is 0.200.1.dev1 is no longer a usable version
number, but we can contend with that if we come to it. Given
MetricFlow's current state of development it's unlikely we'll need
to roll multiple dev builds on patch releases, so this seems like
the right trade.
=> Roll pre-release version number back to 0.200.0.dev2 from 0.200.1.dev1

metricflow/engine/models.py
In the DSI implementation of Metric, we populated all the measures associated with the Metric via a property called `input_measures` this is useful and also needed in the public facing object `engine.model.Metric`. So duplicating that logic over to that.
<!--- 
=> duplicate input_measures property to engine.model.Metric

pyproject.toml
Deploying dev3 build to pick up support for the latest updates to the semantic interfaces spec.
=> Update version to 0.200.0.dev3 for latest dev release

.changes/unreleased/Under the Hood-20230605-145703.yaml, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/engine/metricflow_engine.py
There needs to be a way to get dimension values via SQL instead of needing to make a metric query and then process the dimension values in python. In this PR, we introduce a new field to a MetricFlowQueryRequest (that is yet to be surfaced via the CLI/public interfaces). This field is `query_type` which is an enum used to determine whether the query is a metric/dim_vals query. Currently, metric query is how every query works now and dimension values query will basically return ONLY the dimensions requested in the query without the metric data.
<!--- 
3. run …
=> Get dimension values via SQL

.changes/unreleased/Under the Hood-20230608-130409.yaml, .changes/unreleased/Under the Hood-20230608-135447.yaml, metricflow/errors/errors.py, metricflow/sql/render/big_query.py, metricflow/sql/render/databricks.py, metricflow/sql/render/postgres.py, metricflow/sql/render/redshift.py, metricflow/sql/render/snowflake.py
This PR replaces a generic `RuntimeError` for a more specific exception, `UnsupportedEngineFeatureError`. This makes it easier for clients to handle this exception. I ran the unit tests locally, but other than that I didn't do much testing.
=> Specific error for unsupported data platform feature

metricflow/protocols/sql_client.py, metricflow/sql_clients/base_sql_client_implementation.py
Previously, support for query tags and isolation level were only available
in the AsyncSqlClient protocol. As part of the streamlining effort we will
be consolidating the async_query and query methods, so we add support
for these features to the base query methods in order to be able to
remove the async variations.
=> Add support for query tags and isolation in main query and execute methods

.changes/unreleased/Breaking Changes-20230613-115512.yaml, metricflow/cli/tutorial.py, metricflow/engine/metricflow_engine.py, metricflow/plan_conversion/time_spine.py, metricflow/test/cli/test_cli.py, metricflow/test/fixtures/dataflow_fixtures.py, metricflow/test/fixtures/table_fixtures.py
MetricFlow uses a time spine table under certain conditions,
such as when cumulative metric computations require us to fill
in missing dates.
The existing time spine logic would, at query planning time, run
some introspective queries to determine if the time spine table
existed, and create one spanning a range from 2000 to 2040.
MetricFlow is moving away from managing this internally. In order
to accelerate our initial integration with dbt, we will remove
this custom introspection and table creation logic from the
MetricFlow runtime.
This will effectively break any cumulative or date offset metrics
in any data warehouse that does not have a pre-existing time
spine data set matching the default MetricFlow configuration (i.e.,
with a sequence of daily granularity dates stored in a column …
=> Remove introspective queries and on the fly creation of time spine tables

.changes/unreleased/Breaking Changes-20230614-173609.yaml, metricflow/cli/cli_context.py, metricflow/engine/metricflow_engine.py, metricflow/model/data_warehouse_model_validator.py, metricflow/plan_conversion/dataflow_to_execution.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/protocols/sql_client.py, metricflow/sql/render/big_query.py, metricflow/sql/render/databricks.py, metricflow/sql/render/duckdb_renderer.py, metricflow/sql/render/expr_renderer.py, metricflow/sql/render/postgres.py, metricflow/sql/render/redshift.py, metricflow/sql/render/snowflake.py, metricflow/sql_clients/base_sql_client_implementation.py, metricflow/sql_clients/big_query.py, metricflow/sql_clients/databricks.py, metricflow/sql_clients/duckdb.py, metricflow/sql_clients/postgres.py, metricflow/sql_clients/redshift.py, metricflow/sql_clients/snowflake.py, metricflow/test/examples/test_node_sql.py, metricflow/test/integration/test_configured_cases.py, metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py, metricflow/test/sql/compare_sql_plan.py, metricflow/test/sql/test_engine_specific_rendering.py
The SqlClient protocol originally included a struct of engine properties which
was used to indicate certain engine-specific attributes which could be useful
to know about in various parts of the codebase where the SqlClient itself was
not required. The direct impetus of this construction was the need for a
backwards-compatible approach to the pre-MetricFlow implementation inside
Transform.
As time has gone by, this property struct has become increasingly cumbersome,
serving as a living record of all of the engine-specific quirks we've ever
encountered, and conflating various dialect-specific rendering elements with
core engine capabilities and python API implementation quirks.
Now that we are narrowing MetricFlow's scope of responsibility for SqlClient
state and capability management, it …
=> Eliminate engine attribute structs from SqlClient protocol

metricflow/api/metricflow_client.py, metricflow/cli/cli_context.py, metricflow/cli/main.py, metricflow/engine/metricflow_engine.py, metricflow/engine/utils.py, metricflow/model/data_warehouse_model_validator.py, metricflow/model/semantic_manifest_lookup.py, metricflow/model/semantics/semantic_model_lookup.py, metricflow/protocols/semantics.py, metricflow/test/cli/test_cli.py, metricflow/test/fixtures/cli_fixtures.py, metricflow/test/fixtures/model_fixtures.py, metricflow/test/model/test_data_warehouse_tasks.py, metricflow/test/model/test_semantic_model_container.py
resolves #587
Refactored the semanticmodel validation to use hardcode SQL query instead of creating a dummy dimension and rendering SQL to query that. This removes the need to mutate the `SemanticManifest` which allows us to remove the pydantic object. Similarly, remove the pydantic dependency for the remaining objects in the Lookup classes.
<!--- 
=> Remove dependency on PydanticSemanticManifest on validations

.changes/unreleased/Breaking Changes-20230616-125446.yaml, metricflow/cli/cli_context.py, metricflow/cli/main.py, metricflow/engine/metricflow_engine.py, metricflow/engine/utils.py, metricflow/errors/errors.py, metricflow/test/cli/test_cli.py
This PR is the first step to removing the MF configuration file and relying on a dbt project to instantiate MetricFlow. In this PR for the CLI, we move away from parsing the semantic manifest from a given path to a group of MF yaml files, but instead parse a generated `semantic_manifest.json` to a `SemanticManifest` object. There are a few assumptions in this current state in order for MF to work.
1. You must be running `mf` in a dbt project root directory
2. The `target-path` specified in `dbt_project.yml` is assumed to be the default which is `target`
3. A `semantic_manifest.json` is generated in the default path `{DBT_ROOT}/target/semantic_manifest.json`
Resolves SEM-327
<!--- 
1. read [the contributing …
=> Build a semantic manifest from dbt project root directory

.changes/unreleased/Features-20230621-183113.yaml, Makefile, metricflow/cli/dbt_connectors/adapter_backed_client.py, metricflow/errors/errors.py, metricflow/sql_clients/sql_utils.py, metricflow/test/fixtures/dbt_projects/metricflow_testing/.gitignore, metricflow/test/fixtures/dbt_projects/metricflow_testing/.user.yml, metricflow/test/fixtures/dbt_projects/metricflow_testing/README.md, metricflow/test/fixtures/dbt_projects/metricflow_testing/dbt_project.yml, metricflow/test/fixtures/dbt_projects/metricflow_testing/models/example/my_first_dbt_model.sql, metricflow/test/fixtures/dbt_projects/metricflow_testing/models/example/my_second_dbt_model.sql, metricflow/test/fixtures/dbt_projects/metricflow_testing/models/example/schema.yml, metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml, metricflow/test/fixtures/setup_fixtures.py, metricflow/test/fixtures/sql_client_fixtures.py, metricflow/test/generate_snapshots.py, metricflow/test/sql_clients/test_sql_client.py, pyproject.toml
As part of the effort to provide basic metric querying capabilities
for local installations of dbt core, MetricFlow is removing all
engine-specific dependencies and instead delegating warehouse
connection and query management to dbt adapters for integration
tests and command line operations.
This commit is the first step towards moving onto dbt adapters. It
provides a new wrapper class for dbt adapters, conforming to
MetricFlow's SqlClient protocol, and delegating all operations
down to the underlying adapter. It uses this adapter in test cases
only, and sources it from a dummy project in the test fixtures
directory. The dummy project is configured to allow for different
adapters (configured through test runner environment variables), and
in future it will likely be used as the basis for …
=> Use dbt postgres adapter wrapper for integration tests

.github/actions/run-mf-tests/action.yaml, .github/actions/setup-python-env/action.yaml, .github/workflows/cd-sql-engine-tests.yaml, Makefile, metricflow/test/fixtures/table_fixtures.py, metricflow/test/table_snapshot/table_snapshots.py
Since the race condition with the previous setup for `--use-persistent-source-schema` has been resolved, enabling the flag for CI runs. With this change, SQL engine tests can finish in <4 mins:
https://github.com/dbt-labs/metricflow/actions/runs/5360383668/jobs/9725634762
<!--- 
=> Use Persistent Source Schema for CI Tests

pyproject.toml
The dbt <-> MetricFlow integration was broken in core 1.6.0.b5,
so we update our package to the beta release with the relevant fix.
This also updates the MF version for a deploy since we need the update
to propagate to our bundle package.
=> Update MetricFlow to depend on dbt-core 1.6.0.b6

.changes/unreleased/Breaking Changes-20230623-103932.yaml, .changes/unreleased/Breaking Changes-20230626-113920.yaml, metricflow/api/metricflow_client.py, metricflow/cli/main.py, metricflow/engine/metricflow_engine.py, metricflow/test/api/test_metricflow_client.py, metricflow/test/cli/test_cli.py
Fixes SLA-116 (private to dbt Labs)
This change allows `explain_get_dimension_values` & `get_dimension_values` to take a list of metrics parameters to allow for more flexible integrations, specifically in the Jinja interface.
=> `explain_get_dimension_values` & `get_dimension_values` takes metrics lists

.changes/unreleased/Fixes-20230626-110103.yaml, metricflow/engine/utils.py, metricflow/test/cli/test_cli.py
The dbt-generated semantic manifest is not transformed, and as such
it fails at query time with inscrutable errors about missing metrics
which clearly appear in all of the manifest artifacts and runtime
objects.
This change applies the semantic manifest transformations to all
dbt-sourced json-serialized semantic manifests, and embeds the call
inside of the dbt-specific function in order to prevent confusion.
Longer term, we should refine these APIs and unify them across
dbt-semantic-interfaces and MetricFlow so that we can always be
clear about whether or not transformations are needed for a given
serialized object. This change eschews the boolean parameter approach
because we only have one mode for json parsing at this time. If we
add a second approach, this would likely benefit from …
=> Apply semantic manifest transformations to json parsed output

.changes/unreleased/Features-20230626-133439.yaml, metricflow/cli/cli_context.py, metricflow/cli/dbt_connectors/dbt_config_accessor.py, metricflow/cli/main.py, metricflow/configuration/config_builder.py, metricflow/engine/metricflow_engine.py, metricflow/engine/utils.py, metricflow/test/cli/test_cli.py
The CLI was parsing semantic manifests from the dbt project root
but then falling back to MetricFlow's config-backed SqlClient
initialization, which meant users were effectively required to
match their legacy MetricFlow config with their dbt project profile
adapter configuration.
In practice, the `query`, `list dimension-values`, and warehouse
validation steps for the `validate-configs` commands were all
effectively broken for any new user attempting to use the CLI
with the dbt project integration.
This PR enables CLI queries for all supported dbt adapters
(currently Postgres, but more to follow shortly) for any
user with a minimally valid MetricFlow config.
A follow-up PR will remove all dependencies on the legacy
MetricFlow config, which is the last remaining step before
dbt users can …
=> Enable dbt AdapterBackedSqlClient queries from the MetricFlow CLI

metricflow/cli/cli_context.py, metricflow/cli/dbt_connectors/dbt_config_accessor.py, metricflow/cli/main.py, metricflow/cli/utils.py, metricflow/test/fixtures/cli_fixtures.py
During some live testing of the tutorial we discovered two seemingly
separate but closely connected issues. First, running the tutorial
from outside of a dbt project root filled the terminal with error
trace output, and second the dreaded ResourceWarning was appearing
after certain commands.
The base of the issue was due to us having to initialize the dbt project
at the very start of the CLI invocation, before any of our handlers
were active, and then accidentally initializing it a second time
as part of the tutorial operations.
This PR fixes both issues by first ensuring that we will simply not
run the CLI at all if we are not in a dbt project root, and along
the way restructuring our dbt artifact loading stack such that
we only invoke the dbtRunner one time per process.
=> Fix tutorial loading with dbt project

dbt-metricflow/pyproject.toml
This pulls in the fixes deployed in MetricFlow 0.200.0.dev10.
=> Bump dbt-metricflow to 0.0.2

Makefile, metricflow/test/generate_snapshots.py
With the recent change back to URL-based credential management
for postgres tests, the batch snapshot generation script can
once again be used with postgres, while a direct invocation
within the makefile would fail due to the improper environment
configuration.
This consolidates the engine-specific snapshot generation back
into the script.
=> Fix snapshot generation for postgres

README.md
The MetricFlow docs under the Transform domain are no longer maintained, so
we update the link in the README to point to the new location.
=> changing metricflow docs link

.changes/unreleased/Breaking Changes-20230630-135934.yaml, metricflow/cli/main.py, metricflow/cli/utils.py, metricflow/test/cli/test_cli.py
It is a little inconsistent to use `--group-bys` when `--group-by` is used in cases of grouping by single or multiple elements.
<!--- 
=> change group-bys to group-by in the CLI

.changes/unreleased/Under the Hood-20230705-141555.yaml, metricflow/errors/errors.py, metricflow/model/semantics/linkable_spec_resolver.py
Fixes SLA-158 (internal to dbt Labs)
Raise a more specific exception when a Metric isn't found during linking. This will help with surfacing errors in the Jinja syntax. I only found one other instance of `Unknown metric` [here](https://github.com/dbt-labs/metricflow/blob/5a9e917434b1dbcbd1017ffa2e6635b84dc1c24e/metricflow/query/query_parser.py#L589), but that didn't seem related, so I didn't reuse or change that exception. This change shouldn't cause any breaking changes because `UnknownMetricLinkingError` inherits from `ValueError`
=> Raise `UnknownMetricLinkingError` if a Metric isn't found during linking

.changes/unreleased/Fixes-20230705-182137.yaml, metricflow/cli/cli_context.py, metricflow/errors/errors.py
Currently, error messages in the CLI that result from failing
warehouse health checks or any problem with the model throw a
wrapped exception. In practice, this means a user with a misconfigured
model will see an error of the form:
`ERROR: An error occurred when attempting to create the MetricFlow engine`
along with a pointer to the log file, which will contain a much more
helpful error describing the root cause of the problem.
This change removes the wrapper so that the direct cause of the
exception will be surfaced in the CLI output itself, so users
will instead see exceptions that read something more like:
```
ERROR: Metric `east_coast_order_amount` references measure `MeasureReference(element_name='orderss')` which has not been registered
```
=> Remove layer of indirection from CLI error messages

pyproject.toml
Loosen the `databricks-sql-connector` version requirement and the latest click version `8.1.4` that was just released broke the mypy tests. So restrict that to use versions before `8.1.4`
<!--- 
=> Update databricks-sql-connector and click dependency

.changes/unreleased/Fixes-20230711-132046.yaml, metricflow/cli/dbt_connectors/dbt_config_accessor.py, metricflow/cli/main.py, metricflow/model/dbt_manifest_parser.py
Resolves Issue #650 
- Added `mf --version` command
- Fixed the transform rules needed for a semantic manifest generated by `dbt-core=1.6.0b8`
<!--- 
=> Add version and make compatible fix for dbt-core 1.6.0b8

metricflow/model/dbt_manifest_parser.py, metricflow/model/semantics/semantic_model_lookup.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/specs/where_filter_transform.py, pyproject.toml
This PR makes updates as required to support `dbt-semantic-interfaces==0.1.0rc1`. This shouldn't be merged until there is a version of `dbt-core` that support the same version of `dbt-semantic-interfaces` as there is currently dependency conflict.
<!--- 
=> Update to Support `dbt-semantic-interfaces==0.1.0rc1`

CONTRIBUTING.md, dbt-metricflow/pyproject.toml
Resolves #664
This PR handles the `dbt-metricflow` package and complements https://github.com/dbt-labs/metricflow/commit/7cd3fce84f85e6152a75875ff01cfacf0805964e that handles the `metricflow` package 
It removes explicit Python version numbers from CONTRIBUTING.md to avoid needing to keep that piece up-to-date in the future.
I did not include a changelog entry, but can add one if desired.
=> Update pyproject.toml for dbt-metricflow to support Python 3.10 and 3.11

dbt-metricflow/pyproject.toml
Resolves Issue #665
See details in #665.
We can optionally change the URL as desired. I did not also add a link to a documentation website like [here](https://github.com/dbt-labs/metricflow/blob/10c8feeb8f0666c9d847098aaa248e752f3ed173/pyproject.toml#L66), but can do so if asked to.
I did not include a changelog entry, but can add one if desired.
=> URL for dbt-metricflow for PyPI

.github/pull_request_template.md
Resolves #668
This PR does two things:
- uses a [keyword that will link a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- adds a closing tag for the final comment
See #668 for more context.
I didn't include a changelog entry, but can do so if desired.
=> Use a keyword that will link a pull request to an issue

.changes/unreleased/Under the Hood-20230721-131915.yaml, .github/workflows/cd-sql-engine-tests.yaml, CONTRIBUTING.md, Makefile, metricflow/test/fixtures/sql_client_fixtures.py, pyproject.toml
As we move towards making MetricFlow proper a lean, more
standalone library we will eventually want to only build targets
that pull in a minimal set of dependencies. As a first step towards
this goal we split all packaging of engine dependencies into
separate hatch environments for testing.
This change anticipates future pushes towards integration with
dbt adapters for various engines, and subsequent updates will
move all engine dependencies out of MetricFlow proper and into
either the dev-env or the relevant engine-specific env as appropriate.
=> Separate engine-specific tests to dedicated hatch envs

README.md, pyproject.toml
This PR makes two adjustments to the project metadata:
1. Updates the MetricFlow install instructions in the README to point to the bundled dbt-metricflow package, since an independent install of MetricFlow will not be functionally useful without a dbt project. Note this file will need a broader overhaul once we finish our work on making MetricFlow a stand-alone library without explicit dependencies on either dbt or data warehouse packages.
2. Update the contact information we publish with our releases from Transform to dbt Labs.
=> Clean up project metadata for contact and installation instructions

.changes/unreleased/Under the Hood-20230724-152228.yaml, metricflow/cli/dbt_connectors/adapter_backed_client.py, metricflow/execution/execution_plan.py, metricflow/protocols/sql_client.py, metricflow/test/execution/test_tasks.py, metricflow/test/fixtures/sql_client_fixtures.py, metricflow/test/fixtures/sql_clients/adapter_backed_ddl_client.py, metricflow/test/fixtures/sql_clients/base_sql_client_implementation.py, metricflow/test/fixtures/sql_clients/big_query.py, metricflow/test/fixtures/sql_clients/databricks.py, metricflow/test/fixtures/sql_clients/ddl_sql_client.py, metricflow/test/fixtures/sql_clients/duckdb.py, metricflow/test/fixtures/sql_clients/sqlalchemy_dialect.py, metricflow/test/fixtures/table_fixtures.py, metricflow/test/integration/test_write_to_table.py, metricflow/test/source_schema_tools.py, metricflow/test/sql_clients/test_sql_client.py, metricflow/test/table_snapshot/table_snapshots.py, metricflow/test/table_snapshot/test_table_snapshots.py
MetricFlow is moving to a model where it serves as a library for
compiling and executing metric queries. This core functionality
does not require any DDL or other write operations, and so having
highly specific DDL and write query interfaces, such as the
create_table_from_dataframe method, is not warranted as part of the
core SqlClient protocol.
This PR removes those methods, and moves them to a test package
protocol in order to continue to support their only extant usage,
which is for test case setup, teardown, and verification around
certain operations.
This also moves the implementations of these methods out of the production
AdapterBackedSqlClient and into a test package extension.
This provides us with a bit more flexibility to take temporary short cuts
in order to quickly enable …
=> Remove DDL and other test-only methods from SqlClient protocol

metricflow/test/generate_snapshots.py
The test setup was recently updated to use different `hatch` environments and require additional environment variables, so this PR updates the snapshot generation script to use those.
=> Update Snapshot Generation Script with the New Test Setup

.changes/unreleased/Features-20230726-173129.yaml, metricflow/cli/dbt_connectors/adapter_backed_client.py, metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml, metricflow/test/fixtures/sql_client_fixtures.py, metricflow/test/fixtures/sql_clients/adapter_backed_ddl_client.py
This effectively enables Databricks querying through the CLI for
the dbt-metricflow integation.
This includes a number of minor finicky databricks-specific adjustments
to the test classes and explain plan handling in the main class. These
are fairly hacky, but they are either specific to test classes and
therefore good enough until we can move to something more universally
robust like calling `dbt seed` or similar, or they are temporary until
some of the issues with the BaseAdapter.validate_sql_query method are
resolved.
As such, in order to allow for an all-green commit state, the legacy
SqlClient class will be removed in a follow-up.
=> Move Databricks query execution to AdapterBackedSqlClient

metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml, metricflow/test/fixtures/sql_client_fixtures.py
The dbt env_var macro has special handling for secrets, where any
env var prefixed with DBT_ENV_SECRET will be obfuscated in logs and
other locations.
Since the profile configs we use for our integration tests often involve
runtime secrets from CI or local environments, it makes sense to use this
feature in our test setup.
=> Switch test profile env vars for dbt-backed tests to DBT_ENV_SECRET

metricflow/test/source_schema_tools.py, metricflow/test/table_snapshot/test_source_schema.py
When the test runner encounters an error with the persistent source
schema it prompts the user with an example command. That command
no longer works, and it was very difficult to find in the sea
of log output for a failed test run even with the promotion to a
warning.
This change makes the command work in an engine-specific way, which
is the current approach to our test environment management, and
improves the formatting a bit to make it more copy/paste friendly.
=> Improve messaging for populating the persistent source schema

pyproject.toml
Deploying a dev release with the adapter updates and streamlined dependencies so we can merge that into MetricFlow Server and get everything working over there.
=> Bump MetricFlow version for 0.200.dev14 release

metricflow/engine/metricflow_engine.py, metricflow/engine/models.py, metricflow/model/semantics/linkable_spec_resolver.py, metricflow/query/query_parser.py, metricflow/test/model/test_semantic_model_container.py, metricflow/test/time/test_time_granularity_solver.py, metricflow/time/time_granularity_solver.py
With https://github.com/dbt-labs/metricflow/pull/676, it's possible to remove some redundant logic in the `TimeGranularitySolver`. There are plans for additional simplification that will allow us to consolidate `MetricFlowQueryParser`, `ValidLinkableSpecResolver`, and `TimeGranularitySolver`.
=> Use ValidLinkableSpecResolver for TimeGranularitySolver Implementation

dbt-metricflow/pyproject.toml
Update dbt-metricflow with latest updates to dbt-semantic-interfaces/dbt-core/metricflow
=> Bump dbt-metricflow version to 0.0.5 for local deployment

metricflow/api/metricflow_client.py, metricflow/cli/cli_context.py, metricflow/cli/main.py, metricflow/engine/metricflow_engine.py, metricflow/model/data_warehouse_model_validator.py, metricflow/test/api/conftest.py, metricflow/test/api/test_metricflow_client.py, metricflow/test/fixtures/cli_fixtures.py, metricflow/test/integration/conftest.py, metricflow/test/integration/test_configured_cases.py, metricflow/test/model/test_data_warehouse_tasks.py
The schema property for the MetricFlowEngine was no longer used
in any way. This PR removes it from the engine and from all affected
callers, and cleans out the surrounding parameters used solely as
inputs.
=> Remove unused schema property from MetricFlow runtime

.changes/unreleased/Fixes-20230802-162013.yaml, metricflow/cli/main.py, metricflow/engine/metricflow_engine.py, metricflow/engine/models.py, metricflow/test/cli/test_cli.py
There were a handful of rough edges in the list dimensions outputs.
1. list dimension-values was returning an unsorted set, which is cumbersome
with large outputs.
2. list metrics and list dimensions was not returning the queryable qualified names
=> Clean up output of various list dimensions commands

dbt-metricflow/pyproject.toml
This will let us test the new adapter installs from non-local sources.
=> Update deps for dbt-metricflow 0.1.0.rc1 release

dbt-metricflow/pyproject.toml
0.1.0 is ready to roll. This removes all pre-release markers and relax version pins.
=> Update dbt-metricflow for release 0.1.0

.changes/unreleased/Dependencies-20230810-112855.yaml, pyproject.toml
Our CI jobs were taking forever due to needing to build an old version
of pandas from source for Python 3.11. This updates the dependency to
1.5.x, which allows us to use versions that should have updated
pre-built wheels available.
=> Update Pandas dependency to 1.5.x

.changes/unreleased/Under the Hood-20230814-225729.yaml, .github/workflows/cd-sql-engine-tests.yaml, metricflow/test/fixtures/setup_fixtures.py, pyproject.toml
MetricFlow's testing configuration currently tags sql engine types
to hatch execution environment. The standard one, which we use for
`make test`, is meant to be duckdb, but a stale environment variable
can cause inscrutable failures on any test requiring an engine
connection.
This change updates the test environment configuration to make duckdb
the standard for any runs in the hatch dev-env, including any
invocation such as `make test`. It also removes the default fallback
to duckdb, which was causing inconsistent behaviors in certain
environment configurations, and replaces it with a consistent error.
Developers with heavily customized environment configurations might
have a bad time with this, but they were already having a bad time
with other things, and at least this gives them an …
=> Make test execution more consistent and convenient

pyproject.toml
Earlier, all the mypy checks broke when click upgraded to `8.1.4`. This caused us to restrict the version to a lower version. Now, that fix is out on `8.1.6` (info here https://github.com/pallets/click/issues/2558). So reverting the version restriction and setting the restriction for mypy use only in the dev dependencies.
=> Fix click bug with mypy

metricflow/engine/metricflow_engine.py, metricflow/engine/models.py
We want a way to return a list of dimensions while showing the available granularities for time dimensions. Currently, we filter dimensions with `LinkableElementProperties.DERIVED_TIME_GRANULARITY` property and that is generally the behaviour we want where we're just returning unique dimensions. With this change, one can request dimensions with that property and it would return dimensions where each row may repeat but has a different granularity.  Ie., something like this,
```
Dimension("ordered_at", time_granularity="day")
Dimension("ordered_at", time_granularity="month")
Dimension("ordered_at", time_granularity="quarter")
Dimension("ordered_at", time_granularity="year")
Dimension("customer_type", time_granularity=None)
...
```
=> Modified dimensions_for_metric to allow for returning more details

metricflow/test/fixtures/sql_client_fixtures.py, metricflow/test/generate_snapshots.py
Fixes a couple of small issues with the snapshot generation script:
1. Allow special characters when JSON-parsing BQ password.
2. Don't use persistent source schema for Postgres.
=> Updates to snapshot generation script

metricflow/engine/metricflow_engine.py
Exposes `all_time_constraint` on MFEngine. This will be used in our APIs to expose the min and max dates MetricFlow supports.
=> Expose `all_time_constraint` on MFEngine

.changes/unreleased/Dependencies-20230905-164614.yaml, pyproject.toml
Tabulate is an optional dependency of Pandas, which we use for printing
our query results. This means we must depend on tabulate directly
otherwise users see unhelpful errors about installing the tabulate
dependency.
Our version was pinned to ~0.8.9, but this comes with unexpected
limitations for users interacting with other packages in the broader
dbt ecosystem which require 0.9 or later, so here we are.
Resolves #397
=> Allow tabulate versions >= 0.8.9

.changes/unreleased/Under the Hood-20230912-161509.yaml, metricflow/specs/query_interface.py, metricflow/specs/where_filter_entity.py, metricflow/specs/where_filter_time_dimension.py
A simple update to make the where filter query parameter objects more accurate
=> Fix where filter object inheritance

.github/workflows/cd-sql-engine-populate-persistent-source-schema.yaml, GLOSSARY.md, Makefile
When the definitions of the tables used in tests change, the persistent source schema needs to be repopulated manually. This PR adds a Github workflow to do this that can be trigged with the `Reload Test Data in SQL Engines` label.
=> Add Github workflow to populate the persistent source schema

metricflow/engine/models.py, metricflow/naming/linkable_spec_name.py
Sometimes in the API we need to parse a qualified name into its `time_granularity` and its `name`. For the `name`, we want to include entity links, not just the `element_name`. Currently, `StructuredLinkableSpecName` only supports parsing `element_name`, `entity_links`, and `time_granularity`. Adding this here to ensure we always use the same logic to get the qualified name without granularity.
=> Expose `granularity_free_qualified_name` on `StructuredLinkableSpecName`

metricflow/engine/metricflow_engine.py, metricflow/protocols/query_parameter.py, metricflow/query/query_parser.py, metricflow/specs/query_param_implementations.py, metricflow/test/conftest.py, metricflow/test/integration/test_configured_cases.py, metricflow/test/query/test_query_parser.py
Completes SL-993
Proposed updates to the protocols and implementations used for queries.
IMO, we are using the same protocols for too many things. For instance, we had a `QueryParameterDimension` as the type for the `group_by` param. `QueryParameterDimension` was required to have `grain`, and `date_part` attributes. That means that if the client wants to pass an entity or a categorical dimension into the `group_by` param, they still need to use an object with `grain` and `date_part` attributes even though those are not valid attributes for entities or categorical dimensions. This leaves us with 2 options:
1. Force the client to always include those attributes, even when they aren't valid. This simplifies type checking a lot in MF, but it seems pretty unreasonable on the client side.
2. …
=> Proposed protocols & implementations for query parameters

.changes/unreleased/Fixes-20230926-140015.yaml, metricflow/protocols/query_interface.py, metricflow/specs/where_filter_time_dimension.py
Ideally, we would bring in these changes via the DSI dependency. However, there are currently some dependency conflicts between DSI & MF see [here](https://github.com/dbt-labs/metricflow/pull/786) and [here](https://dbt-labs.slack.com/archives/C050Z6UP4RK/p1695753580056299) (internal to dbt Labs). We would like to get these changes out sooner so that we can create a dev release. We can figure out the dependencies issue later.
=> copy-paste query interface protocols from DSI into MF

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/dataflow_plan.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/query/query_parser.py, metricflow/specs/specs.py, metricflow/test/dataflow/builder/test_dataflow_plan_builder.py, metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py, metricflow/test/query/test_query_parser.py, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_order_by_plan__dfp_0.xml
Thanks to some earlier changes, the `OrderBySpec` class can be made easier / cleaner to use by having a single `InstanceSpec` field instead of more concrete types.
=> Change `OrderBySpec` to Use a Single Spec

.changes/unreleased/Under the Hood-20231006-095540.yaml, metricflow/query/query_parser.py
This surfaces the underlying error message from the where clause. This is helpful in situations like this https://dbt-labs.slack.com/archives/C03KHQRQUBX/p1696602586211399
=> Surface underlying error message in where parameter

.changes/unreleased/Fixes-20231010-144137.yaml, metricflow/query/query_parser.py, metricflow/test/query/test_query_parser.py
Support case-insensitive params in `group_by` and `order_by` parameters.
A [community member recently ran into a bug](https://getdbt.slack.com/archives/C046L0VTVR6/p1696602554947709) where they uppercased a dimension in the `group_by`, which worked, but then the same syntax didn't work in the `order_by`. This should fix that issue.
=> Case insensitivity for query params

.changes/unreleased/Fixes-20231009-195312.yaml, metricflow/dataflow/builder/dataflow_plan_builder.py
Fixes a bug in how we determine which source node to use. Previously, we were choosing a plan based on source node cost. Source nodes can only be `ReadSqlSourceNode` or `MetricTimeDimensionTransformNode`, so they all have `DefaultCost(num_joins=0, num_aggregations=0)`. That means we were just arbitrarily choosing a source node that could satisfy the query. Here, the logic changes to use the number of joins in each node's `LinkableInstanceSatisfiabilityEvaluation`, so we choose the dataflow plan with the lowest number of joins.
Note that this fixes a bug that came up in the process of enabling querying dimensions without metrics.
Also: we have a log that says `Not evaluating other nodes since we found one that doesn't require joins`, but we don't stop evaluating nodes at that point. I …
=> Bug fix: source node evaluation

.github/workflows/cd-sql-engine-populate-persistent-source-schema.yaml, .github/workflows/cd-sql-engine-tests.yaml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_distinct_values__plan0.sql, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_distinct_values__plan0_optimized.sql, pyproject.toml
Most of our SQL engine tests have been broken for a few days.
1. All tests apart from Postgres and DuckDB were broken due to our update to dbt-core 1.7.0rc1
2. Databricks was broken because the cluster target was taken offline
This PR addresses both issues and gets everything running again.
See individual commits for details on each necessary fix.
=> Fix broken SQL engine tests

metricflow/query/query_parser.py, metricflow/test/integration/test_cases/itest_metrics.yaml
Found a bug where date part queries error for any time dimension that isn't `metric_time`. This wasn't caught because all of our tests used `metric_time` (in both MF and MFS) - lesson learned! This creates an instant bug if you try to use any time dimension besides `metric_time` in our Tableau integration.
This is not the ideal fix. Ideally we'll need to put `date_part` in the validation path the way that `time_granularity` is, but we don't have time to do that before the fix needs to ship.
=> Remove error for date part with non-metric time dimension

.changes/unreleased/Dependencies-20231026-151457.yaml, pyproject.toml
The `@override` decorator was added to typing-extensions with version
4.4, but our minimum version is 4.0, which means there are scenarios
where this will suddenly start throwing errors.
Since we require 4.4, let's make that true in the build directive.
=> Update minimum typing-extensions version to 4.4

metricflow/test/cli/test_cli.py, metricflow/test/dataflow/builder/test_dataflow_plan_builder.py, metricflow/test/dataflow/optimizer/source_scan/test_cm_branch_combiner.py, metricflow/test/dataflow/optimizer/source_scan/test_source_scan_optimizer.py, metricflow/test/dataset/test_convert_semantic_model.py, metricflow/test/fixtures/setup_fixtures.py, metricflow/test/generate_snapshots.py, metricflow/test/integration/test_rendered_query.py, metricflow/test/model/test_data_warehouse_tasks.py, metricflow/test/plan_conversion/dataflow_to_sql/test_metric_time_dimension_to_sql.py, metricflow/test/plan_conversion/test_dataflow_to_execution.py, metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py, metricflow/test/snapshot_utils.py, metricflow/test/sql/compare_sql_plan.py, metricflow/test/sql/test_engine_specific_rendering.py, metricflow/test/sql/test_sql_plan_render.py
This PR adds a custom pytest marker to mark tests that generate SQL-engine-specific snapshots. This helps to ensures that the `generate_snapshots.py` script generates snapshots for all relevant tests.
=> Mark Tests That Generate SQL-Engine-Specific Snapshots

.github/workflows/cd-sql-engine-tests.yaml
Currently, when iterating on a PR, the PR author would need to remove and then re-add the label to rerun the SQL-engine tests. This PR updates the Github Action workflow to remove the label for running the SQL engine tests after the tests are complete.
=> Update sql-engine-test workflow to remove label on completion.

metricflow/test/cli/test_cli.py, metricflow/test/fixtures/cli_fixtures.py, metricflow/test/fixtures/setup_fixtures.py, metricflow/test/fixtures/sql_client_fixtures.py
We use pytest-xdist for parallel test execution, which means multiple
worker threads fire up tests which are loosely grouped by class/module.
Unfortunately, there are no guarantees around any of this, so the CLI
tests, which are all in one module, may execute on different workers.
We had a bad fixture layout on the CLI tests which would touch a file
in the CLI directory and then unlink it after the test was done. If
every test ran on the same worker this was fine - only one test would
ever be accessing this path location at a time. But when the tests get
split across workers bad things happen with FileNotFound and things
of that nature.
This change moves us off of having multiple tests creating and
destroying the same file in the same file path location, instead
relying on a fixed file …
=> Fix random failures with parallel CLI tests

pyproject.toml
Tiny fix for this DuckDB install command. I noticed that lately, every time Hatch install dependencies for `dev-env`, I would end up with a rogue file called `=0.7.0`. Turns out Hatch was interpreting this command incorrectly: `pip install duckdb>=0.7.0`. It was running `pip install duckdb`, and dumping the output of that command to a new file called `=0.7.0`. This PR updates the command to `pip install "duckdb>=0.7.0"`, which appears to have the intended effect.
=> Quote DuckDB version in install command

Makefile, metricflow/test/generate_snapshots.py, metricflow/test/populate_persistent_source_schemas.py
I found it annoying to have to populate the persistent source schemas for each engine individually, especially since that required setting the warehouse connection env variables for each engine before you could properly run each make target. So I wrote a script / make target to populate the persistent source schemas for all relevant engines at once, making use of the logic in `generate_snapshots.py` to set those variables dynamically.
Try running `make populate-persistent-source-schemas` to test this out yourself!
=> Script for populating all persistent source schemas

.changes/unreleased/Fixes-20231108-150708.yaml, metricflow/query/query_parser.py, metricflow/test/query/test_query_parser.py
Resolves #825
As of right now we require metric_time in the group by expression
for any metric query against cumulative metrics or derived metrics
with time offset windows or an offset_to_grain parameter set.
The current query validation was only asserting that some time
dimension was included in the group by. In the case of derived
metrics, this simply failed later in the query building phase for
any query with a different time dimension in the group by expression.
In the case of cumulative metrics, this would run an incorrectly
rendered query and then return incorrect results.
This validation change ensures that users have the proper
configuration on queries based on our current limitations.
=> Fix query validation for metric_time requirements

.changes/unreleased/Dependencies-20231109-172955.yaml, pyproject.toml
All of our dbt dependencies now have official 1.7.0 releases
available, so we can update our internal depedencies accordingly.
=> Update dbt dependencies to ~=1.7.0

metricflow/plan_conversion/dataflow_to_sql.py, metricflow/test/fixtures/dataflow_fixtures.py, metricflow/test/fixtures/semantic_manifest_yamls/extended_date_manifest/metrics/bookings_last_month.yaml, metricflow/test/fixtures/sql_fixtures.py, metricflow/test/query_rendering/test_derived_metric_rendering.py, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql
Added this test case to make sure it would work for [a customer's use case](https://getdbt.slack.com/archives/C046L0VTVR6/p1699548838051619) - a derived metric with an input metric that uses month granularity.
Also cleaned up the messaging in an error message I encountered along the way.
=> Add test for time offset metric based on non-default granularity

dbt-metricflow/pyproject.toml, pyproject.toml
This includes updates to package dependencies:
dbt-core and all dbt-adapters to ~=1.7.0
metricflow to ~=0.203.0
=> Update dbt-metricflow to 0.4.0

.changes/unreleased/Dependencies-20231113-181503.yaml, metricflow/cli/main.py, metricflow/engine/metricflow_engine.py, metricflow/telemetry/handlers/handlers.py, metricflow/telemetry/reporter.py, metricflow/test/telemetry/test_telemetry.py, mypy.ini, pyproject.toml
Prior to its acquisition by dbt Labs, Transform used Rudderstack
for analytics event log handling. As a result, the MetricFlow
telemetry system included the option to log data to Rudderstack.
Nowadays there is no longer a need to support this route, and indeed
the Rudderstack client itself causes some small problems, such as
the occasional irrepressible warning about SSL sockets failing
to close properly after running queries in the MetricFlow CLI.
=> Remove RudderStack logging from MetricFlow telemetry

.changes/unreleased/Dependencies-20231115-144849.yaml, pyproject.toml
Due to my persistent inability to understand the semantics of
Python's `~=` version syntax I accidentally pinned typing extensions
to 4.4.x instead of >= 4.4, < 5.
This addresses the error.
=> Relax version pin on typing-extensions to ~=4.4

metricflow/collections/merger.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/specs/specs.py, metricflow/test/collections/test_merger.py, metricflow/test/test_specs.py
This PR adds the utility class `MergeBuilder` that allows you to combine collections that implements `Mergeable`. This is useful as there are a few spec-related classes that are collections, and there are upcoming cases where they need to be merged. This replaces the collection of merge-related methods in the spec set classes.
This PR also includes a minor update to the signature of `InstanceSpec` to make it more flexible.
=> Add `Mergeable` to Simplify Merging Collections

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/node_evaluator.py, metricflow/engine/metricflow_engine.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/plan_conversion/instance_converters.py, metricflow/plan_conversion/node_processor.py, metricflow/specs/specs.py
This PR includes a set of assorted changes to the convenience methods of the spec classes to make them more consistent in naming / easier to use.
=> Assorted Spec Convenience Method Changes

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/model/semantics/metric_lookup.py, metricflow/protocols/semantics.py
This PR separates the recursive handling of derived metrics into cases 
using different methods that are shorter / easier to understand:
* Build a node to compute a simple / base metric.
* Build a node to compute a derived metric.
* Build a node to compute a metric of any type.
* Build a node to compute many metrics.
In addition, this also moves MetricLookUp.measures_for_metric() into the
DataflowPlanBuilder because it seemed a little out of place in MetricLookUp
due to the dependence on the column association resolver.
This is mostly a shuffling of the code w/o logic changes.
=> Organize DataflowPlanBuilder Recursive Case Handling

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/dataflow_plan.py, metricflow/specs/specs.py, metricflow/test/test_instance_serialization.py
I found the `DataflowPlanBuilder` hard to follow in regards to when the measure would be joined to the time spine. There was conditional logic that depended on several parameters scattered throughout methods. This PR encapsulates the join condition in `MetricInputMeasureSpec`, and the consolidates filling out those fields when that spec is constructed. Once the behavior is encapsulated, the signature for methods `_build_aggregated_measure_from_measure_source_node()` can be simplified.
There's additional consolidation that can be done for cumulative measure parameters, but putting that off for now as consolidating this logic has been complex as it is. Also, there's a potential edge case with nested derived offset metrics that was found, but it is not addressed here.
=> Consolidate Measure Time Spine Join Conditional Behavior Into `MetricInputMeasureSpec`

metricflow/specs/patterns/entity_link_pattern.py, metricflow/specs/patterns/spec_pattern.py, metricflow/specs/patterns/typed_patterns.py, metricflow/test/specs/patterns/test_entity_link_pattern.py, metricflow/test/specs/patterns/test_typed_patterns.py
This PR implements the pattern classes for ambiguous group-by-items as described in https://github.com/dbt-labs/metricflow/pull/new/plypaul--58.7--spec-pattern.
=> Add `SpecPattern` Classes to Model Ambiguous Group-By-Item Inputs

metricflow/naming/dunder_scheme.py, metricflow/naming/metric_scheme.py, metricflow/naming/naming_scheme.py, metricflow/naming/object_builder_scheme.py, metricflow/specs/patterns/metric_pattern.py, metricflow/test/naming/conftest.py, metricflow/test/naming/test_dunder_naming_scheme.py, metricflow/test/naming/test_metric_name_scheme.py, metricflow/test/naming/test_object_builder_naming_scheme.py
These naming scheme classes will be used in the query parser to convert string inputs into patterns. The patterns will be used later to resolve ambiguous group-by-items.
=> Add Naming Schemes to Represent Different Input Formats

metricflow/engine/metricflow_engine.py, metricflow/engine/models.py, pyproject.toml
Resolves SL-1390
Expose saved queries on MFEngine to be added to our APIs.
=> Expose Saved Queries on MFEngine

.changes/unreleased/Fixes-20231207-170704.yaml, metricflow/engine/metricflow_engine.py, metricflow/query/query_parser.py, metricflow/test/cli/test_cli.py, metricflow/test/integration/test_configured_cases.py
Resolves #917
A previous change (https://github.com/dbt-labs/metricflow/pull/918) updated the logic to apply a default time constraint for queries with cumulative metrics if one was not supplied. However, the fix revealed that the feature was not working for some time, possibly since the public release. I also realized that the original logic (and also the fix) is not correct with derived metrics that use cumulative metrics. There is future work to better handle time constraints / predicate push down, so removing this for now.
=> Remove Default Time Constraint for Queries with Cumulative Metrics

.changes/unreleased/Fixes-20231215-154356.yaml, metricflow/cli/main.py, metricflow/test/cli/test_cli.py
Resolves #867 
When an exception happens in validate-configs on the CLI, return exit code 1.
=> Return exit code 1 for failed validations

.changes/unreleased/Fixes-20231215-141744.yaml, metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/test/dataflow/optimizer/source_scan/test_source_scan_optimizer.py, metricflow/test/fixtures/semantic_manifest_yamls/simple_manifest/metrics.yaml, metricflow/test/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_2_ratio_metrics_from_1_semantic_model__dfpo_0.xml, metricflow/test/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_duplicate_measures__dfp_0.xml, metricflow/test/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_duplicate_measures__dfpo_0.xml
If there are multiple derived metrics in a query that use the same metric, it's
possible that the same metric is used multiple times. In such cases, the metric
should be deduped so that we don't get a collision in the colum name.
=> Fix Optimizer to Dedupe Cases Where a Metric Is Used More Than Once

.changes/unreleased/Features-20231218-121506.yaml, metricflow/query/issues/parsing/duplicate_metric.py, metricflow/query/validation_rules/base_validation_rule.py, metricflow/query/validation_rules/duplicate_metric.py, metricflow/query/validation_rules/metric_time_requirements.py, metricflow/query/validation_rules/query_validator.py, metricflow/test/query/test_query_parser.py
Resolves #943 
This PR add a validation to check that queries do not contain the same metric more than once, as that would result in a duplicate column in the generated SQL.
=> Add a Validation Rule for Duplicate Metrics in a Query

metricflow/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow/query/group_by_item/filter_spec_resolution/filter_spec_resolver.py, metricflow/query/group_by_item/group_by_item_resolver.py, metricflow/query/group_by_item/resolution_dag/resolution_nodes/measure_source_node.py, metricflow/query/group_by_item/resolution_dag/resolution_nodes/metric_resolution_node.py, metricflow/query/issues/group_by_item_resolver/no_matching_items_for_measure.py, metricflow/query/issues/parsing/invalid_metric.py, metricflow/query/query_parser.py, metricflow/query/query_resolver.py, metricflow/query/resolver_inputs/query_resolver_inputs.py, metricflow/query/similarity.py, metricflow/query/suggestion_generator.py, metricflow/specs/patterns/match_list_pattern.py, metricflow/test/query/group_by_item/test_matching_item_for_filters.py, metricflow/test/query/group_by_item/test_matching_item_for_querying.py, metricflow/test/query/test_suggestions.py, metricflow/test/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_filter__result.txt, metricflow/test/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_input_filter__result.txt, metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_defined_filters_in_multi_metric_query__result_0.txt, metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_defined_where_filter__result_0.txt, metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_group_by_item__result_0.txt, metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_metric__result_0.txt, metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_multiple_metrics__result_0.txt, metricflow/test/source_schema_tools.py
This PR adds suggestions to error messages for metrics / group-by-items specified by the user.
=> Add Suggestions for User Input Errors

.changes/unreleased/Features-20240102-163031.yaml, metricflow/engine/models.py
Resolves #SL-1485
Expose `label` attribute for `Metrics` & `Dimensions` on `MFEngine`. Needed in APIs - will be used for partners to build integrations.
=> Expose `label` on MFEngine Metric

.github/workflows/cd-push-to-pypi.yaml
We are no longer able to use username & PW to publish to PyPi - switching to API token instead.
=> Use API token when publishing to PyPi

metricflow/query/group_by_item/filter_spec_resolution/filter_spec_lookup.py, metricflow/query/group_by_item/filter_spec_resolution/filter_spec_resolver.py, metricflow/query/query_resolver.py, metricflow/test/fixtures/semantic_manifest_yamls/ambiguous_resolution_manifest/metrics.yaml, metricflow/test/query/group_by_item/filter_spec_resolution/test_spec_lookup.py, metricflow/test/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_derived_metrics_with_common_filtered_metric__result.txt
Ambiguous group-by-items can be present in the filter definition, and those need to be resolved to concrete specs.
Previously, `FilterSpecResolutionLookUp` deduped the resolution for ambiguous group-by-items if the same resolution appears multiple times while resolving all ambiguous group-by-items in a query. For example, with the following metric definitions:
```
---
metric:
name: derived_metric_with_common_filtered_metric_0
description: One of the derived metrics that have the same metric + filter.
type: derived
type_params:
expr: monthly_metric_0
metrics:
- name: monthly_metric_0
filter: "{{ TimeDimension('metric_time') }} = '2020-01-01'"
---
metric:
name: derived_metric_with_common_filtered_metric_1
description: One of the derived metrics that have the same metric + filter.
type: …
```
=> Store All Resolutions in `FilterSpecResolutionLookUp`

metricflow/engine/metricflow_engine.py, metricflow/query/group_by_item/filter_spec_resolution/filter_pattern_factory.py, metricflow/query/group_by_item/filter_spec_resolution/filter_spec_resolver.py, metricflow/query/query_parser.py, metricflow/query/query_resolver.py, metricflow/test/fixtures/dataflow_fixtures.py, metricflow/test/fixtures/model_fixtures.py, metricflow/test/query/group_by_item/filter_spec_resolution/test_spec_lookup.py, metricflow/test/query/test_suggestions.py
Resolves #
This PR updates the initializer for `MetricFlowEngine` to allow a query parser to be passed in. A different query parser can be used to alter how inputs to the engine are handled.
=> Expand `MetricFlowEngine` Initializer Signature

.changes/unreleased/Fixes-20240110-140727.yaml, metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/model/dbt_manifest_parser.py, metricflow/model/transformations/dedupe_metric_input_measures.py
Resolves #969 
Currently, when running through the branch combiner, in an instance where you have 2 derived metrics that contains the same input measure, it would get combined and it doesn't get deduped. Example,
```yaml
metric:
name: "derived1"
description: Test child derived metric 1
type: derived
type_params:
expr: "booking_value + bookings"
metrics:
- name: booking_value
- name: bookings
---
metric:
name: "derived2"
description: Test child derived metric 2
type: derived
type_params:
expr: "bookings + instant_bookings"
metrics:
- name: instant_bookings
- name: bookings
---
metric:
name: "derived_parent"
description: Test parent derived metric
type: derived
type_params:
expr: "derived1 + derived2"
metrics:
- name: derived1
- name: derived2
```
This leads to hitting an error during the …
=> Fix duplicate input measures error

.changes/unreleased/Dependencies-20231219-170616.yaml, pyproject.toml
Resolves #927
We do not use MarkupSafe directly. Historically, we've needed this
because sometime, somewhere, something was causing runtime problems
with the way Pandas was importing and loading MarkupSafe.
Whatever that was appears to have been fixed - clean installs still
load MarkupSafe (since it's a transitive dependency) and everything
appears to be working as normal.
=> Remove MarkupSafe dependency

metricflow/test/generate_snapshots.py, metricflow/test/snapshots/test_query_rendering.py/SqlQueryPlan/Trino/test_min_max_only_categorical__plan0.sql, metricflow/test/snapshots/test_query_rendering.py/SqlQueryPlan/Trino/test_min_max_only_categorical__plan0_optimized.sql, metricflow/test/snapshots/test_query_rendering.py/SqlQueryPlan/Trino/test_min_max_only_time__plan0.sql, metricflow/test/snapshots/test_query_rendering.py/SqlQueryPlan/Trino/test_min_max_only_time__plan0_optimized.sql, metricflow/test/snapshots/test_query_rendering.py/SqlQueryPlan/Trino/test_min_max_only_time_quarter__plan0.sql, metricflow/test/snapshots/test_query_rendering.py/SqlQueryPlan/Trino/test_min_max_only_time_quarter__plan0_optimized.sql
The Trino engine tests are failing due to missing snapshots for
a recently added feature.
While fixing this, I discovered the snapshot generation script was
not working correctly for Trino engine updates, so this fixes
the script as well.
=> Add missing Trino snapshots

dbt-metricflow/pyproject.toml
With the release of MetricFlow 0.204.0 we can now release
dbt-metricflow 0.5.0 to complement it.
Note MetricFlow nominally depends on dbt-core 1.7.x, but installs
with that specific version will not be able to use conversion
metrics. That's a boundary case we should probably fix with a patch
release for MetricFlow.
In the meantime, we  ensure the installation helper dbt-metricflow
will force an update to the proper minimum version of dbt-core.
=> Update dbt-metricflow version to 0.5.0

metricflow/model/semantics/semantic_model_lookup.py
`SemanticModelLookup` keeps track of all the valid measures, dimensions, and entities for a given semantic manifest using dictionaries `_measure_index`, `_dimension_index`, `_entity_index`, and `_linkable_reference_index`. These are used for various purposes, one of which is to check if a given measure/dimension/entity name is valid (i.e., if someone queries a dimension name that's not in the index, we will raise an error telling them the dimension doesn't exist).
Previously, these were created as `defaultdicts`. This simplifies the code, but creates a potential bug. If someone queries `get_dimension()` with a dimension that doesn't exist, we will raise the appropriate error, but with an unintended side effect. When you index into a `defaultdict` using a key that doesn't exist yet, that …
=> Potential bug fix: Don't use `defaultdict` for `SemanticModelLookup` indexes

Makefile, local-data-warehouses/Makefile, local-data-warehouses/trino/docker-compose.yaml
Quick dev improvement. Adds a make target to run a Trino warehouse locally. This makes it so you can run `make trino` instead of needing to remember the docker command to run it.
=> Add a make target to run Trino warehouse locally

.changes/unreleased/Dependencies-20240119-174213.yaml, pyproject.toml
Licensing analysis tripped a potential issue with numpy. The
thing is we don't use numpy for anything - this dependency is
only here because some past transitive dependency caused issues
with M1 macs and pinning a minimum version for numpy ensured
that particular problem would not come up. Even the initial
addition was to pin past some security patch. Wild.
Anyway, rather than try to figure out if the new licensing
issue is a false positive, I'm simply removing the package from
our linked dependency set.
=> Remove unused numpy dependency

.github/workflows/cd-sql-engine-tests.yaml
This GitHub Action requires manual approval to run in order to
protect the various warehouse credentials included in it.
However, we trigger it on every push to main, and those nearly
always go without approval. In practice, these tests are only
run manually, either via a PR label or the occasional "I want
to run these on trunk so I'll approve the last one of these that
triggered off a push to main".
We can do the latter via workflow_dispatch anyway, so let's just
get rid of the nearly-universally-ignored action trigger.
=> Stop triggering SQL Engine Tests on push to main

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/specs/specs.py
Tiny cleanup: in a past PR me/Tom/Paul agreed to remove the use of the word "culmination" in reference to cumulative metrics, but there were a few places where that change was missed.
=> Tiny cleanup: Rename culmination -> cumulative

metricflow/test/fixtures/semantic_manifest_yamls/extended_date_manifest/metrics/bookings_monthly_cumulative.yaml, metricflow/test/integration/test_cases/itest_cumulative_metric.yaml, metricflow/test/query_rendering/test_cumulative_metric_rendering.py, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/BigQuery/test_cumulative_metric_month__plan0.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/BigQuery/test_cumulative_metric_month__plan0_optimized.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Databricks/test_cumulative_metric_month__plan0.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Databricks/test_cumulative_metric_month__plan0_optimized.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/DuckDB/test_cumulative_metric_month__plan0.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/DuckDB/test_cumulative_metric_month__plan0_optimized.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Postgres/test_cumulative_metric_month__plan0.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Postgres/test_cumulative_metric_month__plan0_optimized.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Redshift/test_cumulative_metric_month__plan0.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Redshift/test_cumulative_metric_month__plan0_optimized.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Snowflake/test_cumulative_metric_month__plan0.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Snowflake/test_cumulative_metric_month__plan0_optimized.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Trino/test_cumulative_metric_month__plan0.sql, metricflow/test/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Trino/test_cumulative_metric_month__plan0_optimized.sql
We didn't have any test cases for cumulative metrics based on non-day granularity, so this adds one.
=> Add test case for cumulative metric with non-day granularity

metricflow/dataflow/builder/dataflow_plan_builder.py
Small cleanup. The parameter contains measures, not measure names, so should be named accordingly.
=> Use appropriate variable name

metricflow/query/issues/group_by_item_resolver/multiple_join_paths.py, metricflow/specs/patterns/entity_link_pattern.py, metricflow/test/fixtures/model_fixtures.py, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/all_entity_measure_source.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/entity_0_dimension_source.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/entity_0_measure_source.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/entity_1_and_entity_2_measure_source.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/entity_1_dimension_source.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/entity_1_measure_source.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/entity_1_to_entity_0_mapping_source.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/entity_2_to_entity_0_mapping_source.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/metrics.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_multi_hop_join_manifest/project_configuration.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/all_entity_measure_table.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/entity_0_dimension_table.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/entity_0_measure_table.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/entity_1_and_entity_2_measure_table.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/entity_1_dimension_table.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/entity_1_measure_table.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/entity_1_to_entity_0_mapping_table.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/entity_2_measure_table.yaml, metricflow/test/fixtures/source_table_snapshots/simple_multi_hop_join_manifest/entity_2_to_entity_0_mapping_table.yaml, metricflow/test/query/test_ambiguous_entity_path.py, metricflow/test/snapshots/test_ambiguous_entity_path.py/MetricFlowQuerySpec/test_ambiguous_entity_path_resolves_to_shortest_entity_path_item__result_0.txt, metricflow/test/snapshots/test_ambiguous_entity_path.py/MetricFlowQuerySpec/test_resolvable_ambiguous_entity_path__result_0.txt, metricflow/test/snapshots/test_ambiguous_entity_path.py/str/test_non_resolvable_ambiguous_entity_path_due_to_mismatch__result_0.txt, metricflow/test/snapshots/test_ambiguous_entity_path.py/str/test_non_resolvable_ambiguous_entity_path_due_to_multiple_matches__result_0.txt
This PR allows for partial entity paths to be specified for group-by-items. e.g. `user__country` instead of `listing__user__country` if there is a unique shortest path available.
=> Allow Partial Entity Paths in Group-By-Items

metricflow/dataflow/builder/node_evaluator.py
Resolves [a bug](https://dbtlabsmt.datadoghq.com/logs?query=service%3Ametricflow-server%20status%3A%28error%20OR%20info%20OR%20warn%29%20cross%20join%20&cols=host%2Cservice&event=AgAAAY1CURh7OqhiHgAAAAAAAAAYAAAAAEFZMUNVU1BaQUFCbDVWMXY5LWllSUFBMQAAACQAAAAAMDE4ZDQyNTEtMjQ0ZC00ZGNhLTg1YTUtMGM2ZDBiMjI0OTll&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1706210388237&to_ts=1706213988237&live=true) found during Tableau complaint storm. We should be using the join type specified for the join candidate here instead of the default join type. This caused an error when joining to the time spine table, since the default join type for distinct values queries is `FULL OUTER JOIN` but time spine joins require `CROSS JOIN`.
=> Bug fix: always use candidate join type when evaluating nodes to join

metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/metric_lookup.py, metricflow/model/semantics/semantic_model_lookup.py, metricflow/protocols/semantics.py, metricflow/specs/specs.py, metricflow/test/model/test_semantic_model_container.py
Adds some methods that will be used to enable querying with `agg_time_dimension` instead of `metric_time`.
`MetricLookup.get_valid_agg_time_dimensions_for_metric()` will be used in validations, while `SemanticModelLookup.get_agg_time_dimension_specs_for_measure()` will be used in query building.
=> Methods to look up `agg_time_dimensions`

.github/workflows/cd-sql-engine-populate-persistent-source-schema.yaml, metricflow/test/populate_persistent_source_schemas.py
The populate persistent source schema GitHub action has a
workflow_dispatch trigger, but when you attempt to use it all
actions are immediately skipped.
This makes the changes necessary to enable the workflow_dispatch
trigger to execute the tasks in this workflow.
=> Fix conditional execution on populate schema action

.changes/unreleased/Under the Hood-20240125-171747.yaml, metricflow/test/fixtures/semantic_manifest_yamls/simple_manifest/metrics.yaml, metricflow/test/query_rendering/test_derived_metric_rendering.py, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_nested_filters__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_nested_filters__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_nested_filters__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_nested_filters__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_nested_filters__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_nested_filters__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_nested_filters__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_nested_filters__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_nested_filters__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_nested_filters__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_nested_filters__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_nested_filters__plan0_optimized.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_nested_filters__plan0.sql, metricflow/test/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_nested_filters__plan0_optimized.sql
We received a report of filters on nested derived metrics failing
to render. This issue was resolved as part of the updates we made
to our group by item and filter resolution components, and should
no longer be a problem with the new query parsing and dataflow plan
layout components. However, those components did not include a query
rendering test case for nested derived filters.
This adds the relevant test case from query specification through
the query parser and final SQL rendering.
=> Add query rendering test for filters on nested derived metrics

metricflow/engine/models.py
When using the MFE, when we retrieve saved queries object they don't have the exports field as it doesn't exist in the MFE model object.
=> add exports to MFE SavedQuery object

metricflow/dag/dag_to_text.py
Get a bunch of these errors when running queries through multithreading 
```
Got an exception while converting SqlSelectStatementNode(node_id=ss_84) to text
Traceback (most recent call last):
File "/Users/william/git/metricflow/metricflow/dag/dag_to_text.py", line 209, in dag_component_to_text
return self._recursively_format_to_text(dag_component_leaf_node)
File "/Users/william/git/metricflow/metricflow/dag/dag_to_text.py", line 164, in _recursively_format_to_text
with self._max_width_tracker.update_max_width_for_indented_section(
File "/Users/william/git/metricflow/metricflow/dag/dag_to_text.py", line 77, in _max_width_tracker
return self._thread_local_data.max_width_tracker
AttributeError: '_thread._local' object has no attribute 'max_width_tracker'
```
=> Fix threading issue with the dag to text

metricflow/dag/dag_to_text.py, metricflow/test/mf_logging/test_dag_to_text.py
This PR makes some minor updates to `MetricFlowDagTextFormatter`:
* Removes an unnecessary assignment.
* Adds a multithreaded test.
* Updates exception logging to be more helpful.
=> Minor Updates to `MetricFlowDagTextFormatter`

.changes/unreleased/Dependencies-20240119-174213.yaml, .changie.yaml, .github/workflows/bot-changelog.yml
The `Issue` entry in our changelogs is required to be non-empty,
and if it is we format the value into a GitHub link in the final
changelog. This leads to broken links pointing at things like
issue `None` or `0`.
This change updates the changelog formatting to skip over those
entries when forming issue links, and skip formatting in issue
lists if no issues are included. We still include the contributor
and change body, so all due credit remains, just minus the need
for validating common circumventions to our request for issue
numbers.
Running `changie batch 0.205.0  -d` on the underlying trunk commit
and comparing it here illustrates the new behavior with the
docs entry - and the associated author change list - no longer
including bad links.
Since the logic involved was fairly …
=> Streamline Changelog generation to remove invalid issue links

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/node_data_set.py, metricflow/dataflow/builder/source_node.py, metricflow/engine/metricflow_engine.py, metricflow/mf_logging/runtime.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/test/fixtures/manifest_fixtures.py, metricflow/test/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_count_with_no_group_by__plan0.xml, metricflow/test/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_rate__plan0.xml, metricflow/test/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_rate_with_constant_properties__plan0.xml, metricflow/test/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_rate_with_no_group_by__plan0.xml, metricflow/test/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_rate_with_window__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_compute_metrics_node_ratio_from_multiple_semantic_models__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_dimension_with_joined_where_constraint__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_dimensions_requiring_join__plan0.xml, metricflow/test/snapshots/test_distinct_values_to_sql.py/SqlQueryPlan/test_dimension_values_with_a_join_and_a_filter__plan0.xml, metricflow/test/snapshots/test_distinct_values_to_sql.py/SqlQueryPlan/test_dimensions_requiring_join__plan0.xml, metricflow/test/snapshots/test_metric_time_dimension_to_sql.py/SqlQueryPlan/test_simple_query_with_metric_time_dimension__plan0.xml, metricflow/test/snapshots/test_metric_time_without_metrics.py/SqlQueryPlan/test_dimensions_with_time_constraint__plan0.xml, metricflow/test/snapshots/test_metric_time_without_metrics.py/SqlQueryPlan/test_metric_time_only__plan0.xml, metricflow/test/snapshots/test_metric_time_without_metrics.py/SqlQueryPlan/test_metric_time_quarter_alone__plan0.xml, metricflow/test/snapshots/test_metric_time_without_metrics.py/SqlQueryPlan/test_metric_time_with_other_dimensions__plan0.xml
When building a `DataflowPlan`, nodes from `SourceNodeSet` are used as common building blocks for different queries using the same semantic manifest. When the output for a `DataflowPlanNode` is computed, the output is lazily computed and then cached since the output will be required many times for the same nodes (e.g. between queries, and between common join candidates). The output contains generated IDs, and so precomputing the output nodes for nodes from `SourceNodeSet` will have the following effects:
* The runtime of building the `DataflowPlan` should be a little more consistent between queries at the expense of initialization time.
* The IDs in the generated output will be consistent regardless of the order queries seen by the `DataflowPlanBuilder`.
=> Precompute / Cache Outputs for Nodes in `SourceNodeSet`

pyproject.toml
Due to some inconsistencies in dependency resolution for Python
package versions listed using the ~= syntax, we are switching
everything to explicit ranges using >=, < for all dependency
version range specifications in our package configuration.
=> Change use of ~= to >=, < in dependency version specifications

.changes/unreleased/Fixes-20240228-084335.yaml, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/test/dataflow/builder/test_dataflow_plan_builder.py, metricflow/test/query_rendering/test_fill_nulls_with_rendering.py, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_with_filters__dfp_0.xml, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/BigQuery/test_join_to_time_spine_with_filters__plan0.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/BigQuery/test_join_to_time_spine_with_filters__plan0_optimized.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Databricks/test_join_to_time_spine_with_filters__plan0.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Databricks/test_join_to_time_spine_with_filters__plan0_optimized.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/DuckDB/test_join_to_time_spine_with_filters__plan0.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/DuckDB/test_join_to_time_spine_with_filters__plan0_optimized.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Postgres/test_join_to_time_spine_with_filters__plan0.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Postgres/test_join_to_time_spine_with_filters__plan0_optimized.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Redshift/test_join_to_time_spine_with_filters__plan0.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Redshift/test_join_to_time_spine_with_filters__plan0_optimized.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Snowflake/test_join_to_time_spine_with_filters__plan0.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Snowflake/test_join_to_time_spine_with_filters__plan0_optimized.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Trino/test_join_to_time_spine_with_filters__plan0.sql, metricflow/test/snapshots/test_fill_nulls_with_rendering.py/SqlQueryPlan/Trino/test_join_to_time_spine_with_filters__plan0_optimized.sql
Resolves #1039 
Completes SL-1732
For queries using measures that join to time spine, filters were being applied before the time spine join, but not after. This means that there might be additional rows added from the time spine join that should be removed by the filters, resulting in unexpected rows in the output data. Here, we update the DataFlow Plan to apply those filters again after the time spine join, ensuring there will be no unexpected rows in the result.
Note: this means the filters are applied multiple times, which is redundant for the final output but ideally results in a more efficient query.
=> Bug fix: For measures using `join_to_timespine`, apply filters after time spine join

.changes/unreleased/Fixes-20240229-112831.yaml, metricflow/query/group_by_item/candidate_push_down/group_by_item_candidate.py, metricflow/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow/query/issues/group_by_item_resolver/no_parent_candidates.py, metricflow/test/query/group_by_item/test_matching_item_for_querying.py, metricflow/test/snapshots/test_matching_item_for_querying.py/AvailableGroupByItemsResolution/test_missing_parent_for_metric__result.txt
Due to a gap in our upstream model validation it is possible for
a user to define a derived metric with no inputs. This causes a
fall-through error to trigger of the form `unbound method
set.intersection needs an argument`.
The root cause of this is our use of the `*` operator for expanding
an iterable into a set of values. If the iterable is empty, Python
will simply pass nothing - not None, but nothing at all. This means
any call like `set.intersection(*input)` will raise this strange error
if `input` is empty.
This change does two things to resolve this issue:
1. It updates the set.intersection(*input) call to a more robust
approach, which will return an empty set if the input is empty
2. It updates the invocation to check for empty input and include
a more refined error issue …
=> Improve error message for metrics with no parents

dbt-metricflow/pyproject.toml
Due to some strange inconsitencies in how pip resolves `~=`
dependency version specifications, we are switching all of our
packages to use the more explicit `>=` and `<` notation.
=> Switch dbt-metricflow from ~= to >=/< for dependency versions

dbt-metricflow/pyproject.toml
With the release of MetricFlow 0.205.0 we can now release
dbt-metricflow 0.6.0 to complement it.
=> Update dbt-metricflow version to 0.6.0

metricflow/dag/mf_dag.py, metricflow/dataflow/dataflow_plan.py, metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/execution/execution_plan.py, metricflow/query/group_by_item/resolution_dag/resolution_nodes/measure_source_node.py, metricflow/query/group_by_item/resolution_dag/resolution_nodes/metric_resolution_node.py, metricflow/sql/sql_exprs.py, metricflow/sql/sql_plan.py, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_derived_metric_offset_to_grain__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_derived_metric_offset_window__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_derived_metric_offset_with_granularity__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_derived_offset_cumulative_metric__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_derived_metric__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_with_filters__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_with_metric_time__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_nested_derived_metric_with_outer_offset__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_to_grain_metric_filter_and_query_have_different_granularities__dfp_0.xml, metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_window_metric_filter_and_query_have_different_granularities__dfp_0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/DataflowPlan/test_join_to_time_spine_node_with_offset_to_grain__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/DataflowPlan/test_join_to_time_spine_node_with_offset_window__plan0.xml, metricflow/test/snapshots/test_dataflow_to_sql_plan.py/DataflowPlan/test_join_to_time_spine_node_without_offset__plan0.xml
The dataflow plan nodes were intended to be immutable, so this PR updates functions defined in those nodes to use sequences and tuples.
=> Make Dataflow Nodes Immutable

scripts/mf-release-helper
The MetricFlow release process is a little annoying with
updates through FOSSA (which we can hopefully replace with
easier to manage SBOM automation), changelog management,
and so forth.
This automates some of the manual bits and makes the release
PR and tagging processes less error-prone.
This is not production quality deployment code by any means,
but it's better than hand-rolling everything.
=> Add script for helping with MetricFlow releases

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/naming/naming_scheme.py, metricflow/query/group_by_item/filter_spec_resolution/filter_spec_lookup.py, metricflow/specs/patterns/spec_pattern.py, metricflow/specs/specs.py
We will need to build recursive dataflow plans for metrics as dimensions. This PR should not change any output behavior - just separates some DFP logic into a helper method that can be used to build source nodes.
=> Separate method for recursive dataflow plans

metricflow/dag/id_prefix.py, metricflow/sql/optimizer/column_pruner.py, metricflow/sql/optimizer/rewriting_sub_query_reducer.py, metricflow/sql/optimizer/sub_query_reducer.py, metricflow/sql/optimizer/table_alias_simplifier.py, metricflow/sql/render/sql_plan_renderer.py, metricflow/sql/sql_plan.py, metricflow/sql/sql_table.py, metricflow/test/dataset/test_convert_semantic_model.py, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/BigQuery/test_render_create_table_as__create_table_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/BigQuery/test_render_create_table_as__create_view_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Databricks/test_render_create_table_as__create_table_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Databricks/test_render_create_table_as__create_view_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/DuckDB/test_render_create_table_as__create_table_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/DuckDB/test_render_create_table_as__create_view_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Postgres/test_render_create_table_as__create_table_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Postgres/test_render_create_table_as__create_view_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Redshift/test_render_create_table_as__create_table_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Redshift/test_render_create_table_as__create_view_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Snowflake/test_render_create_table_as__create_table_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Snowflake/test_render_create_table_as__create_view_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Trino/test_render_create_table_as__create_table_as.sql, metricflow/test/snapshots/test_sql_plan_render.py/SqlQueryPlan/Trino/test_render_create_table_as__create_view_as.sql, metricflow/test/sql/compare_sql_plan.py, metricflow/test/sql/test_engine_specific_rendering.py, metricflow/test/sql/test_sql_plan_render.py
When generating the tasks for the execution plan, the `CREATE TABLE ... AS SELECT` statement was not generated through the SQL object model. Instead, it was generated when the associated task ran. For better consistency and to support potential SQL-engine differences, this PR adds the appropriate SQL node to model that statement. The execution task updates will be done in a separate PR.
=>  Support `CREATE TABLE ... AS SELECT` in SQL Object Model

metricflow/cli/main.py, metricflow/dag/mf_dag.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py, metricflow/dataset/dataset.py, metricflow/dataset/semantic_model_adapter.py, metricflow/dataset/sql_dataset.py, metricflow/engine/metricflow_engine.py, metricflow/execution/execution_plan.py, metricflow/model/data_warehouse_model_validator.py, metricflow/plan_conversion/convert_to_execution_plan.py, metricflow/plan_conversion/convert_to_sql_plan.py, metricflow/plan_conversion/dataflow_to_execution.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/plan_conversion/sql_join_builder.py, metricflow/query/query_resolver.py, metricflow/sql/optimizer/rewriting_sub_query_reducer.py, metricflow/test/dataflow/builder/test_cyclic_join.py, metricflow/test/dataflow/builder/test_dataflow_plan_builder.py, metricflow/test/dataflow/optimizer/source_scan/test_cm_branch_combiner.py, metricflow/test/dataflow/optimizer/source_scan/test_source_scan_optimizer.py, metricflow/test/dataset/test_convert_semantic_model.py, metricflow/test/examples/test_node_sql.py, metricflow/test/execution/test_tasks.py, metricflow/test/plan_conversion/test_dataflow_to_execution.py, metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py, metricflow/test/query/group_by_item/resolution_dag/test_resolution_dags.py, metricflow/test/query_rendering/compare_rendered_query.py, metricflow/test/snapshot_utils.py, metricflow/test/sql/compare_sql_plan.py
Once the `SqlCreateTableAs` node is available, generation of the associated statement can be done through the SQL-engine renderer instead of a one-off Jinja template in the executed task.
=> Update Execution Plan Generation to Use `SqlCreateTableAs`

metricflow/mf_logging/pretty_print.py, metricflow/test/collection_helpers/test_pretty_print.py
This PR adds an argument to `mf_pformat_many` so that for multi-line strings (e.g. rendered SQL), the log output looks cleaner.
=> Add `raw_strings` Argument to `preserve_raw_strings `

.changes/unreleased/Dependencies-20240326-145935.yaml, pyproject.toml
In order to proceed with development on using Metric inputs in
filter expressions, we need to update our dbt-semantic-interfaces
dependency to 0.5.1 or later.
This change carries some added complexity along with it, since our
dev dependencies specify dbt-core and dbt-<adapter> package
dependencies bound to dbt-core 1.7 version range. This creates
an unresolvable dependency version conflict, since dbt-core depends
on dbt-semantic-interfaces 0.4.x.
For the time being we can get away with relying on the pre-installed
dbt core + adapter packages pulled in by dbt-metricflow, and
simply allow metricflow's specification for dbt-semantic-interfaces
to override the installed package.
Most of the changes in this commit are a result of needing to manage
the dbt-semantic-interfaces version …
=> Update dbt-semantic-interfaces to 0.5.1

metricflow/naming/object_builder_scheme.py, metricflow/naming/object_builder_str.py, metricflow/query/group_by_item/filter_spec_resolution/filter_pattern_factory.py, metricflow/query/group_by_item/filter_spec_resolution/filter_spec_lookup.py, metricflow/query/group_by_item/filter_spec_resolution/filter_spec_resolver.py, metricflow/specs/patterns/typed_patterns.py, metricflow/specs/where_filter_metric.py, metricflow/specs/where_filter_transform.py, tests/model/test_where_filter_spec.py, tests/naming/conftest.py, tests/naming/test_object_builder_naming_scheme.py, tests/specs/patterns/test_entity_link_pattern.py, tests/specs/patterns/test_typed_patterns.py
Allow metrics in filters. This builds off of the changes to allow metric filters in DSI. Changes include:
- Handle group by metrics in object builder scheme
- Create new `SpecPattern` for group by metrics
- Write MF implementation of `WhereFilterMetric`
- Tests for each of the above changes
This is still not complete since the DataflowPlanBuilder does not know how to build a plan to execute a query with a metric filter, so that's coming next.
=> Allow metrics in filters

.changes/unreleased/Fixes-20240408-123954.yaml, metricflow/model/semantics/linkable_element_properties.py, metricflow/model/semantics/linkable_spec_resolver.py, tests/query_rendering/test_metric_filter_rendering.py, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_filter_by_metric_in_same_semantic_model_as_queried_metric__plan0_optimized.sql
In the initial release of Metrics as Dimensions, I overlooked some logic around local elements, resulting in a bug where you can't filter on a metric that's in the same semantic model as the metric you're querying. This fixes that!
Note that the commit `Add METRIC property to all_properties()` is duplicated in https://github.com/dbt-labs/metricflow/pull/1107, so I'll make sure to resolve any resulting merge conflicts based on whichever PR merges first.
=> Bug fix: filter by metrics in same semantic model as queried metrics

.changes/unreleased/Fixes-20240409-112145.yaml, metricflow/dataflow/builder/dataflow_plan_builder.py
Resolves SL-1954
[Users have been seeing](https://dbt-labs.slack.com/archives/C05D1MF1N4Q/p1712067795713559) "Recipe not found" errors, but they aren't likely to understand what that means. This can happen if the specs they requested are not all joinable, so we want to give them an error that makes that more clear.
=> Make recipe errors more user-friendly

.changes/unreleased/Features-20240329-182759.yaml, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/model/semantics/linkable_spec_resolver.py, tests/integration/test_cases/itest_dimensions.yaml, tests/query_rendering/test_metric_filter_rendering.py, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_distinct_values_query_with_metric_filter__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_distinct_values_query_with_metric_filter__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_distinct_values_query_with_metric_filter__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_distinct_values_query_with_metric_filter__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_distinct_values_query_with_metric_filter__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_distinct_values_query_with_metric_filter__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_distinct_values_query_with_metric_filter__plan0.sql, tests/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_distinct_values_query_with_metric_filter__plan0_optimized.sql
Completes SL-1939
Enable metric filters for distinct values queries (queries without metrics).
=> Metric filters for distinct values queries

metricflow/dataflow/dataflow_plan.py, metricflow/dataflow/nodes/filter_elements.py, metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py, metricflow/plan_conversion/dataflow_to_sql.py, tests/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
Just a quick rename! This has been bothering me for a while because it's so hard to remember the name of this method. So I've updated it to match our typical pattern, which is just snake-casing the node class name.
=> Rename node visitor method to match typical pattern

tests/integration/test_cases/itest_dimensions.yaml, tests/integration/test_cases/itest_metrics.yaml
Most engines don't require this, but several do, including
all Postgres versions prior to Postgres 16, so we should
probably keep including the subquery aliases for now.
=> Add missing aliases to integration test check queries

metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/semantic_model_lookup.py
Some small code-reducing updates that I made while working through group by resolution issues. Aiming to simplify the code so it's more readable. Easiest to review by commit.
=> Linkable Spec Tidying

metricflow/engine/metricflow_engine.py, metricflow/model/semantics/linkable_element_properties.py, metricflow/model/semantics/linkable_spec_resolver.py, metricflow/model/semantics/metric_lookup.py, metricflow/protocols/semantics.py, metricflow/query/group_by_item/candidate_push_down/push_down_visitor.py, tests/integration/configured_test_case.py, tests/integration/test_configured_cases.py, tests/model/semantics/test_linkable_spec_resolver.py, tests/model/test_semantic_model_container.py
Updates two enums to have singular names, as is conventional (and as we do with all our other enums).
`LinkableElementProperties` -> `LinkableElementProperty`
`RequiredDwEngineFeatures` -> `RequiredDwEngineFeature`
=> Give enums singular names

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/model/semantics/semantic_model_lookup.py, tests/model/test_semantic_model_container.py
Measure names are required to be unique across semantic models, so we can safely assume that `get_semantic_models_for_measure()` should return one semantic model per measure.
=> Update `get_semantic_models_for_measure` to return just one semantic model

metricflow/model/semantics/linkable_element.py, metricflow/model/semantics/linkable_element_set.py, metricflow/model/semantics/linkable_spec_resolver.py, tests/model/semantics/test_linkable_element_set.py
--------------------------------------------------------------------------------
The LinkableElementSet is a container class for a bunch of metadata-carrying
objects related to available join paths. It keys all of these objects by an
ElementPathKey, and a number of helpers for some fairly complex operations
meant to enable merging or intersecting multiple sets.
The LinkableElementSet operates under a number of underlying assumptions
which are not codified anywhere, and, indeed, there are places in the
codebase that do not conform to these assumptions.
First, the ElementPathKey is assumed to match the type of the elements
associated with it, but there is no mechanism for enforcing this, nor
is there a way to determine the element type directly from the path key
itself. This is an issue …
=> Improve robustness of LinkableElementSet operations

metricflow/model/semantics/linkable_element_set.py, tests/model/semantics/test_linkable_element_set.py
The only_unique_path_keys property in LinkableElementSet previously
did a simple length check on the value tuple for each element type,
meaning that a path key pointing to a tuple containing a lot of
duplicate elements would not be included.
This is almost certainly counter to expectation - indeed the only callsite
for this property clearly expects consolidation to a unique value.
The issue with this is some, but not all, of our LinkableElementSet
operations do distinct value filtering. For example, the merge_by_path_key
does not do such filtering, while the intersection_by_path_key does.
Furthermore, there is nothing stopping a callsite from creating a
set with duplicate elements, so this should probably apply the deduplication
on each call regardless.
This change adjusts the behavior to …
=> Make LinkableElementSet.only_unique_path_keys consider distinct values

metricflow-semantics/metricflow_semantics/query/query_parser.py, metricflow-semantics/metricflow_semantics/specs/spec_classes.py, metricflow-semantics/tests_metricflow_semantics/query/test_ambiguous_entity_path.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/source_node.py, metricflow/engine/metricflow_engine.py, scripts/ci_tests/metricflow_package_test.py, tests_metricflow/fixtures/manifest_fixtures.py
Needed to resolve the appropriate join path for multi-hop joins. Moved source node-building logic to query parser class to avoid cirular import errors. This change also required adding the query parser as a dependency for the dataflow plan builder.
This is needed to resolve the appropriate join path for multi-hop joins. Currently users won't be able to pass a join path for those, so we need to build it ourselves.
Moved source node-building logic to query parser class to avoid circular import errors. This change also required adding the query parser as a dependency for the dataflow plan builder.
This doesn't change the output of any existing tests, but I have some relevant tests coming in future PRs.
=> Use query parser to build group by metric source node

metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py, metricflow-semantics/metricflow_semantics/specs/spec_classes.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/node_evaluator.py, metricflow/dataflow/dataflow_plan.py, metricflow/dataflow/nodes/compute_metrics.py, metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py, metricflow/dataset/sql_dataset.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/plan_conversion/node_processor.py, metricflow/validation/dataflow_join_validator.py, tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
There was a lot of logic in the dataflow plan builder that assumed all source nodes and joinable nodes would be `ReadSqlSourceNode` or `MetricTimeDimensionTransformNode` (as was previously true). This is no longer true since adding `LinkableMetrics`, for which you might have a `ComputeMetricsNode` as a source node. This comes with a lot of changes, like the fact that the entity links might look different for this source node than for others. Here we update the DFP building logic to account for those nodes.
=> Update DFP join logic to account for group by metric source nodes

tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py
Test that these things actually work! This test loops through the allowed linkable metrics and runs them through the query parser & dataflow plan builder. This ensures that they will work for both group by resolution logic and dataflow plan logic.
More tests to come:
- multi-hop linkable metrics (multi-hop for both inner and outer join paths)
- e2e query tests: query rendering + check query tests
=> Test that all available single-hop metrics don't error

metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__accumulate_last_2_months_metric__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__derived_metric_with_different_parent_time_grains__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__derived_metric_with_same_parent_time_grains__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__metrics_with_different_time_grains__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__metrics_with_same_time_grains__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__no_metrics__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__simple_metric__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_derived_metrics_with_common_filtered_metric__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_filter__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_input_filter__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_valid_metric_filter__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_valid_metric_input_filter__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__accumulate_last_2_months_metric__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__derived_metric_with_different_parent_time_grains__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__derived_metric_with_same_parent_time_grains__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__metrics_with_different_time_grains__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__metrics_with_same_time_grains__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__simple_metric__result.txt
Our snapshot files rely on consistent order for all rendered
collections, but we were assuming that all input objects would
be strictly ordered. Unfortunately, the fallback method of using
Python's pretty-printer does not allow for ordered sets, so
any inputs involving set or frozenset types will be fundamentally
unstable.
This expands our list-like formatted print handling to cover set
types, indicating the distinction between set and frozenset and
printing all values in a stable sort order. This does assume all
set values are sortable, which should be the case.
As you can see from the snapshot updates, this is a pre-existing
problem in the codebase. We've gotten away with it because all of
the sets in our snapshots have, thus far, all been of length 1. This
will change in coming …
=> Add support for set type collections in the pretty-printer

metricflow-semantics/metricflow_semantics/query/group_by_item/filter_spec_resolution/filter_spec_lookup.py
The LinkableElementSet object is always present in the extant
initializer calls for FilterSpecResolution. This change allows
us to acces it without having to handle the Optional type everywhere,
and prevents future drift into mayhem as we inspect this object
for things like predicate pushdown evaluation.
=> Make LinkabelElementSet non-optional in FilterSpecResolution

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py, tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py
This reverts commit bcbf1bf6b8368506e23b2f2a4242e236eb8a9823.
The original layout of linkable_element, with the private helper
converting ElementPathKey to the relevant LinkableInstanceSpec,
was intentionally placed to avoid circular dependencies with
the WhereFilterSpec during predicate pushdown implementation.
The code configuration from the reverted commit is nicer in many
respects, but unfortunately an attempt to use it ran into
circular dependencies as expected, and the TYPE_CHECKING work-around
ultimately failed because of the way SerializableDataclass works.
Specifically, SerializableDataclass needs the class to create a concrete
object during its operation, so runtime access to the object is required
it's part of a SerializableDataclass hierarchy.
Since the SerializableDataclass …
=> Revert "Move `_path_key_to_spec` to `ElementPathKey`."

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py, metricflow-semantics/metricflow_semantics/query/group_by_item/filter_spec_resolution/filter_spec_lookup.py, metricflow-semantics/metricflow_semantics/specs/spec_classes.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
We need to access LinkableElements - or, more specifically, their
source SemanticManifestReferences - in the WhereSpecFactory in order
to evaluate fitness for predicate pushdown.
This makes these elements available to the FilterSpecResolutionLookup,
which we use to get the resolved filter elements when building the
WhereFilterSpec. Subsequent changes will plumb this through to the
WhereFilterSpec for predicate pushdown evaluation.
=> Make linkable elements available in FilterSpecResolutionLookup

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py, metricflow-semantics/metricflow_semantics/specs/rendered_spec_tracker.py, metricflow-semantics/metricflow_semantics/specs/spec_classes.py, metricflow-semantics/metricflow_semantics/specs/where_filter_dimension.py, metricflow-semantics/metricflow_semantics/specs/where_filter_entity.py, metricflow-semantics/metricflow_semantics/specs/where_filter_metric.py, metricflow-semantics/metricflow_semantics/specs/where_filter_time_dimension.py, metricflow-semantics/metricflow_semantics/specs/where_filter_transform.py, tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan_with_join__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_with_filters__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_plan__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_with_reused_measure_plan__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_to_grain_metric_filter_and_query_have_different_granularities__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_window_metric_filter_and_query_have_different_granularities__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan_time_dimension__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_with_common_linkable_plan__dfp_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfp_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfpo_0.xml
Push resolved linkable elements through to WhereFilterSpec
The resolved LinkableElements gathered during the filter spec
resolution phase of query processing need to be available to
each WhereFilterSpec so that we can determine whether or not
a given WhereFilterSpec is eligible for predicate pushdown.
This change simply adds the necessary property and wires these
elements through to where we will need to access them in the
DataflowPlanBuilder. This change proved a bit troublesome due
to the SerializableDataclass construct, which has some particular
requirements which required some slightly odd inheritance tagging.
=> Push resolved linkable elements through to WhereFilterSpec

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/specs/spec_classes.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py, metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
Update to `derived_from_semantic_models()` for `LinkableMetrics`. Previously, we were only tracking the semantic models used in the outer join path. Here, we update to add tracking for semantic models used in the inner join path and the metric itself, as well. That should fully cover all semantic models touched for these elements.
=> Track `derived_from_semantic_models` properly for `LinkableMetrics`

metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py, metricflow-semantics/tests_metricflow_semantics/__init__.py, metricflow-semantics/tests_metricflow_semantics/fixtures/setup_fixtures.py, metricflow-semantics/tests_metricflow_semantics/snapshots/__init__.py, tests_metricflow/dataflow_plan_to_svg.py, tests_metricflow/fixtures/setup_fixtures.py, tests_metricflow/snapshots/__init__.py
Instead of searching the directory hierarchy of the test file to locate the snapshot directory, this PR uses a directory anchor to configure the snapshot directory.
=> Configure snapshot directory in `SnapshotConfiguration`

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py, metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
Turns out there was a bug where we were using the wrong set of entity links in path key conversion. This fixes that!
=> Fix path key conversion bug for `LinkableMetrics`

metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py
When a test fails due to a difference in the snapshot, the current error message includes the full snapshot. In some cases, the snapshot is large, so it's hard to manage in the console. This PR changes the error messages to use a more compact form that only includes a few lines of context around the diff like:
```
FAILED tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py::test_join_to_time_spine_node_with_offset_window - AssertionError: Result does not match the stored snapshot. Diff from expected to actual:
--- Expected Result in [...]/test_join_to_time_spine_node_with_offset_window__plan0.xml
+++ Actual Result
@@ -29,7 +29,7 @@
-                        
+                        
<MetricTimeDimensionTransformNode>
```
=> Update snapshot-diff error-messages to be more compact

tests_metricflow/query_rendering/test_metric_filter_rendering.py, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_filter_with_conversion_metric__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_filter_with_conversion_metric__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_group_by_has_local_entity_prefix2__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_group_by_has_local_entity_prefix2__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_filter_with_conversion_metric__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_filter_with_conversion_metric__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_group_by_has_local_entity_prefix2__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_group_by_has_local_entity_prefix2__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_filter_with_conversion_metric__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_filter_with_conversion_metric__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_filter_with_conversion_metric__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_filter_with_conversion_metric__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_group_by_has_local_entity_prefix2__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_group_by_has_local_entity_prefix2__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_filter_with_conversion_metric__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_filter_with_conversion_metric__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_group_by_has_local_entity_prefix2__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_group_by_has_local_entity_prefix2__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_filter_with_conversion_metric__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_filter_with_conversion_metric__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_group_by_has_local_entity_prefix2__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_group_by_has_local_entity_prefix2__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_filter_with_conversion_metric__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_filter_with_conversion_metric__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_group_by_has_local_entity_prefix2__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_group_by_has_local_entity_prefix2__plan0_optimized.sql
Rendering test for a conversion metric filter.
I intended to add a check query test, too, but the SQL result turned out so complicated that it didn't seem particularly useful.
=> Test rendering for conversion metric filter

metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
Some users have run into a scenario where the entity reference can be found in the entity links for some `LinkableEntities`. I haven't yet been able to reproduce that error with our test configs. Releasing metrics as dimensions is blocked on this edge case, so I'm skipping that scenario here to ensure that customers won't run into it until when using `LinkableMetrics` until we can debug further. This will allow us to release the feature and handle this case in a follow up version.
=> Don't allow LinkableMetrics for case when entity reference is in entity links

metricflow-semantics/metricflow_semantics/naming/dunder_scheme.py, metricflow-semantics/metricflow_semantics/query/group_by_item/group_by_item_resolver.py, metricflow-semantics/metricflow_semantics/query/similarity.py, metricflow-semantics/metricflow_semantics/query/suggestion_generator.py, metricflow-semantics/metricflow_semantics/specs/patterns/no_group_by_metric.py, metricflow-semantics/metricflow_semantics/specs/patterns/none_date_part.py, metricflow-semantics/tests_metricflow_semantics/query/test_query_parser.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_defined_filters_in_multi_metric_query__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_defined_where_filter__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_metric__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_multiple_metrics__result_0.txt
Enables suggestions for `GroupByMetrics`. This just means that, if you query an invalid group by metric, the suggestion generator will show you valid group by metrics to help you figure out the right filter.
More detail is provided in commit messages / commit descriptions.
=> Query suggestions for `GroupByMetrics`

metricflow-semantics/metricflow_semantics/query/query_parser.py, metricflow-semantics/tests_metricflow_semantics/query/test_ambiguous_entity_path.py, metricflow-semantics/tests_metricflow_semantics/query/test_query_parser.py, metricflow-semantics/tests_metricflow_semantics/query/test_suggestions.py, metricflow/engine/metricflow_engine.py, scripts/ci_tests/metricflow_semantics_package_test.py, tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py, tests_metricflow/dataflow/optimizer/source_scan/test_source_scan_optimizer.py, tests_metricflow/plan_conversion/dataflow_to_sql/test_distinct_values_to_sql.py, tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py, tests_metricflow/query_rendering/test_cumulative_metric_rendering.py, tests_metricflow/query_rendering/test_derived_metric_rendering.py, tests_metricflow/query_rendering/test_fill_nulls_with_rendering.py, tests_metricflow/query_rendering/test_metric_filter_rendering.py, tests_metricflow/query_rendering/test_query_rendering.py
Similar to the parser update for saved queries, this PR updates `MetricFlowQueryParser.parse_and_validate_query()` to return a result object so that more context can be returned to the caller.
Note: `.query_spec` was added to get tests to pass in this PR. In a later PR, snapshots are used to check the parser results, so those go away.
=> Change `MetricFlowQueryParser.parse_and_validate_query()` to return `ParseQueryResult`

metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/base_node.py, metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/measure_source_node.py, metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/metric_resolution_node.py, metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/no_metrics_query_source_node.py, metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/query_resolution_node.py, metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/tests_metricflow_semantics/query/test_conversion_metrics.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_conversion_metrics.py/ParseQueryResult/test_conversion_rate_with_constant_properties__result.txt
I noticed that the `queried_semantic_models` field was not correct for conversion metrics and also for queries without any group-by-items. This PR addresses those cases.
=> Update `MetricFlowQueryResolution.queried_semantic_models` for Conversion Metrics

metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py
Logging to see if metrics as dimensions is causing major slowdowns.
=> Add logging to track latency for metrics as dimensions in query parsing

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/plan_conversion/node_processor.py
MetricFlow currently allows for a limited scope form of filter
predicate pushdown that is particular to time range constraints where
the querying user has provided an explicit time window for us to
query against. The application of the pushdown operation is managed
by threading the time range constraint through the entire dataflow
plan builder and applying the filter operation as appropriate.
This is exactly what we need to do for robust predicate pushdown
evaluation for our expanded set of pushdown operations. Rather than
wire a whole new set of parameters through, we simply encapsulate
the time range constraints inside of a new object that is more
readily extensible to other predicate pushdown handling.
This specific change is as mechanical as possible in order to minimize
confusion. …
=> Encapsulate time range constraints for predicate pushdown

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/plan_conversion/node_processor.py, tests_metricflow/dataflow/builder/test_predicate_pushdown.py
The predicate pushdown operations for time range constriants currently
rely on None/not-None state to determine whether or not to push the
ConstrainTimeRange filter node to the source. With the switch to
pushdown params this None/not-None state gets tenuous, as future
updates will need to do things like manage time range constraints,
other time dimension filters, and categorical dimension (and entity)
filters, and relying on externalizing None/not-None combinations for
these various filter types will be challenging.
This change encapsulates the enabling and disabling of time range
constraints inside of PredicatePushdownParams. At the moment, in
order to maintain the existing behavior, we simply internalize the
None/not-None behavior for time range constraints. This will also
allow us to …
=> Use pushdown params to disable time range constraint pushdown

.changes/unreleased/Under the Hood-20240516-144603.yaml, metricflow-semantics/metricflow_semantics/dag/id_prefix.py, metricflow/dataflow/dataflow_plan.py, metricflow/dataflow/nodes/read_sql_source.py, tests_metricflow/dataflow/test_dataflow_plan.py
This change ultimately adds the source_semantic_models property to
the DataflowPlan and adds a hook for enabling access to it from any
arbitrary DataflowPlanNode.
We currently have two use-cases for this, one in the cloud codebase
that needs the semantic model inputs for a dataflow plan, and the
upcoming predicate pushdown evaluation which needs the semantic model
inputs for a given DataflowPlanNode.
An earlier version of this change added the property directly to the
DataflowPlanNode, which would satisfy both use cases above. The issue
with having this property assigned directly to a DataflowPlanNode
is that the property might be considered both a node-level and graph-level
attribute, so it's not clear where to put the accessor.
The solution we came up with for this was to allow access …
=> Make source_semantic_models property accessible from a DataflowPlanNode

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/plan_conversion/node_processor.py, tests_metricflow/dataflow/builder/test_predicate_pushdown.py
Rename PredicatePushdownParameters to PredicatePushdownState
The PredicatePushdownParameters class is really a state tracking
container to help us determine whether and how to do predicate pushdown,
o we update the name to match its function.
Update pushdown_params -> pushdown_state
Straggling renames plus documentation updates
=> Rename PredicatePushdownParameters to PredicatePushdownState

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/plan_conversion/node_processor.py, tests_metricflow/dataflow/builder/test_predicate_pushdown.py
The time range constraint is our currently supported predicate pushdown
operation. The specific application of a time range constraint is
inlined in the DataflowPlanBuilder. This moves it to a more general
function, which will make it easier for us to handle other predicate
pushdown states while keeping the conditional logic contained.
Note this is effectively a no-op as the new function is currently a
pass-through. This is borne out by the lack of changes in our snapshots,
several of which cover the time range node.
=> Encapsulate time range constraint application in more general method

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
The LinkableElement interface is used in cases where we have a
set of LinkableElements undifferentiated by underlying type.
In predicate pushdown, this happens with where specs that reference
some set of linkable elements but store them in an undifferentiated
collection.
In practice, we need to know not just the object type, but the more
refined LinkableElementType in order to apply the pushdown evaluation
logic, as time dimensions and categorical dimensions need to be
considered in a distinct way.
This makes the relevant property available in the parent interface
so we can access it directly.
=> Add element type property to LinkableElement interface

.changes/unreleased/Under the Hood-20240523-155148.yaml, metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow-semantics/tests_metricflow_semantics/model/test_semantic_model_container.py, metricflow/engine/metricflow_engine.py
Completes SL-2262
Recently we've seen an increase in latency for compile time on queries. The theory is that this might be caused by the addition of `LinkableMetrics` to group by options, which may have dramatically increased the number of group by options available. Looping through them could add a lot of slowness to the query.
I added some logs to see how long those loops were taking, and looking at data from the past 24 hours, the call to `linkable_elements_for_measure` took about .1 seconds on each call for long-running queries. This could be called quite a few times for the same measure within a given query, resulting in a lot of duplicate work & unnecessary latency. To fix that, I decided to cache that method. I also cached a couple of similar methods along the way.
I tested this …
=> Cache linkable elements

metricflow/plan_conversion/dataflow_to_sql.py
Completes SL-2268
Customers have been hitting this assertion error with no context. Likely this error was added with the assumption that validations would prevent this case, but apparently that is not true. I'll also be following up on the validations to make sure that gets handled in the future.
=> Add context to `AssertionError` for derived metric `expr`

metricflow-semantics/metricflow_semantics/filters/time_constraint.py, metricflow-semantics/metricflow_semantics/query/query_parser.py, metricflow-semantics/metricflow_semantics/time/pandas_adjuster.py, metricflow-semantics/metricflow_semantics/time/time_granularity.py, metricflow-semantics/metricflow_semantics/time/time_period.py, metricflow/dataflow/builder/dataflow_plan_builder.py
This PR moves time-adjustment operations into a interface / class so that
uses of `pandas` for this purpose can be encapsulated. This will facilitate
the switch from `pandas` to `dateutil` for these time-related operations.
=> Move `pandas` time-period calls to an interface

metricflow/data_table/column_types.py, metricflow/data_table/mf_column.py, metricflow/data_table/mf_table.py, tests_metricflow/sql/compare_data_table.py, tests_metricflow/sql/test_data_table.py
This PR adds a replacement class for `pandas.Dataframe` that has the minimum functionality as required by MF. This replacement will allow removal of the `pandas` dependency later on.
=> Add replacement class for dataframes

.changes/unreleased/Features-20240530-190900.yaml, metricflow-semantics/pyproject.toml, pyproject.toml
Resolves #1065 
This adds support for Python 3.12. Once this is merged, the plan is to:
* Increment the version of MF and publish it.
* Update `dbt-metricflow` to use that new version since CI depends on that package.
* Update CI to add tests for Python 3.12.
=> Add Support for Python 3.12

extra-hatch-configuration/requirements-dev-packages.txt, extra-hatch-configuration/requirements.txt, metricflow-semantics/extra-hatch-configuration/requirements-dev-packages.txt, metricflow-semantics/extra-hatch-configuration/requirements.txt, metricflow-semantics/pyproject.toml, pyproject.toml
This PR moves dependencies for `metricflow` so that they are shared with `metricflow-semantics` and makes some updates to put them in the proper sections.
=> Update `metricflow` dependencies

metricflow-semantics/extra-hatch-configuration/requirements-dev-packages.txt, metricflow-semantics/extra-hatch-configuration/requirements.txt, pyproject.toml
With the update to Python 3.12, there a few deprecation warnings that have popped up. This PR updates packages and adds appropriate filters so that those warnings don't show up in test sessions.
=> Fix warnings that appear when running `pytest`

.github/workflows/ci-metricflow-unit-tests.yaml, Makefile, tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py, tests_metricflow/fixtures/setup_fixtures.py
This PR marks slow tests and updates the `Makefile` so that they are only run in CI.
=> Mark slow tests

tests_metricflow/query_rendering/test_metric_filter_rendering.py, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_metric_filtered_by_itself__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_metric_filtered_by_itself__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_metric_filtered_by_itself__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_metric_filtered_by_itself__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_metric_filtered_by_itself__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_metric_filtered_by_itself__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_metric_filtered_by_itself__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_metric_filtered_by_itself__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_metric_filtered_by_itself__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_metric_filtered_by_itself__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_metric_filtered_by_itself__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_metric_filtered_by_itself__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_metric_filtered_by_itself__plan0.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_metric_filtered_by_itself__plan0_optimized.sql
Very belatedly addressing some feedback about this test case! The existing case would always end up with zero rows, so this changes it to a more realistic scenario.
Context: https://github.com/dbt-labs/metricflow/pull/1162#discussion_r1588434046
=> Update funky test case

extra-hatch-configuration/requirements-sql-client-packages.txt, mypy.ini, pyproject.toml, tests_metricflow/fixtures/connection_url.py, tests_metricflow/fixtures/setup_fixtures.py, tests_metricflow/fixtures/sql_client_fixtures.py
The `SQLAlchemy` dependency is only needed because we need to parse the URL for the SQL engine configuration. Since it's relatively straightforward to parse, this PR uses built-in `urllib` to do the parsing and removes the `SQLAlchemy` dependency.
=> Remove `SQLAlchemy` dependency

.github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-metricflow-unit-tests.yaml
This PR updates a few references to Python 3.11 in the Github workflow configuration.
=> Change references to Python 3.11 -> 3.12 in Github workflows

mypy.ini, tests_metricflow/fixtures/cli_fixtures.py, tests_metricflow/integration/test_configured_cases.py
There's a fixture (poorly named, unfortunately) that contains Metricflow-engine related objects for a given manifest. This PR migrates a few tests to use that fixture.
=> Update tests to use common engine fixture

dbt-metricflow/extra-hatch-configuration/requirements-metricflow.txt, dbt-metricflow/pyproject.toml
With the release of MetricFlow 0.206.0 we can update dbt-metricflow
to reflect that dependency change and deploy the new version.
Note our build reshuffling incidentally renamed the extras to full
package names, so `pip install dbt-metricflow[postgres]` must now be
`pip install dbt-metricflow[dbt-postgres]`, which, while more typing,
does seem like an improvement since it's more obvious which package
the extra command actually installs.
To test the build, I ran the following from repo root:
```
$ cd dbt-metricflow
$ hatch build
```
From there, I created a clean venv and ran variations on pip install
commands from the local builds  and fired up the MetricFlow CLI. For example:
```
$ python -m pip install "$HOME/sources/metricflow/dbt-metricflow/dist/dbt_metricflow-0.7.0-py3-none-any.whl[dbt …
```
=> Update dbt-metricflow version to 0.7.0

dbt-metricflow/dbt_metricflow/cli/dbt_connectors/adapter_backed_client.py, dbt-metricflow/extra-hatch-configuration/requirements-cli.txt, extra-hatch-configuration/requirements.txt, metricflow-semantics/extra-hatch-configuration/requirements.txt, metricflow-semantics/metricflow_semantics/time/dateutil_adjuster.py, metricflow-semantics/metricflow_semantics/time/time_constants.py, metricflow-semantics/tests_metricflow_semantics/time/test_time_adjuster.py, metricflow/dataset/convert_semantic_model.py, metricflow/plan_conversion/time_spine.py, pyproject.toml
Primarily, this PR upgrades DSI. This is needed to get sub-daily granularity options into MF. Along the way:
- Points to the latest commit of dbt-core, which is the first commit that does not have a dependency conflict with the version of DSI we need.
- Updates various places in code affected by the upgrade.
=> Upgrade DSI to acquire sub-daily granularity options

tests_metricflow/query_rendering/test_cumulative_metric_rendering.py, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/BigQuery/test_cumulative_metric_no_window_with_time_constraint__plan0.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/BigQuery/test_cumulative_metric_no_window_with_time_constraint__plan0_optimized.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Databricks/test_cumulative_metric_no_window_with_time_constraint__plan0.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Databricks/test_cumulative_metric_no_window_with_time_constraint__plan0_optimized.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/DuckDB/test_cumulative_metric_no_window_with_time_constraint__plan0.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/DuckDB/test_cumulative_metric_no_window_with_time_constraint__plan0_optimized.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Postgres/test_cumulative_metric_no_window_with_time_constraint__plan0.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Postgres/test_cumulative_metric_no_window_with_time_constraint__plan0_optimized.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Redshift/test_cumulative_metric_no_window_with_time_constraint__plan0.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Redshift/test_cumulative_metric_no_window_with_time_constraint__plan0_optimized.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Snowflake/test_cumulative_metric_no_window_with_time_constraint__plan0.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Snowflake/test_cumulative_metric_no_window_with_time_constraint__plan0_optimized.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Trino/test_cumulative_metric_no_window_with_time_constraint__plan0.sql, tests_metricflow/snapshots/test_cumulative_metric_rendering.py/SqlQueryPlan/Trino/test_cumulative_metric_no_window_with_time_constraint__plan0_optimized.sql
This test uses a dimension that's not allowed for the metric. Updated here to use the permitted dimension. Not an issue at this point but becomes an issue when working through enabling non-default granularities for cumulative metrics.
=> Fix funky test

metricflow/plan_conversion/dataflow_to_sql.py, metricflow/sql/sql_exprs.py
There should be no behavior changes associated with this PR, only some code refactoring. This refactor was in service of:
1. Simplicity & readability. Removed some code that is no longer needed, made other pieces more DRY.
2. An upcoming change that will support multiple `agg_time_dimensions` in these functions, which is needed for enabling cumulative metrics with non-default granularities.
=> Refactor `JoinOverTimeRangeNode` SQL rendering logic

.changes/unreleased/Under the Hood-20240612-233459.yaml, metricflow/validation/data_warehouse_model_validator.py, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/BigQuery/test_build_metric_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/BigQuery/test_build_saved_query_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Databricks/test_build_metric_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Databricks/test_build_saved_query_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/DuckDB/test_build_metric_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/DuckDB/test_build_saved_query_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Postgres/test_build_metric_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Postgres/test_build_saved_query_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Redshift/test_build_metric_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Redshift/test_build_saved_query_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Snowflake/test_build_metric_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Snowflake/test_build_saved_query_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Trino/test_build_metric_tasks__query0.sql, tests_metricflow/snapshots/test_data_warehouse_tasks.py/str/Trino/test_build_saved_query_tasks__query0.sql, tests_metricflow/validation/test_data_warehouse_tasks.py
We want to add support for filtering to certain semantic models when validating measures/dimensions/entities/semantic_models, certain metrics when validating metrics, certain saved queries when validating saved queries.
Additionally, we want to add support to generating SQL for validating saved queries
Resolves SL-2375
=> Update DWH validator to include filters + saved query support

metricflow-semantics/extra-hatch-configuration/requirements.txt
We can't rely on a dev version of DSI in mantle. Since mantle depends on `metricflow-semantics`, we can't point to a dev version there.
=> Use mantle-friendly DSI deps in `metricflow-semantics`

metricflow/sql/optimizer/rewriting_sub_query_reducer.py, metricflow/sql/sql_exprs.py
When using the `WindowAggregationNode`, you will end up with a subquery that our current `SqlRewritingSubQueryReducer` thinks can be collapsed into the outer query. However, this would put window functions in the group by clause, which triggers a SQL error. This PR updates the `SqlRewritingSubQueryReducer` logic to avoid reducing in that circumstance.
=> Update optimizer to avoid putting window functions in group by

.changes/unreleased/Features-20240613-172315.yaml, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, metricflow/dataflow/builder/dataflow_plan_builder.py
When querying cumulative metrics without default granularity, build a dataflow plan that includes `WindowReaggregationNode`.
E2E tests coming soon for this feature!
=> `DataflowPlan` for cumulative metrics queried with non-default granularity

metricflow/dataflow/optimizer/source_scan/matching_linkable_specs.py
Tiny cleanup item that was previously missed.
=> Include group by metrics in `MatchingLinkableSpecsTransform`

.github/actions/setup-python-env/action.yaml
Since the files in `extra-hatch-configuration` are used to specify project dependencies, updates to those files should affect how the environment is cached in Github workflows.
=> Add `extra-hatch-configuration` to the cache config in Github workflows

.changes/unreleased/Under the Hood-20240603-170530.yaml, tests_metricflow/integration/test_cases/itest_constraints.yaml
We currently have an incomplete set of integration tests for filters
involving joins - our existing test only covers a filter against
the joined in dimension, and then implicitly discards all null values.
This change adds more robust coverage, including filters against
our current range of supported dimension join types (FULL OUTER and LEFT OUTER)
and joins allowing for NULL values on the tables that might return
NULL due to a join miss.
These tests help make some of the test coverage around predicate pushdown
operations a bit more explicit, although they are not about pushdown
specifically.
=> Add integration tests for filters against various join types

.changes/unreleased/Under the Hood-20240611-162735.yaml, metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py, tests_metricflow/query_rendering/test_predicate_pushdown_rendering.py
In order to run predicate pushdown in a more robust manner we would
be better served applying it as a post-plan-building optimizer rather
than a build-time injection of additional where constraints.
This PR adds the optimizer class with full tracking of predicate
pushdown state, but it simply returns all nodes in the input
DataflowPlan without modifying anything, since the predicate pushdown
is already applied in the DataflowPlanBuilder.
Future updates will move both the where constraint and time range constraint
pushdown operations into this optimizer class. For now we simply evaluate
the output from console logs to get a basis for future implementation changes.
=> Add PredicatePushdownOptimizer in tracking-only mode

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/nodes/where_filter.py, metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py, metricflow/plan_conversion/node_processor.py, tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
Up until now we've been merging sets of WhereFilterSpec instances
into a single instance and then storing that in the WhereConstraintNode.
This made sense for rendering, but when trying to do predicate pushdown
having the specs all merged together limits the space of filter pushdown
opporunities. In order to allow for the same breadth of predicate pushdown
opportunities we have at dataflow plan build time we keep the specs separate,
and encapsulate the merging of these specs into the WhereConstraintNode itself.
=> Store a list of input WhereFilterSpecs in the WhereConstraintNode

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/optimizer/dataflow_optimizer_factory.py, metricflow/engine/metricflow_engine.py, tests_metricflow/query_rendering/compare_rendered_query.py, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_distinct_values_query_with_metric_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_distinct_values_query_with_metric_filter__plan0_optimized.sql
In order to fully support predicate pushdown via the DataflowPlanOptimizer
framework we need two things:
1. Support for optimization in distinct values queries
2. The ability to share components between the DataflowPlanBuilder
and the PredicatePushdownOptimizer
This update addresses both of these concerns by doing a small restructure
of the DataflowPlanBuilder interface for accepting optimizers. Instead of
accepting a sequence of optimizer instances, the build_plan method will now
accept a sequence of optimization enumerations. Those will then be converted
to instances via the factory class added in this change.
From there the update to the distinct values plan method signature was
a trivial addition.
Note - snapshot updates should be limited to ID numbers due to the added
call to the …
=> Update API for requesting dataflow plan optimization

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/optimizer/dataflow_optimizer_factory.py, metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py
The PredicatePushdownOptimizer did not have access to the node
dataset resolver necessary to do the comparison between the linkable
specs referenced in the where filter and the linkable specs available
from the DataflowPlanNode targeted by predicate pushdown.
This change makes the node dataset resolver available in the optimizer.
It uses the one from the DataflowPlanBuilder in order to take advantage
of the cached resolutions available from the build process. The optimizer
is then used to evaluate the column matches in the same manner as the
original build-time pushdown evaluation.
This change was tested by running one of the predicate pushdown rendering
tests with the --log-cli-level=DEBUG confugration set, and observing the
debug output including the same entry for "Filter specs to …
=> Verify column sets match in optimizer pushdown evaluation

.changes/unreleased/Dependencies-20240624-182325.yaml, extra-hatch-configuration/requirements.txt, metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py, mypy.ini
MetricFlow has a single dependency point on pydantic but all we
use it for is our pretty printer. Since all of the objects we
pass through there are, in practice, Pydantic 1.x objects loaded
via the dsi_pydantic_shim, we simply re-use that package element
from the dbt-semantic-interfaces installation and thereby ensure
we're loading the same base model.
This build state was tested via linting (which ran on a pydantic
1.10.x install) and unit tests (which ran on a pydantic 2.7.x install).
=> Relax pydantic dependency range to allow for 2.x installs

metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py, metricflow/plan_conversion/node_processor.py
Pushdown operations for where constraints were a bit scattered
around due to the transition from build-time to optimize-time
handling. This consolidates some of the mechanics.
In particular, the where constraint pushdown state updates have
been centralized into the PredicatePushdownState object, which
allows for more streamlined updates at the callsites, and the
where spec propagation has also been simplified to allow for
all filter specs to be evaluated at once instead of splitting
the evaluation between the WhereConstraintNode and input source
node handlers.
=> Consolidate where constraint predicate pushdown management

metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py
The original implementation of the state tracker for predicate pushdown
was built around an assumption that node-level and node-path access would
be useful for propagating the application of filter predicates back
up the dependency chain.
After working towards an implementation of that logic it's clear that this
is not particularly helpful. Although this tracking is theoretically useful
for debugging scenarios the node-visit-level logging appears adequate, so we
simplify our tracking before adding additional logic.
=> Simplify predicate pushdown state tracking

metricflow/dataflow/dataflow_plan.py, metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py, tests_metricflow/dataflow/optimizer/test_predicate_pushdown_optimizer.py, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_aggregate_output_join_metric_predicate_pushdown__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_aggregate_output_join_metric_predicate_pushdown__dfpo_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_conversion_metric_predicate_pushdown__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_conversion_metric_predicate_pushdown__dfpo_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_cumulative_metric_predicate_pushdown__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_cumulative_metric_predicate_pushdown__dfpo_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_fill_nulls_time_spine_metric_predicate_pushdown__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_fill_nulls_time_spine_metric_predicate_pushdown__dfpo_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_fill_nulls_time_spine_metric_with_post_agg_join_predicate_pushdown__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_fill_nulls_time_spine_metric_with_post_agg_join_predicate_pushdown__dfpo_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_offset_metric_predicate_pushdown__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_offset_metric_predicate_pushdown__dfpo_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_simple_join_categorical_pushdown__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_simple_join_categorical_pushdown__dfpo_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_simple_join_metric_time_pushdown_with_two_targets__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_simple_join_metric_time_pushdown_with_two_targets__dfpo_0.xml
This addresses the testing gap around the cases covered by the
logic internal to the PredicatePushdownOptimizer.
It's rather difficult to hand-construct dataflow plans, so these
rely on snapshots of DataflowPlan text output for some carefully
selected queries which are known to cover the code paths in question.
=> Add direct tests for predicate pushdown optimizer

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/optimizer/dataflow_optimizer_factory.py, metricflow/engine/metricflow_engine.py, tests_metricflow/query_rendering/compare_rendered_query.py
We want to make sure optimizers are run in the same order from
all outside callers, and a subsequent change will broaden our
exposure to dbt cloud service callers. Rather than expecting
everybody to pick the "right" optimization order, we simply
accept a set of optimizations to run and order them internally.
=> Enforce order of application for DataflowPlanOptimizers

.changes/unreleased/Features-20240625-152952.yaml, metricflow/dataflow/optimizer/dataflow_optimizer_factory.py, metricflow/engine/metricflow_engine.py, tests_metricflow/query_rendering/compare_rendered_query.py
This effectively releases PredicatePushdownOptimization - the moment
this change is deployed to cloud it will be enabled.
In order to allow for a rapid mitigation of any unexpected issues this
also parameterizes the query request object to allow callers to
disable optimizations as needed. This means cloud services calling
this method can override the optimizer behaviors without requiring
an update to MetricFlow.
=> Enable PredicatePushdownOptimization for all MetricFlowEngine queries

metricflow-semantics/metricflow_semantics/specs/query_param_implementations.py
Two things:
- This error wasn't do what it was supposed to do, since it never checked if `date_part` was passed. I don't think this ever got triggered because MFS was parsing the grain from the `name` param and passing it via the `grain` param instead.
- I ran into this error in the process of trying to create consistency in the behavior of our Jinja params. Since most interfaces allow passing grain via dundered syntax, this interface is inconsistent. If we eventually want to retire the dunder syntax, we should deprecate it everywhere at once to avoid creating confusion for our users in the meantime.
=> Remove inconsistent validation for `TimeDimensionParameter`

extra-hatch-configuration/requirements.txt, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, pyproject.toml
Upgrades DSI. This is needed to upgrade DSI in MFS. MFS does not depend on DSI directly, instead relying on MF to set the DSI dependency. The DSI upgrade is needed in MFS to get [this bug fix](https://github.com/dbt-labs/dbt-semantic-interfaces/pull/309) released.
[This is the PR](https://github.com/dbt-labs/metricflow-server/pull/746) currently blocked by the upgrade.
=> Upgrade DSI

metricflow-semantics/extra-hatch-configuration/requirements.txt, metricflow-semantics/metricflow_semantics/specs/where_filter_time_dimension.py, metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
Allow users to use dunder syntax to pass granularity in where filter `TimeDimension`. Ex:
`{{ TimeDimension('metric_time__month') }} > 2020-01-01`
This behavior is currently implemented everywhere else that similar Jinja parsing happens, making this one site inconsistent. Fix that to avoid user confusion.
=> Allow passing granularity in where filter `TimeDimension` name

metricflow/plan_conversion/time_spine.py
We have not been rendering the DB name for the time spine in SQL. This has caused a bug for at least one customer, who is seeing their time spine DB ignored in the manifest, and default to a development DB instead of deployment.
=> Bug fix: use `db_name` for time spine

metricflow-semantics/metricflow_semantics/dag/dag_to_text.py, tests_metricflow/mf_logging/test_dag_to_text.py
This PR fixes a bug with how the maximum width for pretty printing was not correctly computed. Note that `SqlStringExpression(node_id=str_0 sql_expr='foo')` is longer than expected - this is due to a `__repr__` issue that will be addressed in a follow up.
=> Fix bug in line-width control in DAG pretty printer

metricflow-semantics/metricflow_semantics/mf_logging/pretty_formattable.py, metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py, metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py
There are some cases when pretty-printing or pretty-formatting an object using MF's pretty-formatter where a different representation is desired e.g. only show specific fields. This PR adds an interface that allows for such control.
=> Add an interface to override pretty-printing behavior

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py, metricflow-semantics/metricflow_semantics/query/group_by_item/group_by_item_resolver.py, metricflow-semantics/metricflow_semantics/query/query_parser.py, metricflow-semantics/metricflow_semantics/query/suggestion_generator.py, metricflow-semantics/metricflow_semantics/specs/patterns/metric_time_default_granularity.py, metricflow-semantics/metricflow_semantics/specs/patterns/min_time_grain.py, metricflow-semantics/metricflow_semantics/specs/patterns/minimum_time_grain.py
Adds a new `SpecPattern` called `MetricTimeDefaultGranularityPattern`. This will be used to apply the `default_granularity` from a queried metric to `metric_time` if no granularity is specified.
Also includes some related cleanup:
- [Rename BaseTimeGrainPattern -> MinimumTimeGrainPattern](https://github.com/dbt-labs/metricflow/commit/4bb4ab710f5d4e1fe1e43a23ad972c751427c47e)
- [Remove unused only_apply_for_metric_time param from MinimumTimeGrainPattern](https://github.com/dbt-labs/metricflow/commit/613050a3fcfce738d4ec2b028c25fb2a8d2eab7d)
=> Add `MetricTimeDefaultGranularityPattern`

extra-hatch-configuration/requirements.txt, metricflow-semantics/extra-hatch-configuration/requirements.txt, metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py
Per title. Set this property when visiting the metric node and narrow down to the max when visiting a query node.
=> Set `max_metric_default_time_granularity` property on `PushDownResult`

metricflow-semantics/metricflow_semantics/model/linkable_element_property.py
This PR updates `LinkableElementProperty.all_properties()` to iterate over the enum to make it less error prone when new properties are added.
=> Streamline `LinkableElementProperty.all_properties()`

metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py, metricflow-semantics/tests_metricflow_semantics/query/group_by_item/test_available_group_by_items.py, metricflow/dataflow/builder/dataflow_plan_builder.py, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_common_semantic_model__dfp_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_2_metrics_from_1_semantic_model__dfp_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_2_metrics_from_1_semantic_model__dfpo_0.xml
`LinkableSpecSet` depends on `InstanceSpecSet`, which leads to circular dependencies in downstream changes. This PR updates a few methods in `LinkableSpecSet` to remove that dependency.
=> Decouple `InstanceSpecSet` and `LinkableSpecSet`

metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py
`LinkableElementSet.__len__()` currently has a bug as `group_by_metric_specs` is not included. Since the current code base does not depend on that method, this PR removes it.
=> Remove `LinkableElementSet.__len__()`

metricflow/engine/models.py
We need to expose `MetricConfig` in the MFEngine so that we can grab the `meta` field now that versionless customers are on DSI 0.6.x which contains that field
=> Expose MetricConfig in MFEngine

metricflow/validation/data_warehouse_model_validator.py
Currently, in dwh validations for dimensions, we query all the dimensions in 1 query and if that fails we attempt to query each dimension one by one. However, with time dimension, we end up querying multiple variants of a singular dimension (ie., `ordered_at` expands to querying `ordered_at__week`, `ordered_at__month`, etc...), but the error message only used the element_ment. This meant in the error, we ended up seeing "duplicates", but it was actually just querying each one of those variants. With this, we should use the qualfiied name to see what we're actually querying for
=> Updated error message for validation tasks

.github/workflows/cd-push-dbt-metricflow-to-pypi.yaml, .github/workflows/cd-push-metricflow-to-pypi.yaml
We need to be able to start deploying dbt-metricflow via tags that
trigger a deployment action instead of relying on manual deployment.
This is necessary for two reasons:
1. The MetricFlow repository is evolving to allow for multiple
package deployments in distinctive ways, and each package would benefit
from a set of pre-deployment steps.
2. With the CLI now bundled with dbt-metricflow we  need a structured way
of adding and deploying patch fixes for versions that are too far
behind the current repo main branch to deploy off of main.
Therefore, this PR splits our PyPI deployment action into two separate
versions with different tag-format triggers, one for MetricFlow and
the other for dbt-metricflow. Authentication for dbt-metricflow will
be managed via PyPI's Trusted Publisher mechanism. …
=> Enable tag-based deployment for dbt-metricflow

.changes/unreleased/Features-20240725-160038.yaml, extra-hatch-configuration/requirements.txt, metricflow-semantics/extra-hatch-configuration/requirements.txt, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/node_evaluator.py, metricflow/dataflow/builder/source_node.py, metricflow/engine/metricflow_engine.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/plan_conversion/node_processor.py, metricflow/plan_conversion/time_spine.py, metricflow/validation/data_warehouse_model_validator.py, tests_metricflow/dataflow/builder/test_node_evaluator.py, tests_metricflow/fixtures/table_fixtures.py, tests_metricflow/plan_conversion/test_time_spine.py
Completes SL-2313
Consume new time spine configs and add support for using multiple time spines at different granularities.
=> Support multiple time spines using new time spine configs

.github/workflows/cd-push-metricflow-to-pypi.yaml
We have changed authentication methods for PyPI to a more secure
approach, so we no longer have to store an access token in GitHub
secrets. This removes the in-code references so we can delete
the secrets themselves.
=> Remove access token reference for PyPI

.changes/unreleased/Fixes-20240716-090114.yaml, dbt-metricflow/dbt_metricflow/cli/main.py
This PR is a backport of #1313 to dbt-metricflow 0.7.x
This will allow us to deploy @saurabh0402's fix for the following issue:
https://github.com/dbt-labs/metricflow/issues/1285
Note - efficacy was tested via the CLI by running hatch build and doing a pip install
of the build package into a clean VM, and running `mf query` with the `--csv` flag
enabled.
=> Backport: Add Column Header to the exported CSV from query command

.github/workflows/cd-push-dbt-metricflow-to-pypi.yaml, .github/workflows/cd-push-metricflow-to-pypi.yaml
In order to use Trusted Publishing we have to do some special things.
Most of these things have been abstracted away through the official
action plugin provided by the Python Packaging Authority.
This change simply conforms our actions configs with the requirements
for the plugin. Specifically, providing the `id-token: write` permission
and the target URL for publication in the relevant environment config.
=> Enable Trusted Publishing for PyPI actions

metricflow/validation/data_warehouse_model_validator.py, tests_metricflow/validation/test_data_warehouse_tasks.py
There isn't a good way to describe what the validation task is doing. This gives consumers of this the ability to expose in a description as to what task is being performed.
=> Added description to validation task for better observability

.github/workflows/cd-push-dbt-metricflow-to-pypi.yaml, .github/workflows/cd-push-metricflow-to-pypi.yaml
Backport of three PRs required to enable tag-based deployment from the 
`support/dbt-metricflow-0.7.x` branch. Specifically:
- **Enable tag-based deployment for dbt-metricflow (#1349)**
- **Remove access token reference for PyPI (#1350)**
- **Enable Trusted Publishing for PyPI actions (#1356)**
=> Backport publishing actions enabling tag deployment for dbt-metricflow

dbt-metricflow/pyproject.toml
This update will be deployed as a patch release on the 0.7.0 minor
version.
This was tested by building locally and installing the build
to run a sequence of CLI commands.
=> Update dbt-metricflow version to 0.7.1

metricflow-semantics/metricflow_semantics/query/query_parser.py
=> Cleanup: validate `min_max_only` isn't used for metric queries

.changes/unreleased/Fixes-20240821-111857.yaml, metricflow/plan_conversion/instance_converters.py
Fixes a bug that a user encountered yesterday, which triggered our alerts. This query was for a ratio metric `users_created / users_created_cumulative`, a perfectly valid metric. The input measure specs were the same, but the input measure INSTANCES had different `cumulative_descriptions` (one is cumulative and one is not).
If interested, see the alert and DD links here: https://dbt-labs.slack.com/archives/C05D1MF1N4Q/p1724196314740709
=> Bug fix: allow multiple metric input measures with the same spec

metricflow/plan_conversion/dataflow_to_sql.py
Yesterday we saw a slew of these errors, but not sure of the root cause. Adding more detail to the error log here so we can debug further.
Logs [here](https://dbtlabsmt.datadoghq.com/logs?query=service%3Ametricflow-server%20%40levelname%3AERROR%20-%22no%20child%20processes%22%20-%22server%20process%22%20-%22waiting%20for%20application%22%20-%22run-prod%5D%20terminated%22%20-%22Application%20shutdown%22%20-%22Application%20startup%22%20-%22shutting%20down%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZFyGmm4JfsmrAAAAAAAAAAYAAAAAEFaRnlHbjhPQUFDY3V5YVJsWVc3RXdCVgAAACQAAAAAMDE5MTcyMjAtMzhiZi00ODBjLWEyMWQtNGE1MmVmNTIzMjNi&fromUser=true&messageDisplay=inline&refresh_mode=paused&sort=time&source=monitor_notif&storage=hot&stream_sort=desc&viz=stream&from_ts=1724196 …
=> Improve log for better debugging

metricflow/plan_conversion/dataflow_to_sql.py
Last improvement for this log didn't actually help because the data set, when printed, does not display any of its properties. Printing the instance sets instead.
=> Improve log again

.changes/unreleased/Features-20240821-112601.yaml, metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py
There was a TODO in here to improve this logic, and it seemed pretty simple so I snagged it.
Previously, if there were aliases in any metric input measures, we would avoid trying to combine the `AggregateMeasuresNodes`. The comment clarified that the scenario we were trying to avoid was a case where different measures used the same alias. To make this more specific, I updated the logic to only skip combining nodes if duplicate aliases were found in the input measures.
=> Improve branch combining logic for `AggregateMeasuresNode`

metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/simple_manifest/saved_queries.yaml, tests_metricflow/query_rendering/test_predicate_pushdown_rendering.py, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/BigQuery/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/BigQuery/test_saved_query_with_metric_joins_and_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Databricks/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Databricks/test_saved_query_with_metric_joins_and_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/DuckDB/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/DuckDB/test_saved_query_with_metric_joins_and_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Postgres/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Postgres/test_saved_query_with_metric_joins_and_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Redshift/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Redshift/test_saved_query_with_metric_joins_and_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Snowflake/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Snowflake/test_saved_query_with_metric_joins_and_filter__plan0_optimized.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Trino/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Trino/test_saved_query_with_metric_joins_and_filter__plan0_optimized.sql, tests_metricflow/validation/test_data_warehouse_tasks.py
A customer reported problems with predicate pushdown removing
filters from certain subqueries. The scenario they were using
involved a saved query with multiple metrics and a set of filters
defined in the saved query itself.
This scenario represents a gap in our test coverage, so we add
a rendering test here. Note the test does not reproduce the
reported issue in any way, but it is useful to have for
the purposes of future development work so we add it here.
=> Add rendering test for predicate pushdown of saved query filters

extra-hatch-configuration/requirements.txt, metricflow-semantics/extra-hatch-configuration/requirements.txt, metricflow-semantics/metricflow_semantics/time/time_spine_source.py, metricflow/dataflow/builder/source_node.py, metricflow/dataset/convert_semantic_model.py, metricflow/plan_conversion/dataflow_to_sql.py, pyproject.toml, tests_metricflow/fixtures/dataflow_fixtures.py, tests_metricflow/fixtures/table_fixtures.py, tests_metricflow/plan_conversion/test_time_spine.py
Completes SL-2744
Add `custom_granularity_columns` to `TimeSpineSource`. Along the way:
- Bumped DSI version to get the new spec that includes custom granularities. Updated this in both MF and `metricflow-semantics`, since the spec was needed in both places. Now that mantle points to an older commit of MF, it should be fine to use a dev version here for now. We'll just need to update to a non-dev version if we ever need to update the commit that mantle is using.
- Updated the commit of `dbt-core` that we use for tests. This was needed to enable compatibility with DSI 0.7.0.
- Renamed old attributes that weren't specific enough to differentiate them from the new attributes.
=> Add `custom_granularity_columns` to `TimeSpineSource`

metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, metricflow-semantics/metricflow_semantics/naming/linkable_spec_name.py, metricflow-semantics/metricflow_semantics/specs/dimension_spec.py, metricflow-semantics/metricflow_semantics/specs/entity_spec.py, metricflow-semantics/metricflow_semantics/specs/measure_spec.py, metricflow-semantics/metricflow_semantics/specs/metadata_spec.py, metricflow-semantics/metricflow_semantics/specs/non_additive_dimension_spec.py, metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/plan_conversion/dataflow_to_sql.py, tests_metricflow/dataflow/builder/test_node_evaluator.py, tests_metricflow/query_rendering/test_query_rendering.py
A number of our spec classes have a `from_name` method which
wraps the StructuredLinkableSpecName.from_name method.
In the dominant majority of cases these calls are unnecessary,
and the behavior of our code would be far more clear with a targeted
set of assertions and standard dataclass initialization.
We also have a looming issue with custom granularities affecting
the way we manage granularity configurations, which will typically
require us to initialize spec classes in a context where we have
access to the properties of any custom granularity. This can't be
readily handled from within the spec classes themselves.
This change rmeoves the `from_name` methods to avoid proliferation of
unnecessary uses, and to streamline the process of moving to direct
initialization when custom …
=> Remove `from_name` methods on spec classes

metricflow-semantics/metricflow_semantics/naming/linkable_spec_name.py, metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py, metricflow-semantics/metricflow_semantics/time/granularity.py, metricflow/engine/metricflow_engine.py
MetricFlow relies on a class called StructuredLinkableSpecName to manage
conversion between structured names and their string representations,
e.g., `listing__is_lux` or `listing__created_at__month`.
Up until now the time granularity component of this naming struct
required an enumeration value, which would then be converted to its
string representation at serialization time. With custom granularities
we need to explicitly allow for a string name for the input time
granularity. This implements that change, along with some added
enforcement to ensure consistency in how we conver to/from the string
representations of these names.
=> Allow custom granularity names in string name to struct conversion

metricflow-semantics/metricflow_semantics/naming/linkable_spec_name.py
Per title - lowercase all inputs to avoid errors later.
=> Lowercase all names passed into `StructuredLinkableSpecName`

metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/metricflow_semantics/specs/patterns/match_list_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/metric_time_default_granularity.py, metricflow-semantics/metricflow_semantics/specs/patterns/metric_time_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/minimum_time_grain.py, metricflow-semantics/metricflow_semantics/specs/patterns/no_group_by_metric.py, metricflow-semantics/metricflow_semantics/specs/patterns/none_date_part.py
This PR makes pattern classes dataclass for easier comparison for equality. The comparison is helpful when memoizing / caching function calls.
=> Make pattern classes dataclasses

metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
This PR removes a `deepcopy` call that is used when fetching dimensions. The call seems unnecessary as the manifest should not be modified during a query. This call was also found to have a significant impact in performance during profiling.
=> Remove unnecessary `deepcopy` call

metricflow-semantics/metricflow_semantics/naming/dunder_scheme.py, metricflow-semantics/metricflow_semantics/naming/metric_scheme.py, metricflow-semantics/metricflow_semantics/naming/naming_scheme.py, metricflow-semantics/metricflow_semantics/naming/object_builder_scheme.py, metricflow-semantics/metricflow_semantics/protocols/query_parameter.py, metricflow-semantics/metricflow_semantics/query/query_parser.py, metricflow-semantics/metricflow_semantics/specs/query_param_implementations.py, metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py, metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py, metricflow-semantics/tests_metricflow_semantics/naming/test_dunder_naming_scheme.py, metricflow-semantics/tests_metricflow_semantics/naming/test_metric_name_scheme.py, metricflow-semantics/tests_metricflow_semantics/naming/test_object_builder_naming_scheme.py, metricflow-semantics/tests_metricflow_semantics/query/group_by_item/filter_spec_resolution/test_spec_lookup.py, metricflow-semantics/tests_metricflow_semantics/query/group_by_item/test_matching_item_for_filters.py, metricflow-semantics/tests_metricflow_semantics/query/group_by_item/test_matching_item_for_querying.py
MetricFlow's query input parameter processing runs through a
pattern matching/parsing step that then produces a parameter spec
for subsequent matching during group by resolution. In practice,
every query parameter either directly references or is derived
directly from one or more elements in a semantic manifest.
Converting a parameter into a corresponsing spec pattern for a
given query input can, therefore, benefit from access to
the semantic manifest lookup objects we provide. This will
allow us to do things like map custom granularities to their
corresponding base granularities when doing group by resolution.
This change simply makes the semantic manifest available to the
method that converts between the query input parameter and the
spec pattern. It isolates the availability of the …
=> Make SemanticManifestLookup available for spec pattern creation

metricflow-semantics/metricflow_semantics/naming/dunder_scheme.py, metricflow-semantics/metricflow_semantics/naming/object_builder_scheme.py, metricflow-semantics/metricflow_semantics/protocols/query_parameter.py, metricflow-semantics/metricflow_semantics/specs/patterns/entity_link_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py, metricflow-semantics/metricflow_semantics/specs/query_param_implementations.py, metricflow-semantics/tests_metricflow_semantics/query/test_query_parser.py, metricflow-semantics/tests_metricflow_semantics/specs/patterns/test_entity_link_pattern.py, tests_metricflow/integration/test_configured_cases.py
In preparation for supporting user-provided custom granularity names
at query time we need to update our query parameter processing
layer to use ExpandedTimeGranularities internally while accepting
string names from the original user input.
This change makes that update, although it is necessarily incomplete.
The TimeDimensionCallParameterSet, in particular, still uses an
enumeration-typed property for representing the user-requested grain,
but this interface is imported from dbt-semantic-interfaces and will
be updated in a later series of changes.
Follow-ups inside MetricFlow will enable lookups against custom granularity
values as we solidify our test layouts.
=> Switch query parameter classes onto ExpandedTimeGranularity

metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py, metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py
This PR updates `mf_pformat_many()` to return a more compact string representation.
* When possible, items are now formatted in a single line.
* Newlines between items were removed.
* Items are now formatted in an indented block.
Please see the updated tests to see what these changes look like.
=> Streamline Object Formatting in Logs

metricflow-semantics/metricflow_semantics/formatting/formatting_helpers.py, metricflow-semantics/metricflow_semantics/mf_logging/lazy_formattable.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/recorded_logging_context.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_lazy_format.py
For larger semantic models / queries, the overhead of formatting objects for logging / writing log lines can be significant. This adds a `LazyFormat` class can be used with the existing logger so that log messages at the debug level don't get formatted nor written when the configured log level would exclude it. Using this, a quick way to migrate the code base would be a replacement like the following:
```
Example:
logger.debug(f"Result is: {expensive_function()}")
->
logger.debug(LazyFormat(lambda: f"Result is: {expensive_function()}")
```
=> Add `LazyFormat` to reduce logging overhead on performance

metricflow-semantics/metricflow_semantics/time/time_spine_source.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/source_node.py, metricflow/plan_conversion/dataflow_to_sql.py
There are very few cases where multiple source nodes can satisfy the same linkable spec, but one instance in which that is the case is when `metric_time` is queried without metrics. In that case, we will use a time spine node to satisfy `metric_time`. Previously, we were choosing the time spine nodes that could support the selected grain, and then narrowing down to the one with the fewest satisfiable linkable specs. This logic was working because, before custom granularities, the time spine with the fewest satisfiable linkable specs was always the time spine with the largest compatible base granularity. With the addition of custom granularities, though, the time spine with the largest compatible base granularity might have any number of satisfiable linkable specs. This changes updates the …
=> Select appropriate time spine node for `metric_time` queries without metrics

metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow-semantics/metricflow_semantics/query/group_by_item/group_by_item_resolver.py, metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/metricflow_semantics/query/suggestion_generator.py
When the user specifies an invalid group-by item, suggestions for alternatives are shown to the user. These can be generated lazily to improve performance when there are no errors.
=> Lazily generate group-by-item candidates for suggestions

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py
This PR caches some properties of immutable classes to reduce computation overhead.
=> Cache some properties immutable properties

metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py, metricflow/dataflow/nodes/join_to_custom_granularity.py, metricflow/plan_conversion/dataflow_to_sql.py
Render SQL for custom granularities.
The `JoinToCustomGranularityNode` will build a time spine dataset and `LEFT OUTER JOIN` it to the parent dataset, without a subquery. This is done by joining the time spine table directly, instead of creating a subquery that selects from the time spine table and then joins. That makes this the first node that does not create its own subquery. This join should be safe to do without a subquery since it is always a `LEFT OUTER JOIN`, ensuring the number of rows will not be changed by the join, making it relatively safe for optimizers to handle.
This behavior was discussed with @tlento and agreed upon in order to ensure optimization and readability.
You can see examples of what this SQL will look like in a [testing …
=> Add SQL rendering logic for custom granularities

.gitignore
I've been using this filename for profiling, and putting this in `.gitignore` streamlines the git worflow.
=> Add `cprofile_output.bin` to `.gitignore`

.changes/unreleased/Features-20240827-112415.yaml, metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py, metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/node_evaluator.py, metricflow/dataflow/nodes/join_to_custom_granularity.py, metricflow/plan_conversion/dataflow_to_sql.py
Update the `DataflowPlanBuilder` to support custom granularities. Steps included:
- For each custom granularity requested, add the appropriate `JoinToCustomGranularityNode` to the `DataflowPlan`.
- When looking for nodes that can satisfy a given linkable spec, check for the ability to satisfy the spec's base granularity, not the custom granularity requested. That will be joined in later.
=> Dataflow plan for custom granularities

metricflow-semantics/metricflow_semantics/time/time_spine_source.py
This gets called when parsing a manifest in mantle, and sometimes that manifest is empty. Don't error to allow for that case.
=> Don't error for lack of time spines

metricflow-semantics/metricflow_semantics/api/v0_1/saved_query_dependency_resolver.py, metricflow-semantics/tests_metricflow_semantics/api/v0_1/test_saved_query_dependency_resolver.py
There seems to be issues with initializing `MetricflowQueryParser` with an empty manifest. This is related to recent time spine changes, but resolving that might take some time, so putting out this PR as a temporary solution.
=> Add empty manifest check for `SavedQueryDependencyResolver`

tests_metricflow/integration/test_cases/itest_granularity.yaml
Adds some check query tests for various custom granularity scenarios. I have some tasks up for other scenarios to test, but also open to more suggestions!
=> Basic check query tests for custom granularity

metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/node_evaluator.py
Based on feedback in https://github.com/dbt-labs/metricflow/pull/1409, this PR makes some updates to the dataflow plan builder. These are only refactoring changes, there should be no behavioral changes. Changes include renaming some things and simplifying the code related to converting custom granularities to base granularities in source node resolution. Reviewing by commit is recommended - full details in commit descriptions.
=> Improved source node logic for custom granularities

metricflow-semantics/metricflow_semantics/model/semantic_manifest_lookup.py, metricflow-semantics/metricflow_semantics/naming/dunder_scheme.py, metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py, metricflow/plan_conversion/dataflow_to_sql.py
Implements some small PR feedback from https://github.com/dbt-labs/metricflow/pull/1425.
=> Custom granularity cleanup

metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
The defined time granularity of a time dimension is frequently called during query resolution to figure out the time granularity for an ambiguous group-by item.
=> Cache `SemanticModelLookup.get_defined_time_granularity()`

metricflow/plan_conversion/dataflow_to_sql.py
An oversight when building this SQL rendering logic - we were dropping some of the SQL select node attributes from the dataset when joining to time spine. This fixes that.
I'm not actually sure of what query scenario might have this attributes before the custom granularity join, so this is more of a "just in case" fix.
=> Don't drop parent attributes when joining to custom granularity

metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
Similar to the previous PRs, this PR caches a few additional methods. I did a little bit of memory profiling using a large manifest, and total memory allocation did not change significantly. I believe this is because these additional caches reference objects that are already stored in `ValidLinkableSpecResolver` or the cached objects have low overhead.
=> Cache additional methods in `MetricLookup` / `SemanticModelLookup`

metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/metricflow_semantics/query/validation_rules/base_validation_rule.py, metricflow-semantics/metricflow_semantics/query/validation_rules/duplicate_metric.py, metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py, metricflow-semantics/metricflow_semantics/query/validation_rules/query_validator.py
The check in `MetricTimeQueryValidationRule` is called for every metric in a derived metric's ancestors, so this moves expensive parts of the check to only where it's needed and caches results when possible to reduce runtimes. The signature for the validation rule classes were changed, so there are a number of diff lines related to that.
=> Reduce recursive-call overhead in `MetricTimeQueryValidationRule`

metricflow-semantics/metricflow_semantics/model/semantics/element_filter.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_spec_resolver.py, metricflow-semantics/tests_metricflow_semantics/model/test_semantic_model_container.py, metricflow/engine/metricflow_engine.py
The signature of a few functions in `ValidLinkableSpecResolver` take in a few arguments that describe how to filter the returned items based on properties. To simplify the signatures and enable improved caching in a later PR, this PR groups them into the `LinkableElementFilter` class.
=> Consolidate property filters into a class

metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow-semantics/metricflow_semantics/specs/patterns/entity_link_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/no_group_by_metric.py, metricflow-semantics/metricflow_semantics/specs/patterns/spec_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py
Now that `LinkableElementFilter` is available, this PR updates `SpecPattern` to return a filter instead of a set of properties.
=> Update patterns to use `LinkableElementFilter`

metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py
This PR changes the cache for `MetricLookup.linkable_elements_for_measure()` to allow caching all measures. Memory use remained reasonable and because it's bound to `MetricLookup`, it will be GCed when a given manifest is no longer used.
=> Improve cache for `MetricLookup.linkable_elements_for_measure()`

metricflow-semantics/metricflow_semantics/model/semantics/element_filter.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow-semantics/metricflow_semantics/specs/patterns/entity_link_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py
This PR updates `LinkableElementFilter` to include the element name. This allows for more efficient filtering before a spec pattern is applied to a `LinkableElementSet`.
=> Support filtering of `LinkableElements` by element name

metricflow-semantics/metricflow_semantics/collection_helpers/lru_cache.py, metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_lru_cache.py
There is a potential memory leak when decorating class instance methods with `fuctools.lru_cache` as `fuctools.lru_cache` holds a reference to the class instance. This PR adds a LRU cache class that can be declared within the instance so that it's GCed when the instance is GCed. This will be used in later PRs to update existing caches / add new caches.
=> Add LRU cache to resolve issues with `fuctools.lru_cache`

metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py, metricflow/engine/metricflow_engine.py, metricflow/telemetry/handlers/python_log.py, metricflow/telemetry/reporter.py
This PR updates a few more log calls to use `LazyFormat`. These were previously missed due to a different signature used for logging.
=> Update more log calls to be lazy

metricflow/dataflow/builder/builder_cache.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/measure_spec_properties.py, metricflow/dataflow/builder/source_node_recipe.py, metricflow/engine/metricflow_engine.py, metricflow/plan_conversion/node_processor.py, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_2_ratio_metrics_from_1_semantic_model__dfp_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_2_ratio_metrics_from_1_semantic_model__dfpo_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_duplicate_measures__dfp_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_duplicate_measures__dfpo_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_nested_derived_metric__dfp_0.xml, tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_nested_derived_metric__dfpo_0.xml
This PR adds a few LRU caches to handle building operations within the `DataflowPlanBuilder`. Since the same metric may be used multiple times in a derived metric (or between queries), there can be significant performance improvements. Please view by commit as there were signature / type changes to making the changes cleaner.
=> Cache building operations in `DataflowPlanBuilder`

metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py
To address potential memory leaks, PR updates use cases of `functools.lru_cache` to use `LruCache`.
=> Update use cases of `fuctools.lru_cache` to use `LruCache`

Makefile, metricflow-semantics/tests_metricflow_semantics/snapshots/test_ambiguous_entity_path.py/MetricFlowQuerySpec/test_ambiguous_entity_path_resolves_to_shortest_entity_path_item__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_ambiguous_entity_path.py/MetricFlowQuerySpec/test_resolvable_ambiguous_entity_path__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_conversion_metrics.py/ParseQueryResult/test_conversion_rate_with_constant_properties__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_metric_time_granularity.py/MetricFlowQuerySpec/test_derived_metric_with_defined_metric_time_filter__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_metric_time_granularity.py/MetricFlowQuerySpec/test_derived_metric_with_defined_metric_time_filter_on_input_metric__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_metric_time_granularity.py/MetricFlowQuerySpec/test_derived_metric_with_explicit_time_granularity__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_metric_time_granularity.py/MetricFlowQuerySpec/test_derived_metric_without_explicit_time_granularity__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_metric_time_granularity.py/MetricFlowQuerySpec/test_non_metric_time_ignores_default_granularity__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_metric_time_granularity.py/MetricFlowQuerySpec/test_simple_metric_with_defined_metric_time_filter__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_metric_time_granularity.py/MetricFlowQuerySpec/test_simple_metric_with_explicit_time_granularity__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_metric_time_granularity.py/MetricFlowQuerySpec/test_simple_metric_without_explicit_time_granularity__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_cumulative_metric_agg_time_dimension_name_validation__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_derived_metric_with_offset_parsing__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_order_by_granularity_conversion__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_order_by_granularity_no_conversion__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_parse_and_validate_where_constraint_dims__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_query_parser__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_query_parser_case_insensitivity_with_names__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_query_parser_case_insensitivity_with_parameter_objects__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_query_parser_with_object_params__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_time_range_constraint_conversion__result.txt, tests_metricflow/generate_snapshots.py
After merging https://github.com/dbt-labs/metricflow/pull/1452, seems like snapshots in MF-semantics were missing (CI still passed - odd). But updated those and also updated the script to update snapshots in MF semantics as that seems to be missing.
=> Fix missing snapshots

metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py
Missed this earlier, but `MetricTimeQueryValidationRule` holds a reference to `SemanticModelLookup` / `MetricLookup` indirectly because it holds a reference to `SemanticManifestLookup`. Since those objects can be large, this PR changes the cache in `MetricTimeQueryValidationRule` to `LruCache` so that those objects are garbage-collected properly.
=> Change cache in `MetricTimeQueryValidationRule` to `LruCache`

metricflow-semantics/metricflow_semantics/sql/sql_table.py, metricflow-semantics/metricflow_semantics/time/time_spine_source.py, metricflow-semantics/tests_metricflow_semantics/sql/test_sql_table.py, metricflow/sql/sql_column.py
This PR makes `SqlTable.schema_name` optional as `SqlTable` can later be used to reference a CTE, which does not have a schema name.
=> Make `SqlTable.schema_name` optional

metricflow-semantics/metricflow_semantics/specs/where_filter/where_filter_spec.py, metricflow-semantics/metricflow_semantics/sql/sql_bind_parameters.py, metricflow/sql/render/expr_renderer.py, metricflow/sql/render/sql_plan_renderer.py, metricflow/sql/render/trino.py, tests_metricflow/sql_clients/test_sql_client.py
`SqlBindParameterSet` implements `combine()`, which is similar to the interface for `Mergeable` objects. This PR updates `SqlBindParameterSet` to be a subclass of `Mergeable` for consistency and the ability to use convenience methods for `Mergeable` objects in later PRs.
=> Implement `Mergeable` for `SqlBindParameterSet`

metricflow/sql/render/sql_plan_renderer.py
* This PR regularizes the handling of different sections in `DefaultSqlQueryPlanRenderer.visit_select_statement_node` to have a consistent pattern for the different sections. 
* Each section calls a separate method to render that section, and each of those methods return the same result object. 
* There are no significant logic changes.
* This makes it cleaner to add the rendering for CTEs in a later PR.
=> Regularize select statement rendering

metricflow-semantics/metricflow_semantics/dag/sequential_id.py, metricflow-semantics/metricflow_semantics/test_helpers/id_helpers.py, tests_metricflow/fixtures/manifest_fixtures.py
This moves `patch_id_generators_helper` to be a method of `SequentialIdGenerator` so that it's more obvious that the patching is happening. Note that in a later PR, the patching is removed and replaced with a stack, but the placement is still helpful.
=> Move `patch_id_generators_helper` to `SequentialIdGenerator`

.changes/unreleased/Fixes-20241021-120748.yaml, metricflow-semantics/metricflow_semantics/dag/sequential_id.py, metricflow-semantics/metricflow_semantics/test_helpers/id_helpers.py, metricflow-semantics/tests_metricflow_semantics/conftest.py, tests_metricflow/conftest.py, tests_metricflow/engine/test_explain.py, tests_metricflow/fixtures/manifest_fixtures.py
Resolves #1473 
While there is currently a lock for ID generation, it is not thread-safe as the start value of ID values can be modified by different threads. e.g. thread A starts generating IDs, thread B resets the ID generation start value, thread A repeats IDs.
This PR:
* Adds a test to verify consistent ID generation for SQL with multiple threads.
* Changes the ID generator to use thread-local state.
* Removes patching of state and replaces it with an explicit stack.
* Assorted organizational / naming changes.
=> Make ID generation thread-safe

.changes/unreleased/Breaking Changes-20241021-115548.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, metricflow-semantics/pyproject.toml, pyproject.toml
=> Update dependencies to require Python `>=3.9`

metricflow-semantics/metricflow_semantics/dag/id_prefix.py, metricflow/sql/optimizer/column_pruner.py, metricflow/sql/optimizer/rewriting_sub_query_reducer.py, metricflow/sql/optimizer/sub_query_reducer.py, metricflow/sql/optimizer/table_alias_simplifier.py, metricflow/sql/render/sql_plan_renderer.py, metricflow/sql/sql_plan.py, tests_metricflow/snapshots/test_render_cte.py/SqlQueryPlan/test_render_cte__plan_0.sql, tests_metricflow/sql/test_render_cte.py
* This PR adds classes to represent CTEs to the SQL object model.
* CTEs will be used in later PRs to simplify generated queries.
* Functionality to render CTEs is included, and existing code should not hit the CTE use cases so many methods were left unimplemented.
=> Add classes to represent CTEs

metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/metricflow_semantics/query/validation_rules/base_validation_rule.py, metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py
This PR update the initializer for query-validation rules to include the resolved group-by items. This allows for more efficient validation in a later PR.
=> Provide resolved group-by-items to query-validation rules

metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/metricflow_semantics/query/validation_rules/base_validation_rule.py, metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py
To improve readability / shorten methods, this PR splits the case handling for different metrics types in `MetricTimeQueryValidationRule`.
=> Split case handling for different metric types in `MetricTimeQueryValidationRule`

metricflow-semantics/metricflow_semantics/query/validation_rules/base_validation_rule.py, metricflow-semantics/metricflow_semantics/query/validation_rules/duplicate_metric.py, metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py, metricflow-semantics/metricflow_semantics/query/validation_rules/query_validator.py
This PR updates the signature of the `PostResolutionQueryValidationRule` to allow for query validation on a per-measure basis. This allows for simpler validation for checks that depend on a measure as used in a later PR.
=> Add per-measure validation in query validation rules

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py, metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/str/test_join_through_scd_no_time_dimension_validation__error.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/str/test_join_to_scd_no_time_dimension_validation__error.txt
This PR improves the performance of `MetricTimeQueryValidationRule`. One of the reasons for the slow performance is that it currently makes calls to `get_joinable_scd_specs_for_metric`, which can be slow with large manifests. Instead, this runs checks based on the resolved group-by-items, which is a much smaller set.
=> Improve performance of `MetricTimeQueryValidationRule`

metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/extended_date_manifest/metrics/monthly_bookings_to_daily_bookings_ratio.yaml, metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/extended_date_manifest/semantic_models/bookings_monthly_source.yaml, metricflow-semantics/tests_metricflow_semantics/fixtures/manifest_fixtures.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_metric_lookup.py, tests_metricflow/integration/test_cases/itest_cumulative_metric.yaml, tests_metricflow/integration/test_cases/itest_dimensions.yaml, tests_metricflow/query_rendering/test_cumulative_metric_rendering.py, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_derived_metric_with_month_dimension_and_offset_window__plan0.sql, tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_derived_metric_with_month_dimension_and_offset_window__plan0_optimized.sql
This PR adds a test case to illustrate a bug with `MetricLookup.get_min_queryable_time_granularity()`. A fix for this test case is provided in a later PR.
=> Add test for bug with `get_min_queryable_time_granularity`

metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_helper.py, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, metricflow/dataset/convert_semantic_model.py, metricflow/engine/metricflow_engine.py
`SemanticModelLookup` has gotten large and unwieldy, both in terms of code and state. This has complicated prior performance improvement work. As a first step to breaking up the class, this PR moves the static methods to a separate helper class.
=> Move static methods to `SemanticModelHelper`

metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_helper.py, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, metricflow/engine/metricflow_engine.py
The helper method `resolved_primary_entity` gets the primary entity in a semantic model. Since semantic models with a measure or a dimension should have a primary entity (enforced by validations), this PR changes that method to raise an exception if one does not exist instead of returning `None`. `get_primary_entity_else_error` is also removed since it becomes redundant.
=> Change `resolved_primary_entity` helper signature

metricflow-semantics/metricflow_semantics/model/semantics/dimension_lookup.py, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_dimension_lookup.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_dimension_lookup.py/dict/test_get_invariant__obj_0.txt, metricflow/dataflow/builder/partitions.py
Similar to https://github.com/dbt-labs/metricflow/pull/1486, this PR creates a lookup class for dimensions. This also replaces calls to the broken `get_dimension()` method, which will be removed in a later PR.
=> Add `DimensionLookup` to break-up `SemanticModelLookup`

metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_metric_lookup.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/measure_spec_properties.py, tests_metricflow/integration/test_cases/itest_dimensions.yaml
This PR fixes a bug with `get_defined_time_granularity()` as demonstrated in https://github.com/dbt-labs/metricflow/pull/1482.
This also changes the signature of `DataflowPlanBuilder.__get_required_and_extraneous_linkable_specs()` to pass in a more complete object (`measure_spec_properties`) so that a call to `get_defined_time_granularity()` is not required.
=> Fix Bug with `get_defined_time_granularity()`

metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, metricflow-semantics/metricflow_semantics/naming/linkable_spec_name.py, metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py, metricflow-semantics/metricflow_semantics/specs/query_param_implementations.py, metricflow-semantics/metricflow_semantics/specs/where_filter/where_filter_time_dimension.py, metricflow-semantics/metricflow_semantics/specs/where_filter/where_filter_transform.py, metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/engine/metricflow_engine.py, metricflow/engine/models.py
With the addition of custom granularities, when we parse the dundered names via `LinkableSpecName.from_name`, we need to be able to know whether the grain provided is a custom grain. This means we need to pass that information through to this classmethod.
Resolves SL-2971
=> Update `LinkableSpecName.from_name` to parse custom grains

metricflow/dataflow/builder/dataflow_plan_builder.py, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_dimensions_with_time_constraint__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan_with_join__dfp_0.xml, tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_metric_time_with_other_dimensions__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_conversion_metric_predicate_pushdown__dfp_0.xml, tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_conversion_metric_predicate_pushdown__dfpo_0.xml
Dedupe logic in the `DataflowPlanBuilder`. Diverging paths in the dataflow plan have frequently been a source of bugs. To reduce similar future bugs, this PR unifies some of the logic across all paths. There are several steps we always take after source node generation and before aggregation. This PR moves all that logic into a helper function to ensure we always use the same logic.
=> Align dataflow plans

metricflow-semantics/metricflow_semantics/dag/mf_dag.py, metricflow/dataflow/dataflow_plan.py, metricflow/dataflow/nodes/add_generated_uuid.py, metricflow/dataflow/nodes/aggregate_measures.py, metricflow/dataflow/nodes/combine_aggregated_outputs.py, metricflow/dataflow/nodes/compute_metrics.py, metricflow/dataflow/nodes/constrain_time.py, metricflow/dataflow/nodes/filter_elements.py, metricflow/dataflow/nodes/join_conversion_events.py, metricflow/dataflow/nodes/join_over_time.py, metricflow/dataflow/nodes/join_to_base.py, metricflow/dataflow/nodes/join_to_custom_granularity.py, metricflow/dataflow/nodes/join_to_time_spine.py, metricflow/dataflow/nodes/metric_time_transform.py, metricflow/dataflow/nodes/min_max.py, metricflow/dataflow/nodes/order_by_limit.py, metricflow/dataflow/nodes/read_sql_source.py, metricflow/dataflow/nodes/semi_additive_join.py, metricflow/dataflow/nodes/where_filter.py, metricflow/dataflow/nodes/window_reaggregation_node.py, metricflow/dataflow/nodes/write_to_data_table.py, metricflow/dataflow/nodes/write_to_table.py, metricflow/sql/sql_exprs.py, metricflow/sql/sql_plan.py
This sets `eq=False` for node dataclasses as nodes should be unique, and equivalence methods should be used for checking as the nodes represent recursive data structures. Without this, comparisons or using nodes as keys can be slow as the generated equals function will traverse the recursive structure.
=> Add `eq=False` to node classes

metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_snapshot.py/str/test_expectation_description__result.txt, metricflow-semantics/tests_metricflow_semantics/test_snapshot.py, tests_metricflow/snapshot_utils.py
To make snapshot files easier to review, this PR adds an `expectation_description` field to the headers. This way,  reviewers can read the description to check that the snapshot contains the expected result. The field was named `expectation_description` instead of `expectation` to make it more clear that it's supposed to be human-readable text vs. a specific value in the snapshot.
=> Support expectations in snapshot files

metricflow/sql/render/sql_plan_renderer.py, metricflow/sql/sql_plan.py
This removes `SqlQueryPlanNode.is_table` and replaces it with a typed accessor for parallelism with `as_select_node`. This is helpful in handling some use cases for CTEs.
=> Replace `is_table` with `as_sql_table_node`

metricflow/plan_conversion/dataflow_to_sql.py, metricflow/sql/optimizer/column_pruner.py, metricflow/sql/optimizer/tag_required_column_aliases.py, metricflow/sql/sql_plan.py, tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_multi_child_pruning__result.txt, tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_nested_pruning__result.txt, tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_no_pruning__result.txt, tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_simple_pruning__result.txt, tests_metricflow/sql/optimizer/check_optimizer.py, tests_metricflow/sql/optimizer/test_cte_column_pruner.py
This updates the column pruner optimizer to support CTEs. To support CTEs, the required columns are mapped to the corresponding CTE and propagated like other parent nodes.
=> Support CTEs in the column pruner

metricflow/sql/optimizer/rewriting_sub_query_reducer.py, metricflow/sql/optimizer/tag_required_column_aliases.py, tests_metricflow/snapshots/test_cte_rewriting_sub_query_reducer.py/str/test_reduce_cte__result.txt, tests_metricflow/snapshots/test_cte_rewriting_sub_query_reducer.py/str/test_reduce_cte_with_use_column_alias_in_group_bys__result.txt, tests_metricflow/snapshots/test_rewriting_sub_query_reducer.py/SqlQueryPlan/test_reducing_join_statement__after_reducing.sql, tests_metricflow/snapshots/test_rewriting_sub_query_reducer.py/SqlQueryPlan/test_reducing_join_statement__before_reducing.sql, tests_metricflow/sql/optimizer/test_cte_rewriting_sub_query_reducer.py, tests_metricflow/sql/optimizer/test_rewriting_sub_query_reducer.py
This updates the sub-query reducer to support CTEs. The `SELECT` statement in each CTE is treated like a `SELECT`, and all CTEs are retained. i.e. a CTE is not reduced with another CTE. The CTEs are retained to make mapping to dataflow plan nodes easier in later PRs.
=> Support CTEs in sub-query reducer

metricflow/sql/optimizer/table_alias_simplifier.py, tests_metricflow/snapshots/test_cte_table_alias_simplifier.py/str/test_table_alias_no_simplification__result.txt, tests_metricflow/snapshots/test_cte_table_alias_simplifier.py/str/test_table_alias_simplification__result.txt, tests_metricflow/snapshots/test_table_alias_simplifier.py/SqlQueryPlan/test_table_alias_simplification__after_alias_simplification.sql, tests_metricflow/snapshots/test_table_alias_simplifier.py/SqlQueryPlan/test_table_alias_simplification__before_alias_simplification.sql, tests_metricflow/sql/optimizer/test_cte_table_alias_simplifier.py, tests_metricflow/sql/optimizer/test_table_alias_simplifier.py
Similar to the updates for the other optimizers in https://github.com/dbt-labs/metricflow/pull/1503 and https://github.com/dbt-labs/metricflow/pull/1504, this PR implements the CTE case for the `SqlTableAliasSimplifier`
=> Update `SqlTableAliasSimplifier` to handle CTEs

metricflow/dataflow/builder/node_data_set.py, metricflow/plan_conversion/dataflow_to_sql.py
This PR splits off the part that does the dataflow traversal in `DataflowToSqlQueryPlanConverter` into a separate class to reduce the class size. Later, these two parts can be put into different files.
=> Split traversal component from `DataflowToSqlQueryPlanConverter`

metricflow-semantics/metricflow_semantics/mf_logging/lazy_formattable.py, metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py, metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py, metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py, metricflow/data_table/mf_table.py, metricflow/dataflow/builder/node_data_set.py, metricflow/dataset/sql_dataset.py, metricflow/plan_conversion/dataflow_to_sql.py, tests_metricflow/sql/compare_data_table.py, tests_metricflow/sql/compare_sql_plan.py
This PR contains an assortment of updates related to logging / formatting. Although not really related, since they were small, they were put into a single PR. Please view by commit.
=> Assorted formatting / logging updates

metricflow-semantics/metricflow_semantics/dag/mf_dag.py, metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py, metricflow-semantics/metricflow_semantics/visitor.py, metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py, metricflow/dataflow/dataflow_plan.py, metricflow/dataflow/dataflow_plan_analyzer.py, metricflow/dataflow/dataflow_plan_visitor.py, tests_metricflow/snapshots/test_common_dataflow_branches.py/str/test_shared_metric_query__result.txt, tests_metricflow/sql/test_common_dataflow_branches.py
This PR adds a method to figure out nodes in a dataflow plan that appear more than once. i.e. a node that is the parent of multiple nodes. These common nodes indicate operations where a computation is reused, e.g. a metric that is used in the computation of multiple derived metrics in a query. These nodes will be later used to generate CTEs.
=> Add a method to figure out common nodes in a dataflow plan

metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/builder/node_evaluator.py, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/BigQuery/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/BigQuery/test_skipped_pushdown__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Databricks/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Databricks/test_skipped_pushdown__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/DuckDB/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/DuckDB/test_skipped_pushdown__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Postgres/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Postgres/test_skipped_pushdown__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Redshift/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Redshift/test_skipped_pushdown__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Snowflake/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Snowflake/test_skipped_pushdown__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Trino/test_saved_query_with_metric_joins_and_filter__plan0.sql, tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Trino/test_skipped_pushdown__plan0.sql
The difference between `queried_linkable_specs`, `required_linkable_specs`, and `extraneous_linkable_specs` has often been overlooked and therefore been the source of many bugs. In [this PR](https://github.com/dbt-labs/metricflow/pull/1506), we removed the unneeded `FilterElementsNodes` that were the main reason we needed those different spec variables. So now we can remove the `extraneous_linkable_specs` variables altogether, and hopefully reduce confusion here.
There is also some related cleanup in here. It's not a huge PR but I still recommend reviewing by commit.
=> Cleanup: Remove `extraneous_linkable_specs`

metricflow-semantics/metricflow_semantics/naming/object_builder_str.py, metricflow-semantics/tests_metricflow_semantics/naming/test_object_builder_naming_scheme.py
`ObjectBuilderNamingScheme.input_str()` is supposed to return `None` if the there is no valid input string for the given spec, but it currently raises an exception. This PR fixes that case.
=> Handle invalid case for `ObjectBuilderNamingScheme.input_str()`

metricflow-semantics/metricflow_semantics/instances.py, metricflow/dataset/sql_dataset.py, metricflow/plan_conversion/dataflow_to_sql.py
Clean up. Just reducing some repeated code in dataflow to SQL logic.
=> Use helper function to find matching instances in dataset

metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py, metricflow/dataflow/builder/dataflow_plan_builder.py
Clean up.
1. Rename default grain -> min grain. This was causing me some confusion because we recently introduced the concept of default grain for metrics, which is defined in the YAML spec, but this code was not referring to that.
2. Also moves some related logic to helper functions to improve readability.
=> Minimum grain clean up

metricflow/dataflow/nodes/join_over_time.py, metricflow/dataset/sql_dataset.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/plan_conversion/instance_converters.py, metricflow/plan_conversion/sql_join_builder.py
There should be no functional changes in this commit, only cleanup and readability improvements. Mostly involves moving complex logic to helper functions.
=> Simplify dataflow to SQL logic for `JoinOverTimeRangeNode`

.changes/unreleased/Features-20241210-172725.yaml, metricflow/engine/models.py
Adds tags to saved queries.  This is modeled off of [this](https://github.com/dbt-labs/metricflow/pull/1334/files) PR.
=> Add tags to SavedQueries

tests_metricflow/fixtures/setup_fixtures.py, tests_metricflow/test_pytest_markers.py
This PR adds a `pytest` marker that allows tests to only be run when testing using DuckDB. This is useful in integration test cases where engine-specific SQL rendering is not being tested. This can help to reduce test suite runtimes and to reduce the number of snapshots.
=> Add marker for DuckDb-only tests

metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py, metricflow/sql/optimizer/optimization_levels.py, tests_metricflow/engine/test_explain.py, tests_metricflow/integration/test_mf_engine.py, tests_metricflow/snapshot_utils.py, tests_metricflow/snapshots/test_explain.py/str/test_optimization_level__result.txt
This PR adds an improved test to show that the SQL optimization level in the request is handled correctly in the MF engine API. The previous test made a more general check, but a snapshot helps to check for specific features. Considering adding an assertion for the snapshot as well.
=> Add improved test for the SQL optimization level in the request

tests_metricflow/generate_snapshots.py, tests_metricflow/populate_persistent_source_schemas.py
This PR renames `MetricFlowTestConfiguration` in `tests_metricflow/generate_snapshots.py` as it conflicts with another class in the codebase.
=> Rename `MetricFlowTestConfiguration` in snapshot-generation script

tests_metricflow/fixtures/manifest_fixtures.py, tests_metricflow/generate_snapshots.py, tests_metricflow/populate_persistent_source_schemas.py
=> Fix argument name in `_create_data_sets`

metricflow/plan_conversion/dataflow_to_sql.py
In case there are issues with the SQL optimizers, this PR adds a mechanism to retry generation using a lower optimization level to potentially reduce user-facing errors.
=> Add retries for SQL generation using lower optimization levels

metricflow/sql/optimizer/rewriting_sub_query_reducer.py, metricflow/sql/optimizer/tag_required_column_aliases.py, metricflow/sql/sql_exprs.py
This PR implements `Mergeable` for `SqlExpressionTreeLineage` to reuse code available in `Mergeable`.
=> Implement `Mergeable` for `SqlExpressionTreeLineage`

dbt-metricflow/dbt_metricflow/cli/main.py, metricflow/engine/metricflow_engine.py, metricflow/execution/dataflow_to_execution.py, metricflow/execution/execution_plan.py, metricflow/validation/data_warehouse_model_validator.py, tests_metricflow/engine/test_explain.py, tests_metricflow/execution/noop_task.py, tests_metricflow/execution/test_tasks.py, tests_metricflow/integration/test_rendered_query.py, tests_metricflow/plan_conversion/test_dataflow_to_execution.py, tests_metricflow/snapshots/test_dataflow_to_execution.py/ExecutionPlan/DuckDB/test_combined_metrics_plan__ep_0.xml, tests_metricflow/snapshots/test_dataflow_to_execution.py/ExecutionPlan/DuckDB/test_joined_plan__ep_0.xml, tests_metricflow/snapshots/test_dataflow_to_execution.py/ExecutionPlan/DuckDB/test_multihop_joined_plan__ep_0.xml, tests_metricflow/snapshots/test_dataflow_to_execution.py/ExecutionPlan/DuckDB/test_small_combined_metrics_plan__ep_0.xml
This PR renames `SqlQuery` to `SqlStatement` since it can now contain "CREATE TABLE ... AS ..." instead of just a `SELECT ...`. This also makes some renames / updates to code referring to `sql_query`.
=> Rename `SqlQuery` to `SqlStatement`

metricflow-semantics/metricflow_semantics/instances.py, metricflow-semantics/metricflow_semantics/specs/dunder_column_association_resolver.py, metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py, metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py, metricflow-semantics/tests_metricflow_semantics/fixtures/manifest_fixtures.py, metricflow/dataflow/nodes/filter_elements.py, metricflow/engine/metricflow_engine.py, metricflow/validation/data_warehouse_model_validator.py, scripts/ci_tests/metricflow_package_test.py, tests_metricflow/dataflow/builder/test_node_data_set.py, tests_metricflow/dataflow/builder/test_node_evaluator.py, tests_metricflow/examples/test_node_sql.py, tests_metricflow/fixtures/manifest_fixtures.py, tests_metricflow/integration/conftest.py, tests_metricflow/integration/test_rendered_query.py, tests_metricflow/plan_conversion/instance_converters/test_create_select_columns_with_measures_aggregated.py, tests_metricflow/plan_conversion/test_dataflow_to_execution.py
And related cleanup. This will allow us to track which specs have had a window function applied between DataflowPlan nodes, which is needed for the dataflow plan used for custom offset windows.
=> Add `window_function` attribute to `TimeDimensionSpec`

metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/metricflow_semantics/sql/sql_exprs.py, metricflow/sql/optimizer/rewriting_sub_query_reducer.py, tests_metricflow/integration/query_output/test_query_output.py, tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_derived_metric_alias__plan0.sql, tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_derived_metric_alias__plan0_optimized.sql, tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_metric_alias__plan0.sql, tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_metric_alias__plan0_optimized.sql
Previously, when applying the `SqlRewritingSubQueryReducer`, we would allow the child order bys to overwrite the parent order bys. This was never a problem because order bys were only present in the outermost SQL query (due to our existing dataflow plans). With the recent change to allow metric aliases, order bys may now be in a parent subquery. This revealed the bug in which they were being erased. This PR fixes that issue.
=> Bug fix: don't erase order by for metric alias query

metricflow-semantics/metricflow_semantics/collection_helpers/lru_cache.py, metricflow-semantics/metricflow_semantics/naming/linkable_spec_name.py, metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py, metricflow-semantics/metricflow_semantics/time/granularity.py, metricflow-semantics/metricflow_semantics/time/time_spine_source.py
There is an issue with mypy when using the `@lru_cache` decorator that causes function parameters to not be type-checked. For the most part, we're migrating MF to use our custom `LruCache` class, but for those cases where we still use the decorator (or until we migrate all of them to the new class), this ensures they will be type checked.
=> Restore type checking for functions decorated with `@lru_cache`

metricflow-semantics/metricflow_semantics/naming/metric_scheme.py, metricflow-semantics/metricflow_semantics/query/query_resolver.py, metricflow-semantics/metricflow_semantics/query/resolver_inputs/query_resolver_inputs.py, metricflow-semantics/metricflow_semantics/specs/patterns/entity_link_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/metric_pattern.py, metricflow-semantics/metricflow_semantics/specs/query_param_implementations.py
This addresses [some feedback](https://github.com/dbt-labs/metricflow/pull/1573#pullrequestreview-2518180663) that did not get addressed before merging [this PR](https://github.com/dbt-labs/metricflow/pull/1573) - specifically:
> Since the alias in this case is describing user inputs, can it be added as a field to ResolverInputForMetric?
=> Move metric alias details from `MetricSpecPattern` to `ResolverInputForMetric`

.changes/unreleased/Fixes-20250116-124630.yaml, metricflow/engine/metricflow_engine.py
This method constructs its response with `__ini__` where others use `from_pydantic`. So, this field has to be added manually so that it MFS can gain access to it.
=> Add config to get_measures_for_metrics response

.github/workflows/cd-push-dbt-metricflow-to-pypi.yaml, .github/workflows/cd-push-metricflow-to-pypi.yaml, .github/workflows/cd-sql-engine-populate-persistent-source-schema.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-linting.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, .pre-commit-config.yaml
This PR adds [actionlint](https://github.com/rhysd/actionlint/) to our pre-commit hooks. It will run whenever something has changed under `.github/workflows/`.
As the name suggests, actionlint is a Github Actions file linter, and it checks for things such as non-conformance to the YAML schema, referencing non-existing steps/outputs or running some security audits. It also runs [shellcheck](https://github.com/koalaman/shellcheck) to ensure the shell scripts in our actions files have no glaring issues.
After adding actionlint, I ran it over the entire repo to fix the issues it found with our actions.
You can review by commit.
=> Add `actionlint` to pre-commit hooks

metricflow-semantics/metricflow_semantics/dag/id_prefix.py, metricflow/engine/metricflow_engine.py, metricflow/execution/dataflow_to_execution.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/sql/optimizer/optimization_levels.py, metricflow/sql/sql_plan.py, metricflow/validation/data_warehouse_model_validator.py, tests_metricflow/engine/test_explain.py, tests_metricflow/examples/test_node_sql.py, tests_metricflow/plan_conversion/dataflow_to_sql/test_cte_sql.py, tests_metricflow/plan_conversion/test_dataflow_to_execution.py, tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py, tests_metricflow/query_rendering/compare_rendered_query.py, tests_metricflow/snapshots/test_explain.py/str/test_optimization_level__result.txt
This PR renames a few symbols related to the recent rename from `SqlQueryPlan` to `SqlPlan`.
=> Renames related to `SqlPlan` - Part 2

dbt-metricflow/dbt_metricflow/cli/dbt_connectors/adapter_backed_client.py, metricflow/engine/metricflow_engine.py, metricflow/execution/dataflow_to_execution.py, metricflow/protocols/sql_client.py, metricflow/sql/render/big_query.py, metricflow/sql/render/databricks.py, metricflow/sql/render/duckdb_renderer.py, metricflow/sql/render/postgres.py, metricflow/sql/render/redshift.py, metricflow/sql/render/snowflake.py, metricflow/sql/render/sql_plan_renderer.py, metricflow/sql/render/trino.py, metricflow/validation/data_warehouse_model_validator.py, tests_metricflow/examples/test_node_sql.py, tests_metricflow/fixtures/sql_clients/adapter_backed_ddl_client.py, tests_metricflow/fixtures/sql_fixtures.py, tests_metricflow/integration/query_output/test_cumulative_metrics.py, tests_metricflow/integration/test_configured_cases.py, tests_metricflow/plan_conversion/dataflow_to_sql/test_cte_sql.py, tests_metricflow/plan_conversion/test_dataflow_to_execution.py, tests_metricflow/sql/compare_sql_plan.py, tests_metricflow/sql/optimizer/check_optimizer.py, tests_metricflow/sql/optimizer/test_column_pruner.py, tests_metricflow/sql/optimizer/test_cte_column_pruner.py, tests_metricflow/sql/optimizer/test_cte_rewriting_sub_query_reducer.py, tests_metricflow/sql/optimizer/test_cte_table_alias_simplifier.py, tests_metricflow/sql/optimizer/test_table_alias_simplifier.py, tests_metricflow/sql/test_engine_specific_rendering.py, tests_metricflow/sql_clients/test_date_time_operations.py
This PR renames a few symbols related to the recent rename from `SqlQueryPlan` to `SqlPlan`.
=> Renames related to `SqlPlan` - Part 3

dbt-metricflow/pyproject.toml
The `pyproject.toml` file for `dbt-metricflow` contains a dependency using a git SHA, so the `allow-direct-references` option needs to be enabled.
=> Allow direct references for `dbt-metricfow` dependencies

.github/actions/run-mf-tests/action.yaml, .github/actions/setup-python-env/action.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-linting.yaml, .github/workflows/ci-metricflow-unit-tests.yaml, scripts/ci_tests/install_hatch_environments.py, scripts/ci_tests/run_package_build_tests.py, scripts/mf_script_helper.py
I noticed that some CI checks were a bit slow on occasion, and found that the root cause was that those checks were installing their dependencies during the run. It seems the associated environment was not getting cached, so this PR updates the action to do so.
=> Cache Python Environments in CI

metricflow/sql/optimizer/column_pruner.py, metricflow/sql/optimizer/required_column_aliases.py, metricflow/sql/sql_plan.py
This PR adds the `SqlCteAliasMapping` to replace the plain `dict` that is currently used to map a CTE alias to a CTE node. This allows for easier manipulation / type hinting when improved CTE support is added to the optimizers.
=> Add `SqlCteAliasMapping` to replace `dict`

metricflow/sql/optimizer/column_pruner.py, metricflow/sql/optimizer/cte_alias_to_cte_node_mapping.py, metricflow/sql/optimizer/cte_mapping_lookup_builder.py, metricflow/sql/optimizer/required_column_aliases.py, tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_common_cte_aliases_in_nested_query__result.txt, tests_metricflow/sql/optimizer/check_optimizer.py, tests_metricflow/sql/optimizer/test_cte_column_pruner.py
Previously, the `SqlColumnPrunerOptimizer` only accounted for CTEs defined at the top level as in current use, the `DataflowToSqlPlanConverter` only generated SQL plans in that way. To allow for generation of SQL plans with CTEs defined in sub-queries (at any depth), this PR updates `SqlColumnPrunerOptimizer` to keep track of the CTE alias mapping / CTE context when traversing the SQL plan.
=> For `SqlColumnPrunerOptimizer` - add support for CTEs in sub-queries

metricflow/sql/optimizer/rewriting_sub_query_reducer.py, tests_metricflow/snapshots/test_cte_rewriting_sub_query_reducer.py/str/test_cte_in_subquery_not_reduced__result.txt, tests_metricflow/sql/optimizer/test_cte_rewriting_sub_query_reducer.py
Similar to https://github.com/dbt-labs/metricflow/pull/1613, but for `SqlRewritingSubQueryReducer`.
=> For `SqlRewritingSubQueryReducer`, add support for CTEs defined in sub-queries

metricflow-semantics/metricflow_semantics/dag/id_prefix.py, metricflow-semantics/metricflow_semantics/specs/dunder_column_association_resolver.py, metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py, metricflow-semantics/metricflow_semantics/sql/sql_exprs.py, metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/dataflow/dataflow_plan_visitor.py, metricflow/dataflow/nodes/offset_by_custom_granularity.py, metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py, metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py, metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py, metricflow/dataset/convert_semantic_model.py, metricflow/dataset/sql_dataset.py, metricflow/execution/dataflow_to_execution.py, metricflow/plan_conversion/dataflow_to_sql.py, metricflow/sql/sql_plan.py, tests_metricflow/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
Adds a new node called `OffsetByCustomGranularityNode`. This will be used to build the SQL for custom offset windows.
=> Add new dataflow plan node for custom offset windows

metricflow/plan_conversion/dataflow_to_sql.py, metricflow/sql/sql_plan.py, tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/test_semi_additive_join_node__plan0.xml, tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/test_semi_additive_join_node_with_grouping__plan0.xml, tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/test_semi_additive_join_node_with_queried_group_by__plan0.xml
This PR fixes a case of `SelectStatementNode` reuse when generating the SQL for a semi-additive join node. There are a few renames in here that increase the diff, but the actual change is small. Please view by commit.
=> Fix reuse of `SelectStatementNode` for semi-additive join SQL

.gitignore, Makefile, metricflow-semantics/metricflow_semantics/test_helpers/performance_helpers.py, pyproject.toml, tests_metricflow/performance/compare_reports.py, tests_metricflow/performance/conftest.py, tests_metricflow/performance/test_simple_manifest.py
NOTE: I had to significantly refactor the original version of this PR to make it use cProfile, so I changed the description and comments to match.
This PR introduces some new testing functionality that we can use to avoid performance regressions. From a user perspective, the performance benchmarking workflow is:
1. Create a new test in `tests_metricflow/performance/` that does something we want to track performance for. You can use `measure_compilation_performance` fixtures to measure the compilation of some SQL based on a query spec and a manifest.
3. Run `make perf` to generate a `performance-report.json`.
4. Run `make perf-compare A=base-report.json B=other-report.json` to generate a Markdown file with a report on changes.
The `performance-report.json` file contains the "raw" data for …
=> Add performance tracking machinery

.github/workflows/ci-cache-environments.yaml
I have been puzzled as to why my PRs sometimes do not get a cache hit in the test Github workflows. Without caching, even the linting check takes minutes to run because it needs to install the dependencies. Based on the docs, it seems that the cache might need to be run on `main`:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
```
Workflow runs cannot restore caches created for child branches or sibling branches. 
For example, a cache created for the child feature-b branch would not be accessible 
to a workflow run triggered on the parent main branch. 
```
So this PR is trying out an action that will run on a push to main to populate the cache.
=> Run the Github cache workflow using the `main` branch

dbt-metricflow/dbt_metricflow/cli/main.py
To run the tutorial in a build-package CI test, this adds a `--yes` option that will allow the tutorial setup to complete without user input.
=> Add `--yes` option to `mf tutorial`

.github/actions/setup-python-env/action.yaml, .github/workflows/cd-push-metricflow-to-pypi.yaml
Got this error while trying to publish in the workflow:
```
ERROR    InvalidDistribution: Invalid distribution metadata: license-expression 
introduced in metadata version 2.4, not 2.1     
```
Might be caused by something else, but fixing the Python version to rule it out.
=> Update Pypi publish workflow to use Python 3.9

pyproject.toml
Updating the version of `hatchling` resolves an issue in the workflow to publish the package to Pypi:
```
ERROR    InvalidDistribution: Invalid distribution metadata: license-expression 
introduced in metadata version 2.4, not 2.1     
```
=> Update `hatchling` to `1.27.0`

dbt-metricflow/dbt_metricflow/__about__.py, metricflow-semantics/pyproject.toml, metricflow/__about__.py
The defined version for packages should generally have a `*.dev123` suffix in `main`.
=> Update package version definitions to `*.dev0`

metricflow-semantics/metricflow_semantics/__about__.py, metricflow-semantics/pyproject.toml
This PR updates how the package version for `metricflow-semantics` is set to follow the style for `metricflow`.
=> Use `__about__.py` to define `metricflow-semantics` package version

tests_metricflow/fixtures/cli_fixtures.py
The setup for the dbt project should be skipped, as otherwise, devs could see unusual errors if they have a dbt project configured while running tests.
=> Skip CLI setup in tests

.changes/unreleased/Fixes-20250129-152608.yaml, dbt-metricflow/dbt_metricflow/cli/main.py, dbt-metricflow/dbt_metricflow/cli/tutorial.py
To simplify the user experience, this PR updates the tutorial flow to always create a sample project and asks the user to run the tutorial commands from there.
Since `main.py` was getting large, this PR includes a refactor to move the tutorial to the helper class. Please review by commit.
=> Update tutorial flow to always create a sample project

.github/workflows/ci-metricflow-unit-tests.yaml, scripts/ci_tests/dbt_metricflow_package_test.py, scripts/ci_tests/run_package_build_tests.py
This PR adds a test in CI that checks if the `dbt-metricflow` package builds properly. The check is accomplished by running the tutorial and then running the sample query.
=> Add a CI test for the `dbt-metricflow` package

.changes/unreleased/Fixes-20250129-152608.yaml, dbt-metricflow/dbt_metricflow/cli/main.py, dbt-metricflow/dbt_metricflow/cli/tutorial.py, tests_metricflow/fixtures/cli_fixtures.py
This PR ports the updates that were previously merged for the `dbt-metricflow==0.8.1` release to `main`. There are some additional updates that will be ported after some fixes in `main`.
=> Port updates from `dbt-metricflow/v0.8.1` to `main`

metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py
This PR updates the handling for Pydantic objects in `mf_pformat` to check if the `dict()` methods exists instead of the `isinstance(BaseModel)` check. The `BaseModel` is actually from the `dsi_shim` and in some cases with different Pydantic versions, it's possible that the check does not pass.  Since it's not foolproof, the formatter falls back to `pprint` if there is an error.
=> Update handling for Pydantic objects in `mf_pformat`

metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_lazy_format.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_pformat_dict.py
This PR enables small objects with a short string representation to be formatted on one line.
=> Allow for a one-line representation in `mf_pformat_dict()`

metricflow-semantics/metricflow_semantics/mf_logging/lazy_formattable.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_lazy_format.py, metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py, metricflow/sql/optimizer/column_pruning/column_pruner.py
When creating a `LazyFormat` object, the keyword argument values may be constructed from expensive methods. Similar to allowing a function to be passed in for the `message` argument, this PR enables methods to be passed in for the keyword argument values so that they can be lazily evaluated.
There were some logging calls that were found in performance profiling to be expensive because lazy-evaluation was not done, so this PR updates a few of those call sites as well. An alternative approach would have been to implement `MetricFlowPrettyFormattable` for those objects.
=> Allow for lazy-evaluation of arguments in `LazyFormat`

dbt-metricflow/dbt_metricflow/cli/cli_link.py, dbt-metricflow/dbt_metricflow/cli/tutorial.py, dbt-metricflow/dbt_metricflow/cli/utils.py
This PR adds a suggestion to report bugs by going to a supplied link when the CLI displays errors.
=> Add link to report issues when displaying errors in the CLI

.github/actions/run-mf-tests/action.yaml, .github/workflows/cd-push-dbt-metricflow-to-pypi.yaml, .github/workflows/cd-push-metricflow-to-pypi.yaml, .github/workflows/cd-sql-engine-populate-persistent-source-schema.yaml, .github/workflows/cd-sql-engine-tests.yaml, .github/workflows/ci-linting.yaml, .github/workflows/ci-metricflow-unit-tests.yaml
I found there were still more actions using Python 3.8. We should be using Python 3.9, and using the older version affects how actions are cached. To simplify management, this removes places that specify a Python version so that the default version (3.9) is used.
There were places where Python 3.12 was specified, but it was unclear why that was the case. Changed those to use the default version as well.
=> Update Github actions to use the default Python version

metricflow/dataflow/dataflow_plan.py, metricflow/dataflow/nodes/join_to_time_spine.py
This PR fixes an issue with `JoinToTimeSpineNode.with_new_parents()` where it was not using the new parents.
=> Fix `JoinToTimeSpineNode.with_new_parents()`

metricflow-semantics/metricflow_semantics/time/time_spine_source.py
Reverts dbt-labs/metricflow#1428
We removed this error so that the saved query dependency resolver in mantle wouldn't hit it for a manifest that does not have any semantic models. Later, we decided not to treat that as a valid state for any MF classes, and instead to avoid instantiating the dependency resolver in that case. That means we can put this error back.
Plus, [some customer ran into this error scenario](https://dbt-labs.slack.com/archives/C05K4R7KZ5Z/p1739894465024389), and they got a very unclear error instead. This will give them a better error in the future.
=> Revert "Don't error for lack of time spines"

metricflow/sql/optimizer/column_pruning/column_pruner.py, metricflow/sql/optimizer/column_pruning/required_column_aliases.py
This PR renames a few variables and methods in the column pruner classes in preparation for https://github.com/dbt-labs/metricflow/pull/1679.
=> Assorted renames in column pruner classes

metricflow/sql/optimizer/column_pruning/required_column_aliases.py
This PR consolidates a couple of loops in `SqlMapRequiredColumnAliasesVisitor` and replaces `.add_alias()` calls with `.add_aliases()` to reduce nesting. There are no logic changes in this PR, and this is mainly to make https://github.com/dbt-labs/metricflow/pull/1679 a simple change given the complexity in that class.
There is some additional consolidation that can be done with other loops, but leaving those out of scope.
=> Consolidate loops in `SqlMapRequiredColumnAliasesVisitor`

metricflow/sql/optimizer/column_pruning/required_column_aliases.py, tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_column_reference_expression__result.txt, tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_string_expression__result.txt, tests_metricflow/sql/optimizer/test_cte_column_pruner.py
This PR fixes a bug where the column pruner does not correctly keep track of columns that are used in `SqlStringExpression` and `SqlColumnAliasReferenceExpression`. Those expressions are different from other expressions as they do not have a table alias, and there is existing case handling for those expressions. The bug is that the handler did not propagate the knowledge that columns from those expressions is required to the available CTEs.
This bug currently does not affect queries due to the way that we wrap access to CTEs in a `SELECT`, but fixing this as it affects later work.
=> Fix bug with missed columns in the column pruner

.changes/unreleased/Fixes-20250328-140319.yaml, dbt-metricflow/dbt_metricflow/cli/sample_dbt_models/sample_models/countries.sql, dbt-metricflow/dbt_metricflow/cli/sample_dbt_models/sample_models/customers.sql, dbt-metricflow/dbt_metricflow/cli/sample_dbt_models/sample_models/transactions.sql, dbt-metricflow/dbt_metricflow/cli/tutorial.py, tests_metricflow/snapshots/test_cli.py/str/test_tutorial_message__result.txt
This PR updates the tutorial project to use `ref()` instead of `source()` in the models. By using `ref()`, `dbt build` will be able to seed appropriately by determining dependencies, allowing the removal of the `dbt seed` step.
For context, updates to the tutorial project are helpful for later changes to the CLI tests / CLI test framework.
=> Update tutorial project to use `ref()`

.changes/unreleased/Features-20250328-140506.yaml, dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/profiles.yml, dbt-metricflow/dbt_metricflow/cli/tutorial.py
This PR updates the `profiles.yml` file in the tutorial project so that the `DuckDB` database file is stored within the project directory instead of the current working directory. This helps to allow for later test cases that run the CLI from directories outside of the project directory.
=> Specify DB file path in tutorial-project profile

.changes/unreleased/Under the Hood-20250328-140613.yaml, dbt-metricflow/dbt_metricflow/cli/cli_configuration.py, dbt-metricflow/dbt_metricflow/cli/dbt_connectors/adapter_backed_client.py, dbt-metricflow/dbt_metricflow/cli/dbt_connectors/dbt_config_accessor.py, tests_metricflow/fixtures/cli_fixtures.py
This PR allows `CliConfiguration` to be loaded from project / profile paths other than the current working directory. This later will enable easier testing of different dbt projects since changing the current working directory can have other side effects.
=> Allow `CliConfiguration` to be loaded from specified paths

.changes/unreleased/Under the Hood-20250328-140847.yaml, dbt-metricflow/dbt_metricflow/cli/main.py, dbt-metricflow/dbt_metricflow/cli/tutorial.py
This PR removes the dependency on the `dbt` project metadata when generating the files associated with the tutorial. This enables the tutorial project (and modified versions) to be more easily generated in test cases.
=> Remove `dbt` project metadata dependency in tutorial project generation

.changes/unreleased/Under the Hood-20250328-141124.yaml, dbt-metricflow/dbt_metricflow/cli/cli_configuration.py, dbt-metricflow/dbt_metricflow/cli/main.py, tests_metricflow/fixtures/cli_fixtures.py
Currently, the `CLIConfiguration` object is initialized / reloaded at the start of a CLI command. To aid test setup, this PR updates CLI commands to only initialize the configuration if it has not already been done. This allows for a prebuilt configuration to be passed into the CLI when running tests and also allows for more straightforward invocation of a CLI command from another CLI command.
=> Avoid reinitialization of `CLIConfiguration`

.changes/unreleased/Under the Hood-20250328-141234.yaml, tests_metricflow/cli/cli_test_helpers.py, tests_metricflow/cli/executor_process_main_function.py, tests_metricflow/cli/isolated_cli_command_interface.py, tests_metricflow/cli/isolated_cli_command_runner.py, tests_metricflow/cli/test_isolated_command_runner.py, tests_metricflow/snapshots/test_isolated_command_runner.py/str/test_isolated_query__result.txt, tests_metricflow/snapshots/test_isolated_command_runner.py/str/test_multiple_queries__result.txt
* The `mf` CLI depends on `dbt` libraries to load the profile for the SQL-engine connection and to load the project manifest.
* However, the `dbt` libraries mutate global / module state, and the contractural guarantees regarding these mutations are not clear.
* In tests, there is a need to test different CLI commands that require different project configurations, so the best way to provide this isolation is to use a separate process to run each CLI command.
* A separate process also enables isolated testing for global-like settings (e.g. settings passed via environment variables).
* Process-level isolation mitigates issues with test execution order / concurrency when different tests load different project configurations.
* This PR adds a CLI runner that uses the `multiprocessing` module …
=> Add process-isolated CLI runner for tests

tests_metricflow/cli/demo_data_types_project_add_on/__init__.py, tests_metricflow/cli/demo_data_types_project_add_on/models/demo_data_types.sql, tests_metricflow/cli/demo_data_types_project_add_on/models/demo_data_types.yml, tests_metricflow/cli/demo_data_types_project_add_on/models/metrics.yml, tests_metricflow/cli/demo_data_types_project_add_on/seeds/demo_data_types_seed.csv, tests_metricflow/cli/demo_data_types_project_add_on/seeds/properties.yml, tests_metricflow/cli/test_output_format.py, tests_metricflow/snapshots/test_output_format.py/str/test_decimals_option__result.txt, tests_metricflow/snapshots/test_output_format.py/str/test_print_null__result.txt, tests_metricflow/snapshots/test_output_format.py/str/test_print_numeric_types__result.txt, tests_metricflow/snapshots/test_output_format.py/str/test_print_string__result.txt, tests_metricflow/snapshots/test_output_format.py/str/test_single_large_number_with_decimals_option__result.txt
This PR adds a test case that includes snapshots of the CLI output when running `mf query ...` with results that contain a variety of data types. There are a few issues that are demonstrated in the snapshots:
* `--decimals` option not taking effect.
* `NULL` values showing up as `None`.
* Alignment changes depending on query output.
* String values that are shown with stripped whitespace.
* Unexpected / inconsistent use of exponential format.
These are resolved in later PRs.
=> Add test case to capture display of various data types for `mf query`

.changes/unreleased/Fixes-20250328-141817.yaml, metricflow/data_table/mf_table.py, tests_metricflow/snapshots/test_output_format.py/str/test_print_string__result.txt
This PR removes the stripping of whitespace around string values in the output of `mf query`.
=> Address display of whitespace-padded strings in the output of `mf query`

.changes/unreleased/Features-20250328-142032.yaml, dbt-metricflow/dbt_metricflow/cli/cli_configuration.py, tests_metricflow/cli/executor_process_main_function.py, tests_metricflow/cli/isolated_cli_command_interface.py, tests_metricflow/cli/isolated_cli_command_runner.py, tests_metricflow/cli/test_isolated_command_runner.py, tests_metricflow/snapshots/test_isolated_command_runner.py/str/test_environment_variables__result.txt
Resolves #1591
This PR adds support for using the environment variables `DBT_PROFILES_DIR` / `DBT_PROJECT_DIR` to configure how the `mf` command loads the connection / project.
=> Add support for `DBT_PROFILES_DIR` / `DBT_PROJECT_DIR` in the CLI

.changes/unreleased/Features-20250331-171100.yaml, .changes/unreleased/Fixes-20250401-110415.yaml, dbt-metricflow/dbt_metricflow/cli/cli_configuration.py, dbt-metricflow/dbt_metricflow/cli/cli_errors.py, dbt-metricflow/dbt_metricflow/cli/cli_string.py, dbt-metricflow/dbt_metricflow/cli/dbt_connectors/dbt_config_accessor.py, dbt-metricflow/dbt_metricflow/cli/utils.py, metricflow-semantics/metricflow_semantics/errors/error_classes.py, metricflow-semantics/metricflow_semantics/query/query_parser.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_ambiguous_entity_path.py/str/test_non_resolvable_ambiguous_entity_path_due_to_mismatch__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_ambiguous_entity_path.py/str/test_non_resolvable_ambiguous_entity_path_due_to_multiple_matches__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_defined_filters_in_multi_metric_query__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_defined_where_filter__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_group_by_item__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_metric__result_0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_suggestions.py/str/test_suggestions_for_multiple_metrics__result_0.txt, tests_metricflow/cli/cli_test_helpers.py, tests_metricflow/cli/executor_process_main_function.py, tests_metricflow/cli/test_cli_error.py, tests_metricflow/snapshots/test_cli_error.py/str/test_invalid_metric__result.txt, tests_metricflow/snapshots/test_cli_error.py/str/test_missing_semantic_manifest__result.txt
This PR updates error handling so that the modification time of the semantic-manifest artifact is shown when an error message is shown to the user. This may help users realize if they are querying using an old semantic manifest artifact because they forgot to run `dbt build` after updates.
=> Add artifact modified time to CLI error messages

.changes/unreleased/Fixes-20250331-171239.yaml, dbt-metricflow/dbt_metricflow/cli/main.py, tests_metricflow/cli/test_cli.py, tests_metricflow/cli/test_cli_error.py, tests_metricflow/snapshots/test_cli.py/str/test_csv__result.txt
Resolves #1706 
This PR updates the CLI to use the native Python methods to create and close the CSV file to handle a potential issue with `click`'s `File` / `LazyFile` where the written file was not immediately visible.
=> Use native Python methods to manage the CSV file handle

.changes/unreleased/Fixes-20250331-171345.yaml, pytest.ini
This PR updates `pytest.ini` so that `pytest` does not scan the `snapshots` directories for tests. There are many files in that location, and parsing them may result in errors.
=> Configure `pytest` to skip scanning snapshots directory

metricflow-semantics/metricflow_semantics/time/time_spine_source.py, tests_metricflow/cli/test_cli.py, tests_metricflow/snapshots/test_cli.py/str/test_missing_time_spine_error__result.txt
This PR back ports an improved error message (65e211580) + adds a test for the case where the user did not configure a time spine. Previously, the user would get a cryptic error message (also see associated commit in this PR): 
```
min() iterable argument is empty
```
=> Backport updated error message for missing time spine

.changes/unreleased/Under the Hood-20250403-032326.yaml, tests_metricflow/performance/categorical_dimension_generator.py, tests_metricflow/performance/dimension_semantic_model_generator.py, tests_metricflow/performance/measure_generator.py, tests_metricflow/performance/measure_semantic_model_generator.py, tests_metricflow/performance/metric_generator.py, tests_metricflow/performance/saved_query_generator.py, tests_metricflow/performance/semantic_manifest_generator.py, tests_metricflow/performance/synthetic_manifest_parameter_set.py, tests_metricflow/performance/test_manifest_generator.py, tests_metricflow/snapshots/test_manifest_generator.py/PydanticSemanticManifest/test_manifest_generator__result.txt
This PR adds a few classes to generate a synthetic manifest. The synthetic manifest can then be used to profile performance and scaling behavior.
=> Synthetic manifests for performance tests

metricflow-semantics/metricflow_semantics/model/semantic_manifest_lookup.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_index.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_index_builder.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/manifest_object_lookup.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_spec_resolver.py, metricflow-semantics/tests_metricflow_semantics/model/test_semantic_model_container.py
This PR adds `LinkableSpecIndex` that is an index object that can be stored and used to initialize `MetricflowEngine` more quickly. This is mainly a shuffling of some of the code in `ValidLinkableSpecResolver` to `LinkableSpecIndexBuilder`, but it can be hard to see from the commits what is old code vs. new code. In addition, there is some more consolidation that can be done between the two classes.
There should be no logical / semantic changes from this update, so the existing tests are used to validate correctness (e.g. `test_linkable_spec_resolver.py`).
=> Add index to store group-by-item metadata

.changes/unreleased/Under the Hood-20250403-120130.yaml, tests_metricflow/performance/test_mf_engine.py
This PR adds a test that benchmarks the time to initialize `MetricflowEngine` with and without `LinkableSpecIndex`. Depending on the semantic manifest, there can be large improvements, and the benchmark case shows a >10x improvement.
=> Add test for MF engine init time improvements via `LinkableSpecIndex`

metricflow-semantics/metricflow_semantics/experimental/singleton.py, metricflow-semantics/tests_metricflow_semantics/experimental/collection_helpers/singleton_test_classes.py, metricflow-semantics/tests_metricflow_semantics/experimental/collection_helpers/test_singleton.py
This experimental PR adds a `Singleton` base class that could improve performance of ID-like dataclasses (see tests). This might need some additional refinement / performance verification.
=> Add `Singleton` base class

dbt-metricflow/dbt_metricflow/cli/dbt_connectors/adapter_backed_client.py, dbt-metricflow/dbt_metricflow/cli/main.py, metricflow-semantics/metricflow_semantics/mf_logging/runtime.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_index_builder.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow/dataflow/builder/dataflow_plan_builder.py, metricflow/execution/execution_plan.py, metricflow/telemetry/reporter.py, tests_metricflow/cli/isolated_cli_command_runner.py, tests_metricflow/execution/noop_task.py, tests_metricflow/fixtures/sql_clients/adapter_backed_ddl_client.py, tests_metricflow/performance/test_mf_engine.py
This PR replaces calls to `time.time()` with `time.perf_counter()` when used in performance measurement cases as `time.time()` may have issues when the system time changes (e.g. daylight savings).
=> Replace `time.time()` with `time.perf_counter()`

dbt-metricflow/dbt_metricflow/cli/dbt_connectors/dbt_config_accessor.py, metricflow-semantics/metricflow_semantics/model/semantics/dimension_lookup.py, metricflow-semantics/metricflow_semantics/model/semantics/measure_lookup.py, metricflow-semantics/metricflow_semantics/naming/object_builder_str.py, metricflow/dataset/sql_dataset.py, metricflow/engine/metricflow_engine.py, metricflow/plan_conversion/instance_converters.py, metricflow/plan_conversion/to_sql_plan/dataflow_to_subquery.py, metricflow/sql/optimizer/column_pruning/cte_alias_to_cte_node_mapping.py, tests_metricflow/cli/cli_test_helpers.py, tests_metricflow/performance/test_manifest_generator.py
This PR removes calls similar to `str(LazyFormat(...))` when used with exceptions as `str()` is called on the message anyway.
=> Remove `str()` for `LazyFormat` passed into `Exception`

metricflow-semantics/metricflow_semantics/specs/non_additive_dimension_spec.py, metricflow/dataflow/builder/dataflow_plan_builder.py
This PR removes the custom `NonAdditiveDimensionSpec.__eq__` as it can cause odd behavior - two instances that are considered equal can have a different hash.
=> Remove `NonAdditiveDimensionSpec.__eq__`

.changes/unreleased/Under the Hood-20250425-173202.yaml, metricflow-semantics/metricflow_semantics/dag/mf_dag.py, metricflow-semantics/metricflow_semantics/mf_logging/pretty_formattable.py, metricflow-semantics/metricflow_semantics/mf_logging/pretty_formatter.py, metricflow-semantics/metricflow_semantics/sql/sql_exprs.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_pretty_print.py
This PR updates the signature of `MetricFlowPrettyFormattable.pretty_format()` to include a format context object. This allows implementing classes to format itself with more flexibility and with more adherence to the format options. One issue with the previous approach was that custom implementations couldn't properly respect the overall line length limit when formatted as a part of a nested object.
=> Provide context in `MetricFlowPrettyFormattable.pretty_format()`

.changes/unreleased/Under the Hood-20250425-173249.yaml, metricflow-semantics/metricflow_semantics/mf_logging/pretty_formatter.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_pretty_print.py
This PR updates pretty-formatting of sets to use `{...}` instead of `set(...)`. `_handle_sequence_obj` was renamed to `_handle_sequence_like_obj`.
=> Use `{}` for pretty-formatting `Set`

.changes/unreleased/Under the Hood-20250425-183020.yaml, metricflow-semantics/metricflow_semantics/mf_logging/pretty_formatter.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_pretty_print.py
This PR adds the `include_underscore_prefix_fields` to `mf_pformat` to handle private fields.
=> Add `include_underscore_prefix_fields` option to `mf_pformat`

.changes/unreleased/Under the Hood-20250429-143615.yaml, metricflow-semantics/metricflow_semantics/mf_logging/pretty_formatter.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_pretty_print.py
This PR adds `MetricFlowPrettyFormatter.pretty_format_object_by_parts()`, which is useful for custom formatting when implementing `MetricFlowPrettyFormattable`.
=> Add `pretty_format_object_by_parts()` to pretty formatter

.changes/unreleased/Under the Hood-20250429-144932.yaml, metricflow-semantics/tests_metricflow_semantics/query/conftest.py, metricflow-semantics/tests_metricflow_semantics/query/errors/test_messages.py, metricflow-semantics/tests_metricflow_semantics/query/test_query_parser.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_messages.py/str/test_empty_query__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_messages.py/str/test_invalid_where_filter__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_messages.py/str/test_long_invalid_metric__result.txt
This PR sets up tests for query error messages and adds a test to check the output of an empty query (no metrics, no group-by items). It shows there are some typos as the output includes `Query([], []`. This will be resolved in a later PR.
=> Add test to check the error message for empty queries

.changes/unreleased/Under the Hood-20250429-154609.yaml, metricflow-semantics/metricflow_semantics/collection_helpers/mf_type_aliases.py, metricflow-semantics/metricflow_semantics/dag/sequential_id.py, metricflow-semantics/metricflow_semantics/helpers/mapping_helpers.py, metricflow-semantics/tests_metricflow_semantics/dag/test_sequential_id_generator.py
This PR updates `SequentialIdGenerator` to properly handle calls from async methods. Previously, `SequentialIdGenerator` used thread-local objects, but in async methods, different contexts are run from a single thread.
=> Update `SequentialIdGenerator` to support async methods

.changes/unreleased/Fixes-20250503-102521.yaml, metricflow-semantics/metricflow_semantics/test_helpers/mock_helpers.py, metricflow/plan_conversion/to_sql_plan/dataflow_to_sql.py, tests_metricflow/plan_conversion/dataflow_to_sql/test_exception_retry.py
This PR fixes an issue with a retry mechanism when generating SQL. Due to the bug, the underlying exception was not propagated up when retries were exhausted.
=> Fix exception propagation in SQL generation

.changes/unreleased/Under the Hood-20250505-155239.yaml, metricflow/plan_conversion/instance_converters.py, metricflow/plan_conversion/select_column_gen.py, metricflow/plan_conversion/spec_transforms.py, metricflow/plan_conversion/to_sql_plan/dataflow_to_subquery.py
This PR updates the fields in `SelectColumnSet` to be tuples as the dataclass is supposed to be immutable. In addition, the `.create()` factory method was added to make it easier to create an instance with an additional field added in a later PR.
=> Update `SelectColumnSet` fields to tuples

.changes/unreleased/Under the Hood-20250513-220750.yaml, tests_metricflow/cli/cli_test_helpers.py, tests_metricflow/cli/executor_process_main_function.py, tests_metricflow/cli/isolated_cli_command_interface.py, tests_metricflow/cli/test_isolated_command_runner.py
There were some recent CI test failures that may be the result of inconsistent or updated behavior from the `Click` dependency. The output of CLI commands was previously checked with the `stdout` field, but that field is now returning an empty value in the error case. This PR updates the test framework to use the `output` field that combines both `stdout` and `stderr`.
=> Use `output` from the `click` invocation to check test results

.changes/unreleased/Under the Hood-20250514-005030.yaml, metricflow/engine/metricflow_engine.py, metricflow/plan_conversion/instance_set_transforms/select_columns.py, tests_metricflow/cli/executor_process_main_function.py, tests_metricflow/fixtures/cli_fixtures.py, tests_metricflow/integration/test_configured_cases.py
This PR resolves an issue where `order_output_columns_by_input_order` did not take effect as expected for metrics with filters defined. This was due to the `MetricSpec` not being the same for what was passed in vs. the one used in the dataflow plan.
=> Handle `order_output_columns_by_input_order` for filtered metrics

.changes/unreleased/Under the Hood-20250514-101429.yaml, metricflow-semantics/metricflow_semantics/mf_logging/pretty_formatter.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_pretty_print.py
This PR updates the handling of `pathlib.Path` objects so that they are presented more cleanly in logs.
=> Add handling of `Path` objects in `mf_pformat()`

metricflow-semantics/metricflow_semantics/collection_helpers/mf_type_aliases.py, metricflow-semantics/metricflow_semantics/experimental/comparison_helpers.py, metricflow-semantics/metricflow_semantics/experimental/ordered_set.py, metricflow-semantics/tests_metricflow_semantics/experimental/test_ordered_set.py, metricflow-semantics/tests_metricflow_semantics/mf_logging/test_pretty_print.py
This PR adds ordered set classes to provide consistency in tests. The `ordered-set` package provides similar functionality, but favoring this as the implementation is short and would avoid adding a dependency.
=> Add ordered set classes

metricflow-semantics/metricflow_semantics/experimental/orderd_enum.py, metricflow-semantics/tests_metricflow_semantics/experimental/test_ordered_enum.py
This PR adds an `Enum` base class that can be ordered for consistency in tests. The `OrderedEnum` from `aenum` was considered but favoring this as the implementation is short and avoids adding a dependency.
=> Add `OrderedEnum`

.changes/unreleased/Fixes-20250620-153226.yaml, metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_parse_and_validate_where_constraint_dims__result.txt, metricflow-semantics/tests_metricflow_semantics/specs/patterns/test_typed_patterns.py, tests_metricflow/integration/test_cases/itest_constraints.yaml
We've been seeing an error that looks like this when querying a time dimension with no grain in a Dimension Jinja block:
This PR fixes that.
=> Fix ambiguity error for time dimensions in Dimension Jinja block

.changes/unreleased/Fixes-20250624-131026.yaml, metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py, metricflow-semantics/requirements-files/requirements.txt, requirements-files/requirements.txt, tests_metricflow/snapshots/test_manifest_generator.py/PydanticSemanticManifest/test_manifest_generator__result.txt
Pair to [this PR](https://github.com/dbt-labs/dbt-semantic-interfaces/pull/379). Fixes an issue where we can't find the `agg_time_dimension` in the semantic model because it's uppercased in one place and lowercased in the other.
=> Ensure lowercase agg_time_dimension

metricflow/engine/metricflow_engine.py, tests_metricflow/snapshots/test_mf_engine.py/list/test_list_dimensions_for_metrics_for_multiple_metrics__result0.txt
1. Allow including derived time grains in `list_group_bys` - This is used for a pretty niche feature in our API that allows you to list all group by names for a given metric. See [here](https://github.com/dbt-labs/metricflow-server/pull/1498) for how it's used.
2. Dedupe group bys exposed in `MFEngine`. There might be duplicates here due to differences between the `LinkableDimension/Entity` and `Dimension/Entity` objects. Ultimately this is because of different join paths used to reach the group by from different metrics.
=> Allow including derived time grains in list_group_bys

metricflow-semantics/tests_metricflow_semantics/experimental/graph_helpers.py, metricflow-semantics/tests_metricflow_semantics/experimental/mf_graph/test_graph_snapshot.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_graph_snapshot.py/str/test_graph_snapshot__result.txt
This PR adds `assert_graph_snapshot_equal` used in later graph tests.
=> Add `assert_graph_snapshot_equal` for tests

metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
This PR updates `LinkableElementType` to be an `OrderedEnum` for consistency in test outputs.
=>  Make `LinkableElementType` an `OrderedEnum`

.changes/unreleased/Under the Hood-20250718-145128.yaml, metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_all_properties__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_cyclic_join_manifest__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_metric_time_property_for_cumulative_metric__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_metric_time_property_for_derived_metrics__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_one_property__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure_multi_hop_model__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_metrics__result0.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_set_for_common_dimensions_in_different_models__result0.txt
To enable use of the semantic graph with a control flag, the MF engine needs a common way of resolving group-by items for a query. To do this, later PRs will change `LinkableElementSet` to an interface with different implementations. To keep test snapshots consistent, this PR updates the format of the snapshot so that the outputs are the same for both implementations.
=> Update the snapshot format for `LinkableElementSet`

.changes/unreleased/Under the Hood-20250724-212239.yaml, metricflow-semantics/metricflow_semantics/experimental/test_helpers/performance_helpers.py, metricflow-semantics/tests_metricflow_semantics/experimental/collection_helpers/test_fast_frozen_dataclass.py, metricflow-semantics/tests_metricflow_semantics/experimental/collection_helpers/test_singleton.py, metricflow-semantics/tests_metricflow_semantics/test_benchmark.py
This PR adds a helper that makes it easier to write tests that compare performance of function calls using `timeit`. The issue with `timeit` is that the arguments are strings of code snippets. Those strings are annoying to write as the IDE inspections don't work / `mypy` does not do type checks. In addition, all required imports must be included in the code snippets.
The helper provides a closure that can be written normally and is instantiated in the `timeit` statement. Please view by commit as there were some renames that are included.
The helper is a WIP so this PR does not migrate existing performance tests.
=> Add a helper for writing `timeit`-based performance tests

.changes/unreleased/Under the Hood-20250724-212448.yaml, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/attribute_recipe_step.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/nodes/attribute_nodes.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/nodes/entity_nodes.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/nodes/node_labels.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/sg_constant.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/sg_interfaces.py
This PR adds the set of nodes used in the semantic graph. Docstrings are in the process of refinement, but there should be enough context in there for review.
=> Add semantic-graph node classes

.changes/unreleased/Under the Hood-20250725-170903.yaml, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/edges/edge_labels.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/edges/sg_edges.py
Related to https://github.com/dbt-labs/metricflow/pull/1791, this add the classes for edges in the semantic graph.
=> Add semantic-graph edge classes

.changes/unreleased/Fixes-20250725-171609.yaml, metricflow-semantics/metricflow_semantics/query/issues/group_by_item_resolver/no_common_items.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_ambiguous_entity_path.py/str/test_non_resolvable_ambiguous_entity_path_due_to_mismatch__result_0.txt
This PR fixes formatting errors in the error message generated by `no_common_items.py`.
=> Fix error message in `no_common_items.py`

.changes/unreleased/Under the Hood-20250730-203401.yaml, metricflow-semantics/metricflow_semantics/experimental/dsi/join_lookup.py, metricflow-semantics/metricflow_semantics/experimental/dsi/manifest_object_lookup.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/entity_join_subgraph.py, metricflow-semantics/tests_metricflow_semantics/experimental/mf_graph/formatting/mf_to_graphical_dot.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/builder/test_subgraph_1_entity_join.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_subgraph_1_entity_join.py/str/test_minimal_manifest__result.txt, metricflow-semantics/tests_metricflow_semantics/snapshots/test_subgraph_1_entity_join.py/str/test_single_join_manifest__result.txt
This PR adds `EntityJoinSubgraphGenerator`, which generates the edges to model joins between semantic models via configured entities.
=> Add subgraph generator for modeling joins

.changes/unreleased/Under the Hood-20250730-204027.yaml, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/categorical_dimension_subgraph.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/builder/test_subgraph_2_categorical_dimension.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_subgraph_2_categorical_dimension.py/str/test_single_join_manifest__result.txt
This PR adds a subgraph generator for the semantic graph to handle categorical dimensions.
=> Add subgraph generator for categorical dimensions

.changes/unreleased/Under the Hood-20250730-204837.yaml, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/entity_key_subgraph.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/builder/test_subgraph_3_entity_key.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_subgraph_3_entity_key.py/str/test_minimal_manifest__result.txt
This PR adds a subgraph generator to model queries for configured-entity keys. In the context of the query interface, this is related to "querying for an entity".
=> Add subgraph generator for configured-entity keys

.changes/unreleased/Under the Hood-20250801-144219.yaml, metricflow-semantics/metricflow_semantics/experimental/mf_graph/mf_graph.py, metricflow-semantics/metricflow_semantics/experimental/mf_graph/mutable_graph.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/attribute_recipe.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/recipe_writer_path.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/recipe_writer_weight.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/graph_builder.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/sg_exceptions.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/sg_interfaces.py, metricflow-semantics/metricflow_semantics/model/semantics/element_filter.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/attribute_resolver/test_recipe_writer.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_recipe_writer.py/str/test_recipe_writer_path__result.txt
This PR adds semantic-graph-specific classes to model paths and path weights in the semantic graph. Paths in the semantic graph can be used to figure out the computation (the recipe) for attributes, and the weight function helps to limit traversal so that only valid paths are taken.
=> Add path weight-function for the semantic graph

.changes/unreleased/Under the Hood-20250805-163012.yaml, metricflow-semantics/metricflow_semantics/collection_helpers/dictionaries.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/trie_resolver/dunder_name_descriptor.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/trie_resolver/dunder_name_trie.py, metricflow-semantics/tests_metricflow_semantics/experimental/test_dunder_name_trie.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_dunder_name_trie.py/dict/test_add_items__result.txt
This PR adds a trie-like data structure for dunder names to simplify the union / intersection operations that are required for group-by item resolution
=> Add trie-like data structure for dunder names

.changes/unreleased/Under the Hood-20250805-164525.yaml, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/annotated_spec_linkable_element_set.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/trie_resolver/entity_key_resolver.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/trie_resolver/group_by_metric_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set_base.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/trie_resolver/test_group_by_metric_trie_resolver.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_group_by_metric_trie_resolver.py/AnnotatedSpecLinkableElementSet/test_measure__result.txt
Related to https://github.com/dbt-labs/metricflow/pull/1806 - this PR adds a semantic-graph-based resolver to resolve group-by metrics.
=> Add semantic-graph-based resolver for group-by metrics

.changes/unreleased/Under the Hood-20250805-165135.yaml, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/resolver/test_sg_lsr_performance.py
This PR adds a test that demonstrates a 500x improvement in initialization times when using the semantic-graph-based resolver. In addition, the resolver also showed an 18x improvement in an high-metric-count lookups (used for metadata calls in the engine).
=> Add performance tests for the semantic-graph-based resolver

.changes/unreleased/Under the Hood-20250807-083916.yaml, metricflow-semantics/metricflow_semantics/model/semantic_manifest_lookup.py, tests_metricflow/fixtures/manifest_fixtures.py, tests_metricflow/integration/test_configured_cases.py
This PR adds the flag `use_semantic_graph` to `SemanticManifestLookup`. Since `SemanticManifestLookup` is an input argument to `MetricFlowEngine`, this allows the flag to be used for incremental deployment.
This also updates the integration tests so that they run with and without the flag set.
=> Add `use_semantic_graph` flag to `SemanticManifestLookup`

.changes/unreleased/Under the Hood-20250811-180206.yaml, metricflow-semantics/metricflow_semantics/errors/error_classes.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_index_builder.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow/engine/metricflow_engine.py, tests_metricflow/engine/test_errors.py, tests_metricflow/snapshot_utils.py, tests_metricflow/snapshots/test_errors.py/dict/test_simple_dimensions_for_metrics_with_invalid_metric__result.txt
This PR updates error handling for `simple_dimensions_for_metrics` to return an error that is decoupled from the underlying implementations in `metric_lookup`.
=> Update error handling for `simple_dimensions_for_metrics`

.changes/unreleased/Under the Hood-20250819-123055.yaml, metricflow-semantics/metricflow_semantics/experimental/dsi/manifest_object_lookup.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/sg_linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/time_entity_subgraph.py, metricflow-semantics/metricflow_semantics/model/semantic_manifest_lookup.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/sg_fixtures.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_manifest_object_lookup.py/ManifestObjectLookup/test_lookup_attributes__result.txt
The semantic graph implementation initially used the minimum grain used in a semantic model as the minimum valid grain (original comment here: https://github.com/dbt-labs/metricflow/blob/4a2edcfbf272f4cc9aef998fd51475b9d8040aad/metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/time_entity_subgraph.py#L43), but then later was changed to use the minimum grain of the time spine as it seemed like it was the correct behavior. To aid migration however, this changes the logic back to the initial implementation.
=> Switch back to using minimum time grain from models

requirements-files/dev-env-requirements.txt, tests_metricflow/generate_snapshots.py
There appears to be some issues with the latest duckdb version, so pinning to a lower version.
Also removes a some commenting that was accidentally merged in a previous commit.
=> Cleanup: fix duckdb version + remove accidental commenting

.changes/unreleased/Fixes-20250916-121517.yaml, metricflow-semantics/metricflow_semantics/experimental/dsi/manifest_object_lookup.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/time_entity_subgraph.py
Seeing some [error logs](https://dbtlabsmt.datadoghq.com/logs?query=trace_id%3A68c91dce0000000098a793d8afe08253&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZlRnG__fSBcoAAAABhBWmxSbklLT0FBQUsweGo5Z1Y1dVJRQXIAAAAkZjE5OTUxYTAtMzU5OC00M2Q0LWJmZmQtMDQxNzNkNjAzODczAAE5ww&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1758009830199&to_ts=1758011830854&live=false) where this min() is called on an empty list. This removes the error.
A manifest without any time dimensions isn't likely very useful (probably in a partially complete state - measures require time dimensions so there can't be any metrics in this case), but this is not where it should error. Instead there are just …
=> Bug fix: don't error if there are no time dims in manifest

.changes/unreleased/Fixes-20250918-070122.yaml, .github/actions/setup-python-env/action.yaml, metricflow-semantics/requirements-files/requirements.txt, requirements-files/requirements.txt
DSI was pinned to a dev version in the last release, which is a problem for some users who use python package managers that ignore dev versions. This pins it to the prior valid version so we can cut a new release pointing to that.
Also pins click due to a bad release that went out today and caused issues building hatch with python 3.12.
=> Pin to a non-dev version of DSI for release

metricflow-semantics/requirements-files/requirements.txt, requirements-files/requirements.txt
We previously upgraded to this version of DSI, then reverted back to a non-dev version for release. Now that the release is finished, we should again use the newer version of DSI. This is needed before releasing a new version of MF to the server. This is because mantle might be producing manifests with the new fields included in the new DSI version, and MFS needs to ensure it can consume those fields.
=> Bump to new DSI dev version (again)

metricflow-semantics/requirements-files/requirements.txt, requirements-files/requirements.txt
We don't want to receive metric fields that our pydantic implementations don't know how to handle, so I'm bumping the version here before it can be bumped in other parts of dbt.
I'll bump MFS after this.
=> Bump dsi version to allow for 'is_private' on metrics from mantle

metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/resolver/test_other_manifest.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/resolver/test_sg_resolver_output.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/sg_tester.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_other_manifest.py/str/test_measure_with_cyclic_join_path__result.txt
This PR adds a test for group-by items using the cyclic manifest to verify that join cycles do not cause an infinite loop.
=> Add test for group-by items using the cyclic manifest

.changes/unreleased/Under the Hood-20251002-122925.yaml, .changes/unreleased/Under the Hood-20251002-123044.yaml, .changes/unreleased/Under the Hood-20251002-123232.yaml, .changes/unreleased/Under the Hood-20251002-123407.yaml, .changes/unreleased/Under the Hood-20251002-123447.yaml, .changes/unreleased/Under the Hood-20251002-123542.yaml, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/sg_linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/trie_resolver/group_by_metric_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/resolver/test_sg_resolver_output.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/resolver/test_sg_resolver_performance.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/sg_tester.py, metricflow/engine/metricflow_engine.py
This PR consolidates methods that handle measures and metrics separately in `GroupByItemSetResolver` to aid the `measure -> simple metric` migration.
=> Consolidate measure / metric methods of `GroupByItemSetResolver`

.changes/unreleased/Features-20251002-171248.yaml, metricflow-semantics/metricflow_semantics/model/dbt_manifest_parser.py
Depends on #1876 
Upstream PR bumps the dsi version, implicitly updating tests to using the default ruleset from dsi.  We can't do that for production MF rn because MF uses an extra transformation internally, so this PR adds all the newer built in PRs from dsi to metricflow-semantics/metricflow_semantics/model/dbt_manifest_parser.py to be used in real circumstances.
(If time was less limited before coalesce, I'd prefer to move the rule upstream if possible, but I don't want to pick up extra work before code freeze.)
Edit: There's also a rule (AddInputMeasuresToMetrics) that only works in dsi.  It probably merits a refactor/rewrite later to clean up the usage code here, but I'd rather prioritize getting this updated here for now.
=> Get MF using the new dsi transformations

.changes/unreleased/Under the Hood-20251002-131616.yaml, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/annotated_spec_linkable_element_set.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/recipe_writer_weight.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/attribute_resolution/sg_linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/trie_resolver/group_by_metric_resolver.py, metricflow-semantics/metricflow_semantics/experimental/semantic_graph/trie_resolver/simple_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/element_filter.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set_base.py, metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py, metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py, metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py, metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py, metricflow-semantics/metricflow_semantics/specs/patterns/entity_link_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/no_group_by_metric.py, metricflow-semantics/metricflow_semantics/specs/patterns/spec_pattern.py, metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/resolver/test_sg_resolver_output.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/resolver/test_sg_resolver_performance.py, metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/sg_tester.py, metricflow/engine/metricflow_engine.py, tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py
This PR changes the names of the fields in `GroupByItemSetFilter` to be more noun-like and adds `.create()` to make it easier to instantiate.
=> Assorted fixes for `GroupByItemSetFilter`

metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py, metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/ParseQueryResult/test_parse_and_validate_where_constraint_dims__result.txt
There's a bug in MFS due to the `LooseTimeDimensionParameter` workaround. This workaround was intended to allow you to pass a grain on a categorical dimension without error in order to avoid breaking some integrations. However, it also has the unintended consequence of not raising an error if the grain you requested is not supported for the selected time dimension. Adding this parameter will enable fixing this issue in MFS. Draft PR [here](https://github.com/dbt-labs/metricflow-server/pull/1618) to see how this will be used.
=> Enable `DimensionPattern` without time dimensions
