dbt-labs/metricflow

- README.md
added install directions for homebrew
> updating readme with homebrew postgres

- attribution.md
Removing `staging` from previous staging repo.
> [Attribution] Remove staging

- metricflow/test/model/validations/test_unique_valid_name.py
This test was failing in CI sometimes, and began to fail quite persistently,
due to an issue with the way we were generating invalid models.
The core issue is that the invalid model element is being generated by
mutating an existing valid model to conform to the error. For cross-element
name checks we had to rename a dimension, but if you rename a primary
time dimension the model validator fails with the wrong error.
To sidestep this problem for the time being we simply restrict the mutated
dimension to one of type CATEGORICAL. Longer term we should create very simple
invalid models that match the validation error types, or models with parameterized
names so we can pass concrete values to the template to generate the errors we need.
Fixes #17
> Fix non-deterministic failures in test_cross_element_names

- README.md
Remove the Interfaces that are part of the Transform commercial offering.
> Remove interfaces which are part of Transform

- CHANGELOG.md
Catalogues changes for minor version deployment 0.92.1
> Update CHANGELOG for 0.92.1

- .gitignore
- metricflow/cli/main.py
This PR provide a super small fix for [this](https://github.com/transform-data/metricflow/issues/56) issue
> Fixed  mf query command displayed in tutorial

- metricflow/api/metricflow_client.py
Currently, when calling `MetricFlowConfig.from_config()` it defaults to using the default location of where the MetricFlow configs are `{HOME}/.metricflow/config.yml`. This restricts the user from being flexible to create config files elsewhere and dynamically use different configs on the fly. So in order to further enable users to setup MetricFlow in a more streamlined fashion, this PR will enhance the `from_config` constructor.
- provide the ability to pass in `config_file_path` via `from_config`
- this is an optional parameter and will default back to the original behaviour of using the default config path
```python
mf = MetricFlowClient.from_config("path/to/test_config.yml")  # will build using the test_config.yml file
mf = MetricFlowClient.from_config() # will act as normal and use …
```
> Add the ability to construct a MetricFlowClient with an absolute path to configs

- metricflow/api/metricflow_client.py
This PR fixes a missing type annotation that should have been caught by the linter, but was not. Follow up item is to take a look at the linter configuration for this project.
> Add Missing Type Annotation

- .github/workflows/cd-sql-engine-tests.yaml
Testing the SQL Engine tests when working directly with repo.
> Adding SQL Engine test workflow

- metricflow/model/parsing/dir_to_model.py
The `UserConfiguredModel` contains 3 core classes, `[DataSource, Materialization, Metric]`. However, there is no flexibility in allowing for adding extra (but not necessary for open source)attributes to the classes. This PR allows for passing custom subclasses of the 3 core classes. This would enable the ability to build custom classes that would be parsed by the parser.
```python3
class DataSourceWithDescription(DataSource):
"""DataSource class with description."""
description: str
parse_yaml_files_to_model(files, data_source_class=DataSourceWithDescription)
```
> Add the ability to pass subclasses to parser

- metricflow/test/sql_clients/test_sql_client.py
This PR updates `test_dry_run` to have a more positive verification for a dry run operation and `test_dry_run_of_bad_query_raises_exception` to work for different engines.
> Update tests for SqlClient.dry_run()

- metricflow/test/compare_df.py
- metricflow/test/integration/test_cases/itest_metrics.yaml
This PR fixes an issue where dataframes may not be compared correctly when there are NULL / NaN values in the dataframe.
> Fix Dataframe Comparison in Tests

- metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/customer_other_data.yaml
- metricflow/test/integration/test_cases/itest_multi_hop_join.yaml
- metricflow/test/model/semantics/test_linkable_spec_resolver.py
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_composite_identifier__plan0.xml
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_composite_identifier_with_join__plan0.xml
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_composite_identifier_with_order_by__plan0.xml
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_multihop_node__plan0.xml
This PR removes a dimension specified in the test data source 'customer_other_data' that does not exist in the source table.
> Remove Incorrect Dimension in Test Data Source 'customer_other_data'

- .gitattributes
As the title. The generated files are pretty overwhelming for review.
Stack on https://github.com/transform-data/metricflow/pull/99
> chore: mark snapshots as generated

- metricflow/cli/main.py
This PR update behavior to exit the CLI on SIGINT / SIGTERM.
> Exit on SIGINT / SIGTERM

- metricflow/cli/main.py
- metricflow/cli/utils.py
- metricflow/sql_clients/duckdb.py
- metricflow/sql_clients/sql_utils.py
This PR enables the use of PostgreSQL as a dialect.
> Add CLI Support for PostgreSQL

- metricflow/cli/main.py
- metricflow/cli/utils.py
- metricflow/sql_clients/sql_utils.py
There was a rebase error with: https://github.com/transform-data/metricflow/pull/118, so re-adding that commit.
> Add CLI support for PostgreSQL (redo)

- pyproject.toml
> Release v0.100.1

- pyproject.toml
> Release 0.100.2

- metricflow/sql_clients/duckdb.py
> Fix a typo in duckdb sql client

- metricflow/model/data_warehouse_model_validator.py
- metricflow/test/model/validations/test_data_warehouse_tasks.py
We were running into an issue where the generation of queries for metrics were taking multiple minutes. This was problematic because when used in a server setting, this meant that the timeout wasn't being respected. This PR moves the generation of queries for data warehouse validations to be delayed until actually running the task.
> Refactor query generation for data warehouse tasks to happen in the query runner

- metricflow/cli/main.py
- metricflow/cli/utils.py
- metricflow/model/validations/validator_helpers.py
- metricflow/test/cli/test_cli.py
• Issues are only printed as the last operation before returning
• `Warnings` and `Future-Errors` are only printed if `validate-configs` is run with flag `--show-all`
• Summary for issue types are printed for each step
```
$ mf validate-configs
✔ 🎉 Successfully linted config YAML files
✔ 🎉 Successfully build model from configs
✔ 🎉 Finished validating data sources against data warehouse, no errors found
✖ Issues found when validating dimensions against data warehouse
✔ 🎉 Finished validating metrics against data warehouse, no errors found
• ERROR: with data source `salesforce_users` in file `users.yaml` on line #2 - Failed to query dimensions in data warehouse for data source `salesforce_users`
Recieved following error from data warehouse:
(snowflake.connector.errors.ProgrammingError) …
```
> Better output for 'mf validate-configs'

- CONTRIBUTING.md
- Makefile
- local-data-warehouses/README.md
Small tweaks to improve development flow:
1. Clarifies docker requirements for running Postgres
2. Adds `make postgres` command to makefile to bring it in line with docs
3. Improves contributor documentation
Yeah yeah separate commits but this is tiny so let's just do it
in one.
> Improve developer documentation

- metricflow/cli/main.py
This flips the flag from https://github.com/transform-data/metricflow/pull/154 to default off
> Flip SQL Description Flag to default off

- CHANGELOG.md
- attribution.md
- pyproject.toml
See changelog for updates in this release.
Note the version bump is from 0.100.2 to 0.110.0 to reflect the breaking changes that will come along with this deployment.
> Release 0.110.0

- CHANGELOG.md
- pyproject.toml
- Bugfix for column ordering
- Improvement on validation output and processing
- Metadata cleanup
- Use BETWEEN
> Release 0.110.1

- metricflow/cli/main.py
- metricflow/model/data_warehouse_model_validator.py
- metricflow/test/model/validations/test_data_warehouse_tasks.py
We haven't been validating model measures against the data warehouse. This PR remedies that.
> Add Measure based Data Warehouse Validations

- README.md
- metricflow/cli/main.py
This PR updates the tutorial documentation to use the recently-added `metric_time` feature.
> Update Tutorial to Use metric_time

- metricflow/cli/custom_click_types.py
- metricflow/cli/main.py
- metricflow/cli/utils.py
- metricflow/dataflow/sql_column.py
- metricflow/errors/errors.py
- metricflow/inference/context/base.py
- metricflow/inference/context/data_warehouse.py
- metricflow/inference/context/snowflake.py
- metricflow/inference/models.py
- metricflow/inference/renderer/base.py
- metricflow/inference/renderer/config_file.py
- metricflow/inference/renderer/stream.py
- metricflow/inference/rule/base.py
- metricflow/inference/rule/defaults.py
- metricflow/inference/rule/rules.py
- metricflow/inference/runner.py
- metricflow/inference/solver/base.py
- metricflow/inference/solver/weighted_tree.py
- metricflow/test/cli/test_custom_click_types.py
- metricflow/test/dataflow/test_sql_column.py
- metricflow/test/inference/context/test_data_warehouse.py
- metricflow/test/inference/context/test_snowflake.py
- metricflow/test/inference/renderer/test_config_file.py
- metricflow/test/inference/rule/conftest.py
- metricflow/test/inference/rule/test_defaults.py
- metricflow/test/inference/rule/test_rules.py
- metricflow/test/inference/solver/test_weighted_tree.py
- metricflow/test/inference/test_models.py
This is a new PR for data source inference. It contains the same contents of #192, but all the commit history has been reworked by adding all files manually again through a separate branch.
> feature: data source inference

- CHANGELOG.md
- attribution.md
- pyproject.toml
- Minor attribution updates from FOSSA
- Changelog updates to cover updates, especially the new features
> Release 0.111.0

- metricflow/model/model_validator.py
- metricflow/model/validations/validator_helpers.py
We recently forked model validation into separate threads via calls
to ProcessPoolExecutor, which pickles the inputs and outputs to the
job. This can apparently cause idiosyncratic behavior when combined
with Pydantic objects, as a consistent local test failure suggests.
This manifests with the following error snippet, but does not occur
in CI runs:
`AttributeError: Can't get attribute '_Pydantic_DataSourceReference_140501776576224' on <module 'pydantic.dataclasses'`
Rather than mess around with internal pickling and unpickling this
commit changes our approach to use Pydantic's serialization support
to pass raw data across. This will be slower per thread, but
more robust to different configurations.
> Serialize validation inputs and outputs for use in ProcessPoolExecutor

- CHANGELOG.md
- attribution.md
- pyproject.toml
See changelog updates for details
Preview: https://test.pypi.org/project/metricflow/
> Release 0.111.1

- metricflow/model/parsing/dir_to_model.py
We've been running into an issue recently, specifically with Windows users wherein ASCII content is being copied to and saved in a UTF-8 file. During parsing this causes a cryptic error message
```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2907500: character maps to `<undefined>`
```
to occur during reading of the model config files. Assuming / guessing the content of the file (and ignoring unknown characters) seems dangerous as this has potential to make parts of the config invalid during validation and thus becoming even harder to debug. Additionally, files could potentially contain mixed encoded content. Thus the safest thing to do seems to be explain what is happening and offer possible remediations.
> Add more helpful error message when file decoding fails

- metricflow/model/validations/measures.py
- metricflow/test/model/validations/test_measures.py
There is a issue where unexpected behaviour occurs when you try to have a different base time granularity for a measure's non_additive_dimension and it's agg_time_dimension. This validation is to ensure that both the base time granularities are the same.
> Add more validations to NonAdditiveDimension

- metricflow/sql_clients/databricks.py
In `DatabricksSqlClient`, clean up URL parsing and `create_table_from_dataframe` code.
> Databricks Cleanup

- metricflow/protocols/sql_client.py
- metricflow/sql_clients/base_sql_client_implementation.py
- metricflow/sql_clients/big_query.py
- metricflow/sql_clients/databricks.py
- metricflow/sql_clients/snowflake.py
- metricflow/sql_clients/sqlalchemy_dialect.py
This PR adds `list_tables` to the `SqlClient` protocol instead of `BaseSqlClientImplementation` so that it's exposed.
> Add SqlClient.list_tables

- CHANGELOG.md
- attribution.md
- pyproject.toml
See changelog for updates. Most notably.... DATABRICKS!
Preview: https://test.pypi.org/project/metricflow/0.120.0/
> Release 0.120.0

- CHANGELOG.md
- attribution.md
- pyproject.toml
Prepare for 0.130.0 dbt release
> Metricflow 0.130.0

- metricflow/model/validations/measures.py
- metricflow/test/model/validations/test_measures.py
The DISTINCT keyword is a problem for aggregation expressions,
because it effectively overrides the additivity of the aggregation
type. Since we rely on the aggregation type to tell us whether or
not a given measure is additive, we run the risk of doing an
inappropriate partial aggregation -> re-aggregation of these
measures.
This would produce incorrect results for a subset of queries,
which makes the framework behavior unpredictable.
Rather than allowing for this, we block the DISTINCT keyword from
use in COUNT expressions. Follow-ups should enable this safeguard for
SUM and AVG types, but COUNT(DISTINCT x) is generally more common
than SUM(DISTINCT x) so we start here.
> Add validation to block DISTINCT keyword on COUNT aggregations

- CHANGELOG.md
- attribution.md
- pyproject.toml
Minor improvements to dbt model querying plus some added safeguards
around COUNT aggregations and developer flows.
Deployment preview: https://test.pypi.org/project/metricflow/0.130.1/
> Release 0.130.1

- metricflow/model/validations/validator_helpers.py
The decorator `validate_safely` has been very useful. Specifically it catches issues during validation that we don't expect to happen. The problem recently has been that the issues built by `validate_safely` have become increasibly hard to read. This is mostly because the args passed to the method which ultimately raised an exception have been included in the base validation issue message. When the passed arg(s) are just a data source name, thats not a problem. But when the passed arg(s) incldue the entire UserConfiguredModel, it becomes an incomprehensible wall of text. This commit moves the method arguments and method name to the `extra_details` portion of the validation issue. Doing so makes the default printing of the validation issue more legible but still allows to get the detail …
> Improve legibility of issues raised by `validate_safely`

- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_nested_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuerySqlClient/test_nested_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_nested_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DatabricksSqlClient/test_nested_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_nested_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/PostgresSqlClient/test_nested_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_nested_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/RedshiftSqlClient/test_nested_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_derived_metric__plan0_optimized.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_nested_derived_metric__plan0.sql
- metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/SnowflakeSqlClient/test_nested_derived_metric__plan0_optimized.sql
This PR adds missing snapshots for some SQL engines.
> Add Missing Test Snapshots

- metricflow/sql_clients/big_query.py
- metricflow/sql_clients/postgres.py
- metricflow/sql_clients/redshift.py
- metricflow/sql_clients/snowflake.py
This PR implements the query cancellation methods for the SQL engines (minus Databricks).
> Implement Cancel Methods for Sql Engines

- metricflow/test/sql_clients/test_async.py
Since cancellation of queries is not guaranteed by SQL engines, the unit test should retry a few times in case the cancellation didn't work.
> Retry Cancel When Testing AsyncSqlClient.cancel_request()

- metricflow/execution/execution_plan.py
- metricflow/plan_conversion/dataflow_to_execution.py
- metricflow/sql_clients/sql_utils.py
This PR updates the signatures of the methods in the execution plan to support tagging SQL queries.
> Support Tagging SQL Queries in the Execution Plan

- README.md
> fix 2 links in README

- metricflow/sql_clients/databricks.py
Adding a log here to give us some details about when the query starts and what it looked like.
> Add Databricks log at query start

- metricflow/constraints/time_constraint.py
This PR changes the representation invariant check to a warning as there are some edge cases that haven't been solved yet.
> Change TimeRangeConstraint assertion to a warning

- CHANGELOG.md
- attribution.md
- poetry.lock
- pyproject.toml
Lots of changes. Highlights include:
- Derived metrics
- Versioned dimension (SCD Type II) join support
- Percentile measures
Breaking changes:
- API changes to SqlClient protocol might affect developers
- Bugfix for output data rendering may consolidate rows for multi-metric queries
TestPyPi upload: https://test.pypi.org/project/metricflow/0.140.0/
> Release 0.140.0

- metricflow/sql_clients/snowflake.py
This PR updates the `SnowflakeSqlClient.list_tables()` to use `information_schema` to sidestep the 10K row limit for `SHOW TABLES` used in the current implementation.
> Use information_schema for list_tables() in Snowflake

- .changes/unreleased/Under the Hood-20230424-162315.yaml
- dbt_semantic_interfaces/dbt_semantic_interfaces/objects/aggregation_type.py
- dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/measure.py
- dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/boolean_measure.py
- dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/convert_count.py
- dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/convert_median.py
- metricflow/aggregation_properties.py
- metricflow/dataflow/dataflow_plan.py
- metricflow/model/dbt_mapping_rules/dbt_metric_to_measure.py
- metricflow/model/semantics/data_source_semantics.py
- metricflow/model/transformations/dbt_to_metricflow.py
- metricflow/model/validations/measures.py
- metricflow/plan_conversion/dataflow_to_sql.py
- metricflow/specs.py
- metricflow/sql/sql_exprs.py
- metricflow/test/dataflow/builder/test_measure_additiveness.py
- metricflow/test/model/parsing/test_data_source_parsing.py
- metricflow/test/model/validations/test_data_warehouse_tasks.py
- metricflow/test/model/validations/test_dimension_const.py
- metricflow/test/model/validations/test_identifiers.py
- metricflow/test/model/validations/test_metrics.py
- metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py
> Moving AggregationType enum into dbt-semantic-interfaces

- .changes/unreleased/Under the Hood-20230427-102540.yaml
- .pre-commit-config.yaml
- metricflow/model/transformations/dbt_to_metricflow.py
- poetry.lock
- pyproject.toml
> Hard pinning dbt-core to 1.4

- .changes/unreleased/Breaking Changes-20230503-110825.yaml
- dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/dimension.py
- dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/schemas.py
- dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/schemas/metricflow.json
- metricflow/test/model/parsing/test_data_source_parsing.py
resolves #494 
The issue lays out why I _think_ this is helpful and the PR does just that.
> Removing DimensionTypeParams time_format

- metricflow/model/validations/data_sources.py
These validations are moving to dbt_semantic_interfaces. In dbt-semantic-interfaces there won't be a defined `SUPPORTED_GRANULARITIES`, just the TimeGranularty Enum values. Thus checking against this would be pointless because it has to be a valid TimeGranularity before this point. Long term if MetricFlow for some reason doesn't support a granularity defined in dbt-semantic-interfaces, then at that point we should write a custom rule in MetricFlow validating that only the supported granularities are used.
> Remove `SUPPORTED_GRANULARITIES` check from `DataSourceTimeDimensionWarningsRule`

- dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/schemas/metricflow.json
With the change of constraint -> filter, the json schema needs to be updated
<!--- 
> update schema with constraint -> filter

- pyproject.toml
Version update for initial dev release after the cutover to dsi
> MetricFlow 0.200.0.dev0

- .changes/unreleased/Under the Hood-20230522-195743.yaml
- metricflow/cli/utils.py
- metricflow/configuration/env_var.py
- metricflow/errors/errors.py
- metricflow/sql/sql_exprs.py
- metricflow/sql/sql_plan.py
- metricflow/sql_clients/sql_utils.py
- metricflow/test/fixtures/cli_fixtures.py
- metricflow/test/plan_utils.py
- poetry.lock
- pyproject.toml
resolves #546 
This PR updates mypy to 1.3.0, the current latest version.
<!--- 
> Update mypy to 1.3.0

- README.md
- pyproject.toml
This commit includes a version bump for dev1 release, along with
updates to licensing metadata in the release packages.
> Update metadata for 0.200.0.dev1 release

- .changes/unreleased/Under the Hood-20230525-183003.yaml
- metricflow/engine/metricflow_engine.py
- metricflow/engine/models.py
- pyproject.toml
Needed for MFS metadata calls!
Sorry for all the line length changes, a bit distracting - I think it's because of the Hatch configuration Paul set up? Might need to configure pre-commit to work with Hatch properly ([I had to get pretty hacky with that to make it work in MFS](https://github.com/dbt-labs/metricflow-server/blob/488cb000c6df1aa673cabc20314d21b50308ace8/Makefile#L16)). 
Also note that I bumped the dev version here, hoping to get a dev release out ASAP with this change!
<!--- 
3. run `changie new` to [create a changelog …
> Add qualified name to MFEngine Dimension

- metricflow/cli/sample_models/countries.yaml
- metricflow/cli/sample_models/customers.yaml
- metricflow/cli/sample_models/transactions.yaml
- metricflow/test/cli/test_cli.py
resolves #563
Sample models were broken after the DSI changes due to owners still being present. Added tests for tutorial and test for parsing the sample tutorial models to prevent this from happening in the future.
<!--- 
> Fix tutorial and added tests

- metricflow/engine/metricflow_engine.py
Missed adding the method to protocol class in https://github.com/dbt-labs/metricflow/pull/566
<!--- 
> added explain dimension values method to protocol

- pyproject.toml
> Bump dev version

- metricflow/cli/sample_models/countries.yaml
- pyproject.toml
Bump DSI to `0.1.0.dev5` and update the broken tutorial model.
<!--- 
> Bump DSI and update MF

- .github/pull_request_template.md
> Fix Typo "resolves" -> "Resolves" in Github PR template

- .changes/unreleased/Features-20230620-092430.yaml
- CONTRIBUTING.md
- Makefile
- metricflow/engine/metricflow_engine.py
- metricflow/test/generate_snapshots.py
Resolves #609
Implements the feature described in the linked issue.
<!--- 
> Add Snapshot Generation Script

- .github/actions/setup-python-env/action.yaml
- metricflow/sql_clients/sql_utils.py
- metricflow/test/fixtures/setup_fixtures.py
This PR adds a warning if a test session could benefit from changing the parallelism.
<!--- 
> Print warning to parallelize tests when applicable

- pyproject.toml
Bump dbt-core dependency to 1.6.0b5 and metricflow to 0.200.0.dev5
<!--- 
> bump dbt-core to 1.6.0b5 and mf to 0.200.0.dev5

- pyproject.toml
Bump MetrifFlow version to dev7 to release new dimension values methods.
> Bump to dev7

- pyproject.toml
Bump MetricFlow to dev8
<!--- 
> bump to dev8

- metricflow/test/generate_snapshots.py
This adds the `--persistent-source-schema` flag to the `pytest` call in the snapshot generation script for a significant speedup.
<!--- 
> Use `--persistent-source-schema` in the Snapshot Generation Script

- pyproject.toml
Bump MetricFlow to 0.200.0.dev9
<!--- 
> bump to 0.200.0.dev9

- .changes/unreleased/Features-20230628-165151.yaml
- dbt-metricflow/LICENSE
- dbt-metricflow/README.md
- dbt-metricflow/pyproject.toml
Create the initial `dbt-metricflow` package to be published onto pypi. The use case of this package is to bundle the versioning for `metricflow` and `dbt-core` such that they would work together in parallel and allow the user to use the `mf` and `dbt` CLI. Also, has optional extras installs for the different dbt adapters that are integrated with MetricFlow.
This package will work to manage the versioning between `metricflow` and `dbt-core` and the `dbt-adapters` such that they work nicely together. 
This package will include the MetricFlow CLI (and possibly the dbt Core CLI) code and allow MetricFlow to rip out the dependency on `dbt-core`
Resolves SEM-392
<!--- 
1. read [the contributing …
> Create dbt-metricflow package

- pyproject.toml
Bump metricflow to 0.200.0.dev10
<!--- 
> bump to 0.200.0.dev10

- pyproject.toml
> bump MetricFlow to 0.200.0.dev11

- pyproject.toml
Includes changes from this PR https://github.com/dbt-labs/metricflow/pull/651
<!--- 
> bump to 0.200.0.dev12

- dbt-metricflow/pyproject.toml
> bump dbt-metricflow with the rc version of dbt-core and dsi

- dbt-metricflow/pyproject.toml
Includes the change of loosening python dependency
> bump dbt-metricflow to 0.0.4

- metricflow/cli/dbt_connectors/dbt_config_accessor.py
Resolves #683
Communicates how to generate `semantic_manifest.json` if it is missing.
> Improve CLI error message for generating semantic_manifest

- metricflow/cli/dbt_connectors/adapter_backed_client.py
The dry_run method in AdapterBackedSqlClient is a bit messy due to
some snags with using the SQLAdapter implementation of dbt's
BaseAdapter.validate_sql method.
Once those issues are resolved we can consolidate to a single call
type, which will require a connection with a standardized identifier.
In the interim, we can consolidate the SQLAdapter subclass behavior
onto a single named connection invocation and simply handle the results
in a special way if that adapter happens to be Databricks.
> Clean up dry run method in AdapterBackedSqlClient

- pyproject.toml
Deploy dev release with changes to primary entity/dimension parsing
> Release MetricFlow 0.200.0.dev15

- pyproject.toml
We're ready to deploy the rc for 0.200.0!
> Update versions for 0.200.0.rc1

- .changes/unreleased/Under the Hood-20230816-150030.yaml
- metricflow/test/generate_snapshots.py
Fixes a couple of issues in the script for regenerating snapshots.
> Update snapshot generation script

- pyproject.toml
> bump to 0.202.0.dev1

- dbt-metricflow/pyproject.toml
Updates MetricFlow version to 0.202.0 and dbt-metricflow to 0.3.0
> Release PR for dbt-metricflow 0.3.0

- pyproject.toml
> Bump to 0.203.0.dev2

- metricflow/cli/main.py
- metricflow/cli/sample_dbt_models/sample_models/metrics.yml
With the addition of unique labels validation, the tutorial model fails on that. Update the labels to resolve that. Additionally, cleaned up the tutorial message to remove outdated info and added link to adding time spine model.
> Fix tutorial

- .changes/unreleased/Under the Hood-20231127-133132.yaml
- metricflow/test/model/test_where_filter_spec.py
This is just a simple test to sanity-check myself.
> Test to ensure Dimension and TimeDimension syntax are identical in the case of a time dimension

- pyproject.toml
Bump dev version to 0.204.0.dev1 for the bug fix https://github.com/dbt-labs/metricflow/pull/909
> bump to 0.204.0.dev1

- .changes/unreleased/Under the Hood-20231214-113549.yaml
- metricflow/model/data_warehouse_model_validator.py
Addresses this issue https://dbt-labs.slack.com/archives/C05K4R7KZ5Z/p1702571237772439. No dev release should be necessary for this.
> Fixed typo in error message

- .github/atlas.yaml
> add tracking for github advanced security

- pyproject.toml
> Update MF Package Version to 0.204.0.dev5

- metricflow/query/issues/group_by_item_resolver/no_common_items.py
- metricflow/query/issues/group_by_item_resolver/no_matching_items_for_measure.py
- metricflow/query/issues/group_by_item_resolver/no_matching_items_for_no_metrics_query.py
- metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_defined_filters_in_multi_metric_query__result_0.txt
- metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_defined_where_filter__result_0.txt
- metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_group_by_item__result_0.txt
- metricflow/test/snapshots/test_suggestions.py/str/test_suggestions_for_multiple_metrics__result_0.txt
This PR updates the issue messages so that they span fewer columns for easier viewing with side-by-side terminals.
> Make Query Issue Messages More Narrow for Easier Console Viewing

- pyproject.toml
> Update MetricFlow Package Version to 0.204.0.dev7

- metricflow/dataflow/builder/dataflow_plan_builder.py
- metricflow/engine/metricflow_engine.py
- metricflow/plan_conversion/dataflow_to_sql.py
- metricflow/sql/optimizer/rewriting_sub_query_reducer.py
This PR:
* Adds logging for the result of an optimization for dataflow plans / SQL query plans.
* Adds a retry that builds a dataflow plan without optimizers if there is an exception building a dataflow plan / converting dataflow to SQL / creating an execution plan.
* Updates an erroneous error log call to be info.
> Improve Optimizer Logging / Robustness

- .changes/unreleased/Docs-20240126-133614.yaml
- metricflow/cli/main.py
The tutorial message did not reflect the changes made in #642 : replacing `--group-bys` by `--group-by`
> change group-bys to group-by in the tutorial message

- pyproject.toml
Bumping to dev3 to get exports into the savedquery object in MFE
> bump to 0.204.1.dev3

- pyproject.toml
> bump to 0.204.1.dev4

- metricflow/test/fixtures/semantic_manifest_yamls/simple_manifest/metrics.yaml
- metricflow/test/plan_conversion/dataflow_to_sql/test_conversion_metrics_to_sql.py
I accidentally merged https://github.com/dbt-labs/metricflow/pull/1037 without addressing @tlento's feedback, so I addressed it here.
> Address missed PR feedback

- .changes/unreleased/Breaking Changes-20240215-114702.yaml
Resolves #1034 
This PR adds a missing change log entry for #1026.
> Add Change Log for #1034

- metricflow/dataflow/builder/dataflow_plan_builder.py
- metricflow/dataset/convert_semantic_model.py
- metricflow/dataset/sql_dataset.py
This PR makes some minor fixes to improve logging / remove unused code.
> Minor Assorted Fixes

- pyproject.toml
> Update Package Version to `0.205.0.dev0`

- metricflow/dataflow/nodes/compute_metrics.py
- metricflow/plan_conversion/dataflow_to_sql.py
- metricflow/plan_conversion/instance_converters.py
- metricflow/plan_conversion/select_column_gen.py
Handle `GroupByMetrics` in instance converters.
> `GroupByMetric` instance converters

- tests/integration/test_cases/itest_dimensions.yaml
Adds a test that I had a TODO up for.
> Add test covering min-max queries on a metric_time range

- pyproject.toml
Got some outdated links in the `pyproject.toml`! Updated here.
> Update outdated Transform links

- metricflow/engine/metricflow_engine.py
The DataflowPlan optimizers are, at least in theory, applied as part
of a loop of optimizer sets to try, with each iteration of the loop
theoretically applying a different set of optimizers, and concluding
with an empty set. The idea behind this was quite clearly to ensure
that the optimizers don't cause valid queries to fail due to some
incorrect optimization path. Why we deemed this necessary is completely
unclear, as no documentation has been provided to explain this bit
of complexity.
What was happening in practice was that on every iteration we were
applying the same hard-coded set consisting of the SourceScanOptimizer,
and the loop itself would incorrectly report error logs suggesting
that other things were being attempted.
Since this logic has never been applied correctly, the …
> Remove pointless loop over DataflowPlan optimizer sets

- metricflow/model/semantics/linkable_spec_resolver.py
Fixes a small oversight. This didn't seem to cause any issues so it might not be used anywhere, but maybe will be eventually.
> Pass join_path where missed in group by resolution

- metricflow/model/semantics/metric_lookup.py
- metricflow/model/semantics/semantic_model_lookup.py
The ElementPathKey object is primarily used for accessing the set
of linkable elements associated with a given semantic model element
and the linkable path used to get to it from a query or metric.
The accessors implicitly require that granularity be set on all
ElementPathKey instances associated with Time Dimension elements.
Passing in an ElementPathKey for a time dimension without a granularity
will result in it being mistaken for a categorical dimension, causing
the path key lookups to behave strangely.
Attempting to make this implicit requirement explicitly enforced
uncovered an area of the codebase using ElementPathKey as a deduplication
mechanism for TimeDimensions. This convenience usage is harmless in and
of itself, but if those ELementPathKey instances were ever used for
access …
> Remove granularity-free ElementPathKey instances

- metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
- metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
- metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_spec_resolver.py
As described in title. Simplifies code that will be stacked on this branch.
> Add helper method SemanticModelJoinPath.from_single_element()

- metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
Some customers have a misconfiguration (I think) that is triggering this error. We should roll out a validation to get that fixed instead of blocking all their queries with this error.
> Remove error that users are running into

- pyproject.toml
> Update package version to `0.206.0.dev3`

- metricflow-semantics/metricflow_semantics/specs/column_assoc.py
- metricflow-semantics/metricflow_semantics/specs/dunder_column_association_resolver.py
- metricflow/plan_conversion/dataflow_to_sql.py
- tests_metricflow/dataflow/builder/test_node_data_set.py
For the love of code reduction!!
> Use default arg for `SingleColumnCorrelationKey`

- tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py
- tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_cumulative_metric_no_window_or_grain_with_metric_time__dfp_0.xml
Another test using a grain that's not allowed for the metric.
> Fix another funky test

- pyproject.toml
> Update package version to `0.207.0.dev0`

- pyproject.toml
> Update package version to `0.207.0.dev1`

- metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
- metricflow-semantics/metricflow_semantics/specs/group_by_metric_spec.py
Tiny cleanup. Moved this class to DSI recently, but hadn't gotten around to removing the MF implementation.
> Use DSI `GroupByMetricReference`

- metricflow-semantics/tests_metricflow_semantics/specs/test_spec_serialization.py
> Add a test for serializing `WhereFilterSpec`

- metricflow/plan_conversion/dataflow_to_sql.py
Cleanup. Docs link is not changing after all so this is valid.
> Remove unneeded TODO

- metricflow-semantics/metricflow_semantics/dag/dag_to_text.py
This PR changes the method to format a DAG to text to not use Jinja as during performance profiling, Jinja was found to be quite slow.
> Update DAG formatting to not use Jinja

- extra-hatch-configuration/requirements.txt
- metricflow-semantics/extra-hatch-configuration/requirements.txt
- metricflow-semantics/metricflow_semantics/time/time_spine_source.py
Need to get this upgraded and then upgrade MF in MFS before the core spec change can merge. Otherwise, there might be a DSI version coming from a manifest that we aren't able to parse in MFS.
> Upgrade DSI

- metricflow/plan_conversion/dataflow_to_sql.py
- tests_metricflow/query_rendering/test_custom_granularity.py
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/BigQuery/test_simple_metric_with_custom_granularity_and_join__plan0.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/BigQuery/test_simple_metric_with_custom_granularity_and_join__plan0_optimized.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Databricks/test_simple_metric_with_custom_granularity_and_join__plan0.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Databricks/test_simple_metric_with_custom_granularity_and_join__plan0_optimized.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/DuckDB/test_simple_metric_with_custom_granularity_and_join__plan0.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/DuckDB/test_simple_metric_with_custom_granularity_and_join__plan0_optimized.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Postgres/test_simple_metric_with_custom_granularity_and_join__plan0.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Postgres/test_simple_metric_with_custom_granularity_and_join__plan0_optimized.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Redshift/test_simple_metric_with_custom_granularity_and_join__plan0.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Redshift/test_simple_metric_with_custom_granularity_and_join__plan0_optimized.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Snowflake/test_simple_metric_with_custom_granularity_and_join__plan0.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Snowflake/test_simple_metric_with_custom_granularity_and_join__plan0_optimized.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Trino/test_simple_metric_with_custom_granularity_and_join__plan0.sql
- tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Trino/test_simple_metric_with_custom_granularity_and_join__plan0_optimized.sql
SQL rendering tests for querying time dimensions that require a join with custom granularity.
> SQL rendering tests for custom granularity time dimensions requiring join

- metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py
- metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py
This PR updates additional log lines to use `LazyFormat` as they were missed during the initial migration.
>  Lazy format additional log lines

- metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py
- metricflow-semantics/metricflow_semantics/time/granularity.py
The methods in `ExpandedTimeGranularity` benefits from caching as they are called in many cases where `TimeDimensionSpecs` are created. `*Spec` objects are one of the most frequently created / used objects.
> Cache methods in `ExpandedTimeGranularity`

- metricflow/dataflow/dataflow_plan.py
- metricflow/dataflow/dataflow_plan_visitor.py
- metricflow/dataflow/nodes/add_generated_uuid.py
- metricflow/dataflow/nodes/aggregate_measures.py
- metricflow/dataflow/nodes/combine_aggregated_outputs.py
- metricflow/dataflow/nodes/compute_metrics.py
- metricflow/dataflow/nodes/constrain_time.py
- metricflow/dataflow/nodes/filter_elements.py
- metricflow/dataflow/nodes/join_conversion_events.py
- metricflow/dataflow/nodes/join_over_time.py
- metricflow/dataflow/nodes/join_to_base.py
- metricflow/dataflow/nodes/join_to_custom_granularity.py
- metricflow/dataflow/nodes/join_to_time_spine.py
- metricflow/dataflow/nodes/metric_time_transform.py
- metricflow/dataflow/nodes/min_max.py
- metricflow/dataflow/nodes/order_by_limit.py
- metricflow/dataflow/nodes/read_sql_source.py
- metricflow/dataflow/nodes/semi_additive_join.py
- metricflow/dataflow/nodes/where_filter.py
- metricflow/dataflow/nodes/window_reaggregation_node.py
- metricflow/dataflow/nodes/write_to_data_table.py
- metricflow/dataflow/nodes/write_to_table.py
- metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py
- metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py
- metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py
- metricflow/execution/dataflow_to_execution.py
- metricflow/plan_conversion/dataflow_to_sql.py
- tests_metricflow/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
This PR moves `DataflowPlanNodeVisitor` to reduce file sizes.
> Move `DataflowPlanNodeVisitor` to a separate file

- metricflow/plan_conversion/dataflow_to_sql.py
> Add log line for SQL generation option set

- dbt-metricflow/dbt_metricflow/__about__.py
- dbt-metricflow/pyproject.toml
- metricflow/__about__.py
- pyproject.toml
This allows the package version to be updated with `hatch version ...`, which simplifies release automation.
> Update `pyproject.toml` files to use a dynamic version configuration

- metricflow/dataflow/builder/dataflow_plan_builder.py
This aims to make it easier to 1) read through the dataflow plan builder at a high level, and 2) distinguish which time spine features are being addressed in each of these code snippets.
There should be no functional changes.
> Add helper functions for building `JoinToTimeSpineNodes`

- dbt-metricflow/dbt_metricflow/cli/cli_configuration.py
- dbt-metricflow/dbt_metricflow/cli/main.py
This PR updates the tutorial to check / better handle the flow when the dbt adapter is not installed.
> Update tutorial flow for missing adapter packages

- dbt-metricflow/dbt_metricflow/cli/sample_dbt_models/semantic_manifest.json
This prettifies `semantic_manifes_pretty.json` used in `mf tutorial` for easier debugging.
> Prettify`semantic_manifes_pretty.json`

- dbt-metricflow/dbt_metricflow/cli/tutorial.py
This PR makes some minor updates to the tutorial message
> Update tutorial message

- .changes/unreleased/Features-20250221-153551.yaml
- dbt-metricflow/dbt_metricflow/cli/main.py
- tests_metricflow/cli/conftest.py
- tests_metricflow/cli/test_cli_quiet.py
- tests_metricflow/snapshots/test_cli_quiet.py/str/DuckDB/test_explain__result.txt
- tests_metricflow/snapshots/test_cli_quiet.py/str/DuckDB/test_query__result.txt
> Add `--quiet` option to the `query` CLI command

- dbt-metricflow/extra-hatch-configuration/requirements-cli.txt
- extra-hatch-configuration/requirements.txt
Vulnerability context here https://github.com/dbt-labs/metricflow-server/security/dependabot/42
> Upgrade Jinja to fix a security vulnerability

- metricflow-semantics/metricflow_semantics/experimental/dataclass_helpers.py
- metricflow-semantics/metricflow_semantics/experimental/test_helpers/performance_helpers.py
- metricflow-semantics/metricflow_semantics/helpers/string_helpers.py
- metricflow-semantics/pyproject.toml
- metricflow-semantics/tests_metricflow_semantics/experimental/collection_helpers/dataclass_statement.py
- metricflow-semantics/tests_metricflow_semantics/experimental/collection_helpers/fast_frozen_dataclass_test_classes.py
- metricflow-semantics/tests_metricflow_semantics/experimental/collection_helpers/statement_helpers.py
- metricflow-semantics/tests_metricflow_semantics/experimental/collection_helpers/test_fast_frozen_dataclass.py
- pyproject.toml
This experimental PR adds a `fast_frozen_dataclass` decorator that improves the performance of frozen-dataclass use-cases by using regular dataclasses but relying on the type system to enforce immutability (frozen dataclasses are slower than regular dataclasses). In addition, performance is improved by caching the computed hash (see test cases).
> Add `fast_frozen_dataclass` decorator

- metricflow-semantics/metricflow_semantics/aggregation_properties.py
- metricflow-semantics/metricflow_semantics/specs/query_spec.py
- metricflow/dataflow/builder/dataflow_plan_builder.py
- tests_metricflow/fixtures/sql_clients/common_client.py
This PR contains assorted fixes / cleanup. Please view by commit.
> Assorted fixes / cleanup

- .changes/unreleased/Fixes-20250429-145426.yaml
- metricflow-semantics/metricflow_semantics/helpers/string_helpers.py
- metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/query_resolution_node.py
- metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_path.py
- metricflow-semantics/metricflow_semantics/query/query_parser.py
- metricflow-semantics/metricflow_semantics/query/resolver_inputs/query_resolver_inputs.py
- metricflow-semantics/tests_metricflow_semantics/snapshots/test_messages.py/str/test_empty_query__result.txt
- metricflow-semantics/tests_metricflow_semantics/snapshots/test_messages.py/str/test_long_invalid_metric__result.txt
This PR fixes typos / formatting of the error message when a query is empty.
> Fix error message with empty queries

- .changes/unreleased/Under the Hood-20250718-144933.yaml
- .gitignore
- metricflow-semantics/metricflow_semantics/collection_helpers/syntactic_sugar.py
- metricflow-semantics/metricflow_semantics/experimental/mf_graph/comparable.py
- metricflow-semantics/metricflow_semantics/experimental/mf_graph/graph_id.py
- metricflow-semantics/metricflow_semantics/experimental/mf_graph/mf_graph.py
- metricflow-semantics/metricflow_semantics/experimental/mf_graph/mutable_graph.py
- metricflow-semantics/metricflow_semantics/experimental/ordered_set.py
- metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
- metricflow-semantics/metricflow_semantics/time/granularity.py
- metricflow-semantics/tests_metricflow_semantics/experimental/mf_graph/formatting/test_svg.py
- metricflow-semantics/tests_metricflow_semantics/experimental/test_ordered_set.py
- metricflow/dataflow/dataflow_plan.py
This PR contains assorted fixes for classes that are later used for the semantic graph. Please view by commit.
> Assorted fixes for graph-related classes

- .changes/unreleased/Under the Hood-20250725-172502.yaml
- metricflow-semantics/metricflow_semantics/experimental/mf_graph/formatting/dot_attributes.py
- metricflow-semantics/metricflow_semantics/experimental/mf_graph/mf_graph.py
- metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/measure_subgraph.py
- metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/partial_graph_builder.py
- metricflow-semantics/metricflow_semantics/experimental/semantic_graph/builder/subgraph_generator.py
- metricflow-semantics/metricflow_semantics/experimental/semantic_graph/nodes/entity_nodes.py
- metricflow-semantics/metricflow_semantics/mf_logging/format_option.py
- metricflow-semantics/metricflow_semantics/mf_logging/pretty_formatter.py
- metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py
- metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/query_resolution_node.py
- metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/sg_00_minimal_manifest/__init__.py
- metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/sg_00_minimal_manifest/manifest.yaml
- metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/sg_00_minimal_manifest/project_configuration.yaml
- metricflow-semantics/tests_metricflow_semantics/experimental/mf_graph/formatting/mf_to_dot.py
- metricflow-semantics/tests_metricflow_semantics/experimental/mf_graph/formatting/mf_to_graphical_dot.py
- metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/builder/subgraph_test_helpers.py
- metricflow-semantics/tests_metricflow_semantics/experimental/semantic_graph/builder/test_subgraph_0_measure.py
- metricflow-semantics/tests_metricflow_semantics/fixtures/manifest_fixtures.py
- metricflow-semantics/tests_metricflow_semantics/mf_logging/test_pretty_print.py
- metricflow-semantics/tests_metricflow_semantics/snapshots/test_dot.py/str/test_dot_text__result.txt
- metricflow-semantics/tests_metricflow_semantics/snapshots/test_manifest_object_lookup.py/ManifestObjectLookup/test_lookup_attributes__result.txt
- metricflow-semantics/tests_metricflow_semantics/snapshots/test_subgraph_0_measure.py/str/test_minimal_manifest__result.txt
This PR adds a generator for edges related to measures in the semantic graph. Please view by commit.
> Add subgraph generator for measures

- metricflow/__about__.py
To be merged right after the new release.
> Bump to new dev version
